### ISSUE TITLE
[Vanilla bug] Barbarian rage skill

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1111]
Referring to: https://diablo2.diablowiki.net/Barbarian_(Diablo_I)

The Hellfire Barbarian has a skill called Rage. This skill is a short term buff that boosts his strength, vitality, and dexterity for 12 seconds. After that time he enters a 12 second lethargy phase, when those same attributes are reduced by the same amount. Afterwards his vitality is supposed to suffer a permanent penalty, however due to a bug in Hellfire, clicking on any item in his inventory will reset the vitality loss.

The whole thing looks like this.
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6093624/output.mkv.zip)

It doesn't matter if the belt or the inventory is clicked to restore the health.

**Comment by galaxyhaxz** [comment]
IMO the very concept of a skill giving a permanent loss is stupid. Why would anyone use the skill? A temporary lethargy makes sense, but perhaps it should stay broken as it is or have that feature removed.

This is similar to the repair/recharge skills, where you wouldn't want to use them on any item you care about as it will permanently damage them.

**Comment by Chance4us** [comment]
Yes, it's probably better to keep the bug in order to keep the game's originality.
Alternatively, the permanent penalty could be removed.

**Comment by galaxyhaxz** [comment]
Yep, and while were at it, skills like repair/recharge (though not for DevilX, but mods) have to go. A skill that repairs an item would have to suffer some kind of penalty to not remove the purpose of the blacksmith, but at the same time it ruins the point of the skill.

Same goes with the Bard having Identify as a skill, it breaks Deckard Cain. In my opinion skills should be focused on offensive much like Diablo 2.

**Comment by FitzRoyX** [comment]
> Afterwards his vitality is supposed to suffer a permanent penalty

It could be true given that the game has +vit potions, but it seems pretty far-fetched on the surface. I don't know if I trust a wiki saying perma statloss was intended behavior.

**Comment by GrayFace** [comment]
Since he loses life, what about making him lose HP instead of Max HP? E.g. when lethargy runs off leave him with 10-20% of HP he had at that moment.

As for approach to bugs that people might want to keep, in my patches I use 'hidden' ini settings for them. Such settings aren't there by default, but people that want the bug back can add it.

> Yep, and while we're at it, skills like repair/recharge (though not for DevilX, but mods) have to go. A skill that repairs an item would have to suffer some kind of penalty to not remove the purpose of the blacksmith, but at the same time it ruins the point of the skill.

I disagree. It's very different with items. Most staves are consumables that you deplete and sell, because mana potions are cheaper than recharging at the shop. (exceptions I've found are healing that's always cheaper on a staff and guardian that's cheaper if you have less then about 500 mana). Items with ok durability can be repaired with the skill exclusively and still last the entire game. Both skills make perfect sense, especially since Warrior has to repair more and has to buy more elixirs to max out, while Mage needs to invest into spells more than anyone else.

**Comment by StephenCWills** [comment]
I just reviewed the code here and did some playtesting. From what I can tell, there are no intended permanent stat losses associated with this skill. To the best of my understanding, here is a more accurate description of how the skill works.

**Rage Starts**
Duration: `clvl/10 + slvl/2 + 12.25 seconds`
Str: `+2*clvl`
Dex: `+1.5*clvl`
Vit: `+2*clvl`

**Lethargy Starts**
Duration: `clvl/10 + slvl/2 + 12.25 seconds`
Str: `-2*clvl`
Dex: `-1.5*clvl`
Vit: `-2*clvl`
HP: `-(MaxHP - HP)`
*Note: `MaxHP - HP` is calculated in the frame where Lethargy starts*

**Rage Ends**
HP: `-(MaxHP - HP) - 3*clvl`
*Note: `MaxHP - HP` is calculated in the frame where Lethargy ends, whereas `3*clvl` is calculated in the frame when the buff starts*

I think, because Rage is a skill, it is always cast at slvl 0. So duration is really just somewhere between 12.35 and 17.25 seconds depending on the character's level.

The bug described here occurs because the player's `_pHitPoints` are reduced, but `_pHPBase` is not. So triggering `CalcPlrItemVals()` during or after Lethargy by adjusting items in the player's inventory will cause the HP penalties to disappear. All other places in the code where the player loses HP will also update `_pHPBase` so `MI_Blodboil()` should probably do so as well.

Also, I get the feeling when reading the code that the `MaxHP - HP` penalty is actually a mistake, like the developer was attempting to capture the player's current damage level before calling `CalcPlrItemVals()` and then reapply it after the HP was adjusted by item stats. Just my two cents.

**Comment by AJenbo** [comment]
They got the scavengers health changes completely wrong, so why not.
