### ISSUE TITLE
Requirements information is cut off in store

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1167]
Requirements information in store + savegame:
![blade](https://user-images.githubusercontent.com/45902449/111009904-2770c600-8395-11eb-9db3-ee6357fee8e5.png)
[single_1.hsv.zip](https://github.com/diasurgical/devilutionX/files/6133668/single_1.hsv.zip)

Requirements information in game + savegame:
![blade2](https://user-images.githubusercontent.com/45902449/111009660-8e41af80-8394-11eb-8976-a992b168547c.png)
[single_2.hsv.zip](https://github.com/diasurgical/devilutionX/files/6133664/single_2.hsv.zip)

**Comment by julealgon** [comment]
Logic seems wrong in here:

https://github.com/diasurgical/devilutionX/blob/cb65d308cf6d71a0b0c813425a6f3fbfffd5ab39/Source/stores.cpp#L175-L185

Was there a recent change to requirement prints @AJenbo ? Seems like a refactor gone wrong here. The last requirement will always win, which is why only Dex is showing for Blade (which has STR and DEX reqs).

**Comment by julealgon** [comment]
For reference this is the logic used for the item display:

```c++
	if (str || mag || dex) {
		strcpy(tempstr, "Required:");
		if (str)
			sprintf(tempstr + strlen(tempstr), " %i Str", str);
		if (mag)
			sprintf(tempstr + strlen(tempstr), " %i Mag", mag);
		if (dex)
			sprintf(tempstr + strlen(tempstr), " %i Dex", dex);
		AddPanelString(tempstr, TRUE);
	}
```

This really should be unified :S

**Comment by AJenbo** [comment]
both should look like the second one, its anover sight from me when dealing with the original not working on some compilers
