### ISSUE TITLE
Building DevilutionX with MSYS2

### ISSUE THREAD

**Issue by joankaradimov** [diasurgical/devilutionX#119]
I'm trying to build DevilutionX with MSYS2. This appears to work with [Devilution](https://github.com/diasurgical/devilution/blob/master/docs/INSTALL_windows.md). But I've failed to make it work in DevilutionX.

I've created a `CMake/msys2_mingw.cmake` file that looks like this:

```cmake
cmake_minimum_required(VERSION 3.10)

SET(CROSS_PREFIX "/mingw64" CACHE STRING "crosstool-NG prefix")

SET(CMAKE_SYSTEM_NAME Windows)

# workaround
list(APPEND CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES "${CROSS_PREFIX}/include/SDL2" "${CROSS_PREFIX}/include/sodium")

SET(CMAKE_C_COMPILER   "gcc.exe")
SET(CMAKE_CXX_COMPILER "g++.exe")

SET(CMAKE_FIND_ROOT_PATH  "${CROSS_PREFIX}")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

After that I run:
```bash
pacman -S mingw64/mingw-w64-x86_64-libsodium mingw64/mingw-w64-x86_64-SDL2_ttf mingw64/mingw-w64-x86_64-SDL2_mixer mingw64/mingw-w64-x86_64-SDL2

mkdir build
cd build
cmake -DASAN=OFF -DCMAKE_TOOLCHAIN_FILE=../CMake/msys2_mingw.cmake ..
```

... and it works. The toolchain and the dependencies are detected correctly. However trying to `make` results in an error:

```
D:/dev/work/devilutionX/types.h:51:10: fatal error: miniwin/pushdecl.inc: No such file or directory
 #include "miniwin/pushdecl.inc"
```

Can anyone help with this? My confusion comes mostly from the `SourceS`/`SourceX` directories. Should one of those be used in a build of DevilutionX or both?

**Comment by AJenbo** [comment]
Both SourceS/SourceX, they are what distinguish DevilutionX form Devilution, i.e. this is where all the OS abstraction and reimplemented UI lives.

Since you are running `pacman` I assume that you are on Arch? First of all is there any reason why you are trying to build a Windows version rather than a native Linux version? Secondly is there something that makes the recommended Mingw method mentioned in the readme not work for you?

**Comment by joankaradimov** [comment]
> Both SourceS/SourceX are required

Ok, so I assumed wrong initially.

> Since you are running pacman I assume that you are on Arch?

No, that's MSYS2. It uses pacman for package management. But it uses its own repository with msys/mingw32/mingw64 binaries instead of the ones for Arch Linux. And it's handy. It has packages for all DevilutionX dependencies.

> First of all is there any reason why you are trying to build a Windows version rather than a native Linux version? Secondly is there something that makes the recommended Mingw method mentioned in the readme not work for you?

There's no cross compilation going on here. It's all Windows.

**Comment by AJenbo** [comment]
> As far as I can tell the readme and the build scripts assume cross compilaiton. And there's no cross compilation going on here. It's all Windows.

That's correct, the "Windows via Visual Studio" is however for natively building on Windows, we automatically test it using the free 2017 version of Visual Studio and the script found here:
https://github.com/diasurgical/devilutionX/blob/master/appveyor.yml
It uses `vcpkg` for installing the dependencies.

Hope that helps.

**Comment by joankaradimov** [comment]
Ok, this does not look like a use case that makes much sense. I was thinking of making the build process easier and MSYS is not the thing.

Thanks!

**Comment by sskras** [comment]
Well, if Devilution for Windows can be built using Msys2, then DevilutionX could be too, IMO.

But then I haven't built the Devilution at all / ever, so my opinion might be too light.

**Comment by AJenbo** [comment]
The build set ups is barley related, DevilutionX muses CMake and has external dependencies, Devilution only has a make file but is rather system specific.

**Comment by tmose1106** [comment]
Hi, I too wanted to build using MSYS2. I spent a considerable chunk of my day working on this and was able to find a solution.

For this I used almost the OP's CMake file save for changing `/mingw64` to `/mingw32` since I was going for a 32 bit build. Running as the OP suggested produced the same results as they stated.

I was able to debug the error further by running the following to configure the Makefile to output the commands being run without extra CMake information using [this StackOverflow question](https://stackoverflow.com/questions/2670121/using-cmake-with-gnu-make-how-can-i-see-the-exact-commands):

```
cmake -DCMAKE_TOOLCHAIN_FILE=../CMake/msys2_mingw.cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_RULE_MESSAGES:BOOL=OFF ..
make
```

Below is an excerpt of the make output I received:

```
make -f CMakeFiles/devilution.dir/build.make CMakeFiles/devilution.dir/build
make[2]: Entering directory '/c/Users/tmose/Documents/Sources/devilutionX/build'
/mingw32/bin/g++.exe  -DDEVILUTION_ENGINE -DDEVILUTION_STUB -DFASTER -D_DEBUG @CMakeFiles/devilution.dir/includes_CXX.rsp -g   -gstabs -fno-omit-frame-pointer -Wno-unknown-pragmas -fpermissive -Wno-write-strings -Wno-multichar -w -fno-strict-aliasing -fsigned-char -fno-aggressive-loop-optimizations -std=c++14 -o CMakeFiles/devilution.dir/Source/appfat.cpp.obj -c /c/Users/tmose/Documents/Sources/devilutionX/Source/appfat.cpp
In file included from C:/Users/tmose/Documents/Sources/devilutionX/Source/diablo.h:5,
                 from C:/Users/tmose/Documents/Sources/devilutionX/Source/appfat.cpp:1:
C:/Users/tmose/Documents/Sources/devilutionX/types.h:51:10: fatal error: miniwin/pushdecl.inc: No such file or directory
   51 | #include "miniwin/pushdecl.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Here you will notice that the includes (which are causing the error) are not being passed directly. Rather, they were recorded inside of this "response" file as CMake calls it which is the path with the `@` before it. So I decided to turn these response files off. I was able to do so by adding these (seemingly undocumented) lines to the CMakeLists.txt file:

```
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES 0)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_LIBRARIES 0)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS 0)
```

This configured the makefile so that the includes were all given inline. Then the program was able to compile. So in the end, these response files are used on Windows CMake builds, but when used in UNIX makefiles I believe they do not act accordingly and lead to errors like these. 

As to how we would like to go about supporting this build method inside of the Makefile should be decided. I was not able to include the above lines inside of the OP's CMake script for some reason. So perhaps an if statement needs to be added inside the CMake file specifically for MSYS2 builds?

**Comment by AJenbo** [comment]
Nice work so far, I'll reopen the issue since there appears to be interest in supporting msys2.

**Comment by MBeijer** [comment]
Just f.y.i, I'm building with mingw32 and mingw64 without issues on my Jenkins build machines (Debian GNU/Linux) with docker images. 
```
mkdir build
cd build
cmake -G"Unix Makefiles" ..
cmake --build . --config Release -- -j 8"
```
However, the guy I'm working on the Big Endian port with had to use **-G"MSYS Makefiles"** when using mingw/msys on his Windows system.

**Comment by arczi84** [comment]
Exacly, MSYS2 is my main toolchain for devilutionX.

**Comment by AJenbo** [comment]
So can this be closed or did you have to modify the generated build setup?

**Comment by arczi84** [comment]
Yes, like MBeijer said -G"MSYS Makefiles" did work for me.

**Comment by J1Man** [comment]
Hi everybody,

I tried compiling DevilutionX using MSYS2 based on the instructions on this thread, but unfortunately nothing seems to work.  I am not a MSYS2 expert, but in the past I was able to compile some projects using MSYS2 by looking at the build instructions.  Unfortunately there are no official MSYS2 build instructions for this project.  I am hoping that we can create step-by-step MSYS2 instructions in this thread, refine them and add them to the wiki.


This is what I did so far:

I started with a clean install Windows 10 Pro 64bit OS virtual machine.
I installed MSYS2 by running the installer from msys2.org. Links are listed below.
https://www.msys2.org/
https://github.com/msys2/msys2-installer/releases/download/2023-05-26/msys2-x86_64-20230526.exe

I opened the MSYS2 shell and ran the following command.
pacman -Syu
exit

After that I opened the MSYS2 shell again and ran the same command again
pacman -Syu
exit

At this stage MSYS2 default installation was fully updated.

I opened the MSYS2 shell again and ran the following command to install the prerequisite packages required to compile devilutionX. I got the package names from the previous posts on this thread and from the internet.

pacman -S git mingw-w64-x86_64-cmake mingw-w64-x86_64-libsodium mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image
exit

After that I opened "MSYS2 MINGW64" shell and ran the following commands to build the 64bit devilutionx.  

git clone https://github.com/diasurgical/devilutionX.git
cd devilutionX
mkdir build
cd build
cmake -G"MSYS Makefiles" ..

And it does not work at all.  I couldn't even generate the makefiles.

I looked at lots of tutorials online and kept installing lots and lots of packages, but I could not build the project.

@arczi84, it seems like you succeeded to compile devilutionX on MSYS2.  I would appreciate if you can share the full list of commands that you use on a clean install MSYS2 system to install all the prerequisite packages and to build the project.

Not just arczi84, I would appreciate if anybody can help me. Thanks.

**Comment by AJenbo** [comment]
Sure but why not just use one of the two (three?) other supported ways to build on windows?

**Comment by AJenbo** [comment]
mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-SDL2_mixer are no longer needed. Better check the mingw instructions for which packages are needed.

**Comment by AJenbo** [comment]
> And it does not work at all. I couldn't even generate the makefiles.

What error did you get?

**Comment by StephenCWills** [comment]
Some general wisdom from my efforts to build for 3DS using MSYS2: https://github.com/diasurgical/devilutionX/issues/1865#issuecomment-832391533

I'm not sure how applicable this would be to compiling for Windows.

**Comment by J1Man** [comment]
Hi AJenbo and StephenCWills,

I will start by answering AJenbo's questions.  I used MSYS2 to compile other open source projects in the past and it really makes things very easy (when it works).  I don't have experience with WSL.  My cpu does not allow nested virtualization.  As a result, I am not able to use WSL in a windows 10 virtual machine.

arczi84 and MBeijer stated in their posts that MSYS2 works for them.  They also made it look very easy to compile this project under MSYS2. :))  You know the saying "hindsight is 20/20".  Now I know that I shouldn't even have attempted it. LOL.

Initially I couldn't even generate the make files.  I first got an error saying that "MSYS Makefiles" are not supported.  After installing some packages, I got a bunch of compiler flag missing errors while attempting to generate the make files.  Later I figured out that a compiler was not included in the base MSYS2 installation. LOL.

Anyway, I believe that something good might come out of my effort, in terms of code compliance with multiple build environments.  The good news is I miraculously got devilutionX to compile up to 83%.  The bad news is compiler gave an error in code and exited.
Compiler gave errors while compiling dvlnet/protocol_zt.cpp, dvlnet/zerotier_native.cpp, dvlnet/zerotier_lwip.cpp.
The error was: mingw64/include/_timeval.h:10:8: error redefinition of 'struct timeval'
There were also tons of warnings.
I am not a programmer, so it is impossible for me to debug anything.

I wrote down the updated step-by step instructions to compile this project under MSYS2 below.  The trick I used is to first compile another open source project which has an automatic build script for MSYS2. That script downloads the compiler and sets all compiler flags accurately.  That's how I was able to set things up even though I don't know much about MSYS2.

Without further ado, the updated instructions are the following:


Start with a clean install Windows 10 Pro 64bit OS virtual machine.

Go ahead and install MSYS2 and build Wimlib project per the instructions shown on the link below
https://github.com/ebiggers/wimlib/blob/master/README.WINDOWS.md#building-from-source
Please make sure to use "MSYS2 MINGW64" shell for building wimlib.
Please note that we are building wimlib because it has an excellent build script that sets things up accurately under MSYS2.
Exit the "MSYS2 MINGW64" shell after the wimlib compilation is over.

Open MSYS2 shell and enter the following commands:

pacman -S git cmake mingw-w64-x86_64-gtest mingw-w64-x86_64-cmake mingw-w64-x86_64-libsodium mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image
git clone https://github.com/diasurgical/devilutionX.git
exit

Open "MSYS2 MINGW64" shell and type the following to generate the make files and start compiling:

cd devilutionX
mkdir build
cd build
cmake -G"MSYS Makefiles" ..
cmake --build . --config Release -- -j 8

It will build fine until 83%.  There will be lots of warnings but no errors until 83%.  After that, it will give the errors that I mentioned above and exit the compilation process.


Let me know if you can replicate the errors that I am getting. Errors might be things that you guys can easily fix by changing the code.

Since I already did most of the trial and error with MSY2, it might now be relatively easier for you guys to make the project fully compliant with the MSYS2 build environment.

**Comment by AJenbo** [comment]
You still do not need `mingw-w64-x86_64-SDL2_ttf ` or `mingw-w64-x86_64-SDL2_mixer `

https://stackoverflow.com/questions/58067077/simple-fltk-application-not-cross-compiling-with-mingw

**Comment by J1Man** [comment]
> You still do not need `mingw-w64-x86_64-SDL2_ttf ` or `mingw-w64-x86_64-SDL2_mixer `
> 
> https://stackoverflow.com/questions/58067077/simple-fltk-application-not-cross-compiling-with-mingw

I had them installed during my first attempt.  You mentioned that they were redundant, but  I still forgot to remove them from my commands in my second attempt.  :))  Most probably, the compiler errors are not caused by redundant packages, right?

I can revise the step-by-step instructions and remove all redundant packages after somebody figures out how to successfully compile this thing under MSYS2.  Additional things that I couldn't figure out might also have to be added to the instructions.

**Comment by AJenbo** [comment]
> Most probably, the compiler errors are not caused by redundant packages, right?

Moste likely it's caused by the cause stated in the stackoverflow post I linked.
