### ISSUE TITLE
[Enhancement proposal] Configurable quests for single player and network game

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1213]
It would mean for a network game to make possible to activate single player quests in diablo.ini as following.
Poisoned Water Supply, Gharbad the Weak, The Magic Rock, Arkaine's Valor, The Chamber of Bone, Halls of the Blind,
Zhar the Mad, Black Mushroom, Anvil of Fury, Warlord of Blood, Lachdanan, The Jersey's Jersey, Little Girl

It would mean for single and network game as following options:
1. The Butcher - reward is a random item or "The Butcher's Cleaver"
2. a) The Curse of King Leoric - King's place configurable for both game types in diablo.ini
b) reward is a random item or "The Undead Crown"
3. Archbishop Lazarus - Archbishop's place configurable for both game types in diablo.ini

**Comment by julealgon** [comment]
We'll make quests fully configurable at some point, by softcoding their settings and allowing one to define "quest groups" with arbitrary spawn rates (which will allow you to create identical behavior to vanilla, but at the same time allowing full customizability).

The idea is to also softcode items, which will them allow you to link both: i.e. declaratively assign item drops to monsters. With that, one should be able to customize drops for special monsters also, like Butcher and Leoric.

Lastly, I had an idea that should be feasible, which would allow the host to define the "game parameters" and broadcast the settings to other players, so that no matter the settings one has configured locally, when joining other's games, the host's settings will "override" the local settings and modified games can be shared this way without requiring all parties to have the same "mod setup".

It is highly likely that such advanced softcodes will not be .ini flags, but deeply nested .json config files, however.

This will take a while though as there is significant refactoring that needs to be done first.

**Comment by AJenbo** [comment]
most quest are borken in multiplayer and will need to be fixed first.
