### ISSUE TITLE
Broken hall of the blind

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1320]
![screen00](https://user-images.githubusercontent.com/45902449/113360010-3cfc5e80-9349-11eb-9643-b3e5fc101952.png)
![screen01](https://user-images.githubusercontent.com/45902449/113360017-41c11280-9349-11eb-9899-7282b99a6076.png)
[hall.zip](https://github.com/diasurgical/devilutionX/files/6246738/hall.zip)

**Comment by AJenbo** [comment]
What does "completely broken" mean?

**Comment by Chance4us** [comment]
> What does "completely broken" mean? From what I can see the door frame is missing.

The description wasn't that good, I've already managed to do that better several times
. 
By the way, the holes don't look that bad in vanilla, only the doors are missing. 
![screen01](https://user-images.githubusercontent.com/45902449/113360619-6b2e6e00-934a-11eb-87f3-567892568696.png)

**Comment by galaxyhaxz** [comment]
If it's just doors that are missing, then that's a known bug, from Vanilla too. We documented it i think in 2019

**Comment by Chance4us** [comment]
Looks a little different this time in vanilla.

**Comment by AJenbo** [comment]
Vanilla has a bug where it will render the doorframe twice... we have fixed that, but with no doors both doorframes are now missing :cry:

**Comment by AJenbo** [comment]
@galaxyhaxz not only that by @Chance4us was the one that reported it :D

**Comment by galaxyhaxz** [comment]
I can't seem to find the original thread, do you have a link? I wasn't sure who posted it, but I never had the chance to look into it and find the fix. Can't find it anywhere.

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/issues/113

**Comment by Chance4us** [comment]
It's obviously an another seed which has also missing doors. LOL ;-)

**Comment by AJenbo** [comment]
So both this and #113 were caused by the level running out of objects (127 max) and so was unable to spawn the doors. We have now fixed this by making sure the doors spawn at the start like all other doors. Not that it is not feasible to fix existing savegames and because we have fixed the double rendering of the door frame this looks a bit worse in DevilutionX than in vanilla. But all new games will be unaffected and will even work correctly if transferred back to Diablo.
