### ISSUE TITLE
Some Quest Items Can Be Behave Bizarrely in Multiplayer with Multiple Players

### ISSUE THREAD

**Issue by BartyMae** [diasurgical/devilutionX#1437]
**Important information**
Windows 10 LTSC 2019 x64, DevilutionX (v1.2.0-5F5DCIAF) with Hellfire, self-compiled, multiplayer.

**Description**
While playing with a friend, we noticed that quest items can be destroyed by the game if you pick them up with the wrong player, seemingly mostly tied to who is the host. For example, having a non-host player talk to the Farmer to spawn the Auric Amulet will drop the Auric Amulet on the ground, and if the non-host player (who does not already have an Auric Amulet) attempts to pick it up, nothing will happen for a few moments, and then suddenly the Auric Amulet will disappear from the game entirely. This is not limited to simply the Auric Amulet - for example, the Rune Bomb, Cathedral Map, and Torn Notes seemed to have the same problem.

**Expected behavior**
Ideally, all players should be able to pick these quest items up and use them.

**Comment by AJenbo** [comment]
These are original hellfire issue, hellfire was never really meant for multiplayer. The issues will be addressed eventually and are fairly high on the priority list as they are pretty annoying.

**Comment by AJenbo** [comment]
Also affects Theodor

**Comment by Myrddin-Wyllt** [comment]
I haven't played on my desktop in some time, but at least on Android; this occurs occasionally with random items. I was trying to figure a common trigger, it seems to happen more often when enemies are on screen and you've just traveled to an area. I had at least 4 items disappear in 30 minutes. It might have something to do with autopickup of gold; I'll try disabling and report back if that seems to fix this. Before this glitch happens, the pickup button seems to have no effect (i.e., the character doesn't even move towards the item) and after a moment the item just vanishes, no pickup sound effect.

**Comment by ephphatha** [comment]
This is a fun one. In current master quest items are only spawned for the player who triggered the change in quest state. The other players don't see the item appear but they all receive a message that the quest has advanced, so they can't trigger a copy to spawn on their end.

Using the Rune Bomb as an example the following sequence happens:
1. The host creates the game and spawns in town as player 0, claiming level 0 (for the purpose of deciding which player controls game state)
2. Player 1 joins the game and recognises that player 0 is currently on level 0
3. Player 1 talks to the farmer, spawns the rune bomb (for them only) and advances the quest state for both players
4. Player 1 attempts to pick up the rune bomb. The game recognised that player 0 controls level 0 so it sends a message saying "Player 1 is attempting to pick up the rune bomb"
5. Player 0 receives this message, looks through the list of dropped items, doesn't find the rune bomb, and discards the message
6. A few seconds later player 1s game looks through the list of actions, sees an attempt was made to pick up an item that never completed, and runs a check to see if it failed to process a dropped item from another player. Nothing shows up so it deletes the item corresponding to that message, causing the rune bomb to disappear. (bit fuzzy on the actual trigger here)

This only blocks the pickup attempt if the host is on the same level as the quest item drops when the non-host player joins. If the host is in the dungeon for example a second player can join, spawn the rune bomb, and pick it up successfully.

**Comment by ephphatha** [comment]
...And all the code that handles placing an item on the ground in response to a "this item was placed on the ground" network message assume it's because a player dropped it. When monsters are killed they send a message to all connected players announcing the monster death, then each player spawns loot locally and sends messages out with whatever loot was created. This second round of messages is ignored by players currently on the level, it only gets used by players who join the game or travel to the level after the event.

I was hoping to use the same logic to sync quest item drops but it has the same issue. Players on the same level when one spawns the item don't see it drop, players joining the game later or travelling to the level after the drop will see it on the ground.

**Comment by AJenbo** [comment]
Could this result in issue where loot items are not possible to pick up, ore the pick up is not synced, because the item landed on two different tiles?

**Comment by ephphatha** [comment]
DROPITEM commands are a bit special, the triggering player will set the location of the dropped item, then the master player for the level will replicate that position to all players (and record it in the level delta), it doesn't matter if there's been a desync on the monster that drops theodore for example. Then when picking up an item the fallback check to look for an item by seed and type will still run if the pickup position turns out to be invalid, though this should really never happen for these types of dropped items.
