### ISSUE TITLE
Nintendo Switch port

### ISSUE THREAD

**Issue by sskras** [diasurgical/devilutionX#151]
Recent [**Modern Vintage Gamer** video](https://www.youtube.com/watch?v=5tADL_fmsHQ) tells about him (MVG) porting devilutionX to the Nintendo Swtich: https://github.com/lantus/devilution-nx

Maybe it's a good idea to synchronise the repos and port the patches back : )

**Comment by AJenbo** [comment]
MVG did a hard fork with no history or pointer back to this repo, this complicates the process a bit. But also he has said that that he want to clean it up a bit first as well as solve some issues like video not playing properly on Switch, before working on upstraming the changes. As he also mentions the biggest change is adding the controller scheme, and writing a build script. The controller scheme at the moment is a bit invasive so needs some cleaning and the build script is written in raw make so I'm hopping this can be adapted to Cmake so that it won't need to be separately maintained.

We are keeping an eye on the repo and collaborating on any changes and fixes for now.

**Comment by erfg12** [comment]
Might wait for MVG's port to be ready instead of my joystick implementations since he already has OpenGL joystick support. But I don't really like his button setup, I think mine was better as it reflected the PS1 control scheme more.

**Comment by AJenbo** [comment]
@erfg12 ok I was hoping you would reference MVG's code to do a clean port of your controller code since it more closely matches the original PSX mapping.

**Comment by AJenbo** [comment]
This has now been done thanks to the help of @rsn8887 and @glebm
