### ISSUE TITLE
Provide an AppImage for linux

### ISSUE THREAD

**Issue by azubieta** [diasurgical/devilutionX#167]
AppImage is a great and portable packaging format for GNU/Linux. It would be great to have this great game available in that format. 
For more information you can look at:

https://appimage.org/
https://docs.appimage.org/packaging-guide/index.html

We would love to assist you at #appimage on freenode IRC

**Comment by AJenbo** [comment]
AppImage would be nice, would you be able to send a PR with the need changes that would need to be done for CircleCi? Or list what needs to be changes for it to woke?

**Comment by thimslugga** [comment]
I've actually been building my own DevilutionX.AppImage since coming across this project last year. Right now I'm including the diabdat.mpq in my appimage. Is there an alternative that could be used as I wasn't sure if it's okay to share this file.

I'm not familiar with CircleCi so I'll have to look into how to use it for automating the build.

**Comment by AJenbo** [comment]
The mpq can't be part of the appimage for some what ovious reasons. People need to provide that them selfs from there legitamate copy of the full game, or the shareware.

You aren't required to make this work via CircleCi, but CircleCi is basically just a simple shell script runner, so not much magic to figure out there.

Preferably this could be done using CMake + CPack, but it looks like they haven't build a generator for AppImage yet: https://github.com/AppImage/AppImageKit/issues/160

**Comment by StephenCWills** [comment]
Given that we have an AppImage among the releases, and it's being built by CI, it seems this issue is resolved.
