### ISSUE TITLE
Chest trap in catacombs hitting multiple times depending on what direction it's opened from (elemental bug?)

### ISSUE THREAD

**Issue by Taohn** [diasurgical/devilutionX#1672]
**Important information**
Windows 10 Pro 64 / DevilutionX version 1.2.1 /  downloaded release

**Describe**
It's a small chest with a fire arrow trap (the one that launches from the chest itself rather than the wall). Normally it deals 10-15 damage or so with a single projectile, but around half the time the character will be hit multiple times in quick succession (several of which are blocked), dying almost instantly. It can happen from any direction but seems to do so most often from the position in the attached save.  I've had the same thing happen with nova traps ([single_1.zip](https://github.com/diasurgical/devilutionX/files/6368993/single_1.zip)), but that at least makes some kind of sense since the projectiles could be overlapping. 

Similar problem referenced [here ](https://www.lurkerlounge.com/forums/thread-12422.html) under "FIRE/LIGHTNING SUFFIX ISSUES" 

**To Reproduce**

1. Load save [single_1.zip](https://github.com/diasurgical/devilutionX/files/6368986/single_1.zip) 
2. Click on nearby chest (reload if death doesn't occur; it will within a few tries at most)

**Expected behavior**
For character to be hit once rather than multiple times.

**Comment by qndel** [comment]
Thanks!

**Comment by Taohn** [comment]
Forgot to add, this is Hellfire.

**Comment by qndel** [comment]
Found a small issue with your save :D was wondering why the instakill was seemingly random, turns out there are hiddens on the level and they are always active = call rng for movement, that's why you don't always get killed by that chest (And I was starting to think devilutionx's rng broke :D )

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/115955912-de667280-a4f9-11eb-87bf-2af586e09f0f.png)
[single_31.zip](https://github.com/diasurgical/devilutionX/files/6369415/single_31.zip)
This save always gets the instakill (I killed all monsters on the level)
I marked spots where character gets instakilled on the picture, maybe it's related to arrow hitting a wall and exploding and character being caught in the explosion multiple times?

**Comment by qndel** [comment]
@StephenCWills actually I got a wild theory https://github.com/diasurgical/devilutionX/pull/1641
The instakill only happens in this situation:
1. you block the missile
2. you are standing next to a wall/something blocking.

So you block and deflect the missile, it flies further, hits the wall, you are still recovering from the hit = can't block again, get hit repeatedly from the explosion = dead.

If that's the case, your PR should fix this as well!

**Comment by qndel** [comment]
Yup! I'm right : )

**Comment by Taohn** [comment]
Fascinating, but if you don't mind me asking what do active hiddens have to do with opening chest? Also, why would the explosion hit more than once?

**Comment by qndel** [comment]
They advance the rng = you open the chest and get different results depending on the time you opened it at

**Comment by qndel** [comment]
Okay seems it's more complex than that, you can get it to happen without blocking and in vanilla too 
![instakill](https://user-images.githubusercontent.com/14297035/115958029-ec21f500-a505-11eb-888e-ebeb441e318c.gif)

**Comment by StephenCWills** [comment]
It looks like this type of arrow was designed to hit multiple times. Perhaps the damage is just too high?
https://github.com/diasurgical/devilutionX/blob/b1ee8c00b33aca4a92a4388ff5116cb4f6143941/Source/missiles.cpp#L3349

Actually, since it's generating two random numbers, wouldn't it be possible for min damage to be greater than max damage?

**Comment by qndel** [comment]
yeah seems it's possible 😆 as for getting hit multiple times, the problem is that sometimes you will hit once which is fine, but sometimes like 10 times which is an instant kill, if you lowered the damage, then it'd suck in general :(

**Comment by StephenCWills** [comment]
Right, and the damage is based on the dlvl. On dlvl 7, the absolute minimum damage is 8, and you take damage up to 10 times. A sorcerer with 70 life just can't survive 10 consecutive hits.

**Comment by StephenCWills** [comment]
I guess if I were reviewing this for player damage instead of trap damage, I would say that the target should not get hit multiple times from the elemental damage. That's because the min and max damage for a player's projectiles is determined from the player's gear. Plus, it's difficult to balance a mechanic that can do up to 10x its base damage depending on a bunch of RNG.

Also, FYI, melee weapons have the same behavior.
https://github.com/diasurgical/devilutionX/blob/b1ee8c00b33aca4a92a4388ff5116cb4f6143941/Source/missiles.cpp#L2298
https://github.com/diasurgical/devilutionX/blob/b1ee8c00b33aca4a92a4388ff5116cb4f6143941/Source/missiles.cpp#L4563

**Comment by StephenCWills** [comment]
I double-checked my info with Jarulf's Guide. Melee weapon elemental damage only hits once. This appears to be because `MI_Weapexp()` honors the collision logic and lets the missile die upon collision. `MI_LArrow()` uses the `nodel` flag to allow the missile to linger after collision, causing it to deal damage multiple times. These should probably be made to work the same way.

**Comment by FitzRoyX** [comment]
Loaded the save many times with latest master and can confirm that player no longer gets instakilled by elemental arrow. PR 3863 by StephenCWills fixed this.

**Comment by StephenCWills** [comment]
That PR is from @kphoenix137. I'm just the one who mentioned this issue in there.
