### ISSUE TITLE
Shrines need to effect stats & equipment randomly from the start of a game.

### ISSUE THREAD

**Issue by DrGonzo564** [diasurgical/devilutionX#1874]
**Important information**
Mac OS 10.15.7 / DevilutionX 1.2.1 / Downloaded Release

**Describe**
Due to a design flaw in how the game engine handles the random effects in shrines, Hidden Shrines will tend to reduce the durability of the item in the right slot (left hand) more often. Mysterious Shrines will tend to raise Dexterity more often than other stats. Enchanted shrines will tend to reduce Chain Lightning more often than the other spells. This effect becomes less noticeable the more you play in a single gaming session, i.e. the shrine effects will become more 'random.' Namely, the "random seed" stored with ANY shrine is not initialized properly, and the shrine uses whatever happens to be in that memory location. At startup this memory will mostly be "empty", which is read as zero, which then causes the non-random behavior. After the game is played for a while, the memory is much less likely to be zero, and therefore tends to approach randomness.
(I copy/pasted this from https://www.lurkerlounge.com/forums/thread-12422.html)

**Expected behaviour**
They should be randomized from the start of a new game.

**Additional context**
Example my Warrior is lvl 40 and my spells are all high level 9-15 but CL is lvl 4 and my left hand shield only has 10 durability due to this bug.

**Comment by AJenbo** [comment]
To Reproduce and Screenshots sections are misleading, please fill them out or remove them

**Comment by julealgon** [comment]
I actually thought the vanilla behavior was because "the random number generator was bad" (@qndel ) but this points to something else entirely. Seems like a very sensible thing to fix.

**Comment by qndel** [comment]
This is caused by "the random number generator is bad"

**Comment by AJenbo** [comment]
The guide is somewhere between wrong and misleading on this point:
https://github.com/diasurgical/devilutionX/blob/master/Source/objects.cpp#L3432

**Comment by julealgon** [comment]
Thanks for clarifying @qndel / @AJenbo .

**Comment by qndel** [comment]
Turns out the cause is different
Found by @mewmew 
lshrine and rshrine will use whatever seed value is present in that object, which may be a garbage value from a previous object present in the same memory location
if the object at that object index was a door, a candle or some other object that didn't need a seed, then the shrine object at the next dlvl would also have a zero seed = that's what is causing the bias

**Comment by StephenCWills** [comment]
It might be worth noting that DevilutionX actually matches the Hellfire logic of memsetting the whole array of objects between dungeon levels instead of nitpicking which fields should be cleared. So it does not, in fact, use the seed from the previous object in memory. Instead, the seed will always be zero, completely eliminating the random element of these shrines.

https://github.com/diasurgical/devilutionX/blob/28d7c960638930799b2d6e5c410970cb338b7687/Source/objects.cpp#L397-L399

To compare behavior between vanilla Diablo and Hellfire, see:
https://github.com/diasurgical/devilution/blob/b86b8fd7c4966385e3a7dbcb29e6d7e05bdab95e/Source/objects.cpp#L394-L414
