### ISSUE TITLE
Dialogues and menu sounds played with lower volume compared to 1.2.1

### ISSUE THREAD

**Issue by M0Rf30** [diasurgical/devilutionX#1919]
**Important information**
 Arch Linux / DevilutionX dfece830ad4ba0628a147accf951c521d837c827 / Compiled by myself (devilutionx-git package)

**Describe**
When in town dialogues are not played, also menu sounds (related to click/choice feedback) are not played

**Additional context**
I also tried to downgrade SDL_audiolib to the previous commit, but nothing.
It's not present in stable 1.2.1 tag
I attach some (I hope) useful logs
[execution-debug.log](https://github.com/diasurgical/devilutionX/files/6448078/debug.log)

[cmake.log](https://github.com/diasurgical/devilutionX/files/6448101/cmake.log)

**Comment by AJenbo** [comment]
What volume do you have ingame? Does the heros say there line on first entry to the dungeon?

**Comment by AJenbo** [comment]
By "enabled" are you refering to `0` (scale goes from -1600 to 0)?

I'm unable to replicate this :/

**Comment by M0Rf30** [comment]
Ok I'll reformulate on the base of more details
To replicate try to do this. 
```
Sound Volume=-1000
Music Volume=0
```
Now switch between latest commit and 1.2.1 tag.
You'll notice, for the same settings, a recognizable difference in volume.
And this explain my mistake. At a first glance (no headphones) I thought about some issue about missing sounds. Indeed are still there but with a totally different gain

**Comment by AJenbo** [comment]
yeah the volume scaling has been reformulated to give more control, is it giving any issues besides having to change the volume slider?

**Comment by julealgon** [comment]
@AJenbo this kind of issue has been happening quite consistently: people opening issues related to things that have changed on purpose for the next release.

Have you considered keeping track of new features in an incremental fashion in the Wiki/readme, so that people are aware of what features/changes are coming and can react accordingly?

Perhaps it would be best to have the feature PRs themselves update the "upcoming features" section and then only convert this section into the actual release notes later (or something like that).

Something else we could do, is we could perhaps add some information to the bug template, something like `"please check the new features and bug fixes <on this link>(link to next milestone) before opening a bug since your issue might have been fixed already"`.

**Comment by AJenbo** [comment]
Ideally I would like to follow the guidelines from Keep-a-Changelog: https://github.com/diasurgical/devilutionX/blob/master/docs/CHANGELOG.md#changelog But I haven't really had the time to manage it.
