### ISSUE TITLE
Character rotates towards cursor when casting skils

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2061]
![dancerepair](https://user-images.githubusercontent.com/14297035/119547935-fc8fee80-bd95-11eb-9326-f942bac2681e.gif)

Doesn't happen in vanilla

**Comment by StephenCWills** [comment]
I suspect this was introduced by #2025. Do we really consider this to be a bug, though? Seems fine to me.

**Comment by qndel** [comment]
looks bad to me 🤷

**Comment by julealgon** [comment]
How does it work when inside the dungeon in vanilla?

**Comment by julealgon** [comment]
I think there are 2 distinct behaviors at play here:
1. Casting in town "uses standing animation" (that it, it actually resets the animation but plays "standing" again)
2. Casting casts in the direction of the cursor

1 seems to have been implemented on purpose (even though I disagree with it), so to me 2 makes sense as a consequence of that. Otherwise, for 2 to not happen, we'd need special casing (which I'm against).

**Comment by FitzRoyX** [comment]
I too thought the cast animations looked better. The player normally doesn't change directions without heavy leg movement, so this ends up looking very abrupt.
