### ISSUE TITLE
Snot spill not behaving correctly

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2081]
As reported by janis on Discord

In a conversation with SNOTSPILL
`SS Talk = 21, Flags = 64`
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6565663/single_0.zip)

**Comment by ThomasChr** [comment]
@AJenbo Could you please elaborate a little what the bug is?

**Comment by StephenCWills** [comment]
I'm completely stumped on this one. The quest's `_qvar1` variable tracks the following states.

* 1 = quest initialized
* 2 = spoken to Snotspill at least once, enabling the use of the chest containing the sign
* 3 = given the sign to either Ogden or Snotspill, triggering hostilities

The error signals an illegal state where the `_qvar1` variable is less than 2 after talking to Snotspill.
https://github.com/diasurgical/devilutionX/blob/85ea90c2c40596b5ab7009afd8885bdd0b8a50f1/Source/monster.cpp#L1757-L1759

In the provided save, the chest is open which suggests that `_qvar1` must have been 2 at some point.
https://github.com/diasurgical/devilutionX/blob/1700c775478e10c8ed85a648a177842b5e373fe1/Source/objects.cpp#L3119

Also in the provided save, the value of `_qvar1` is 1. So its value must have changed after opening the chest. There are two places in the codebase where this quest's `_qvar1` variable gets set to 1: when starting a new game (`InitQuests()`) and when talking to Ogden after visiting dungeon level 3.

The short version is, `InitQuests()` couldn't have been called after the chest was opened or else the quest log would have been reset. However, the `_qactive` variable prevents Ogden from overwriting `_qvar1` state. I couldn't find a way to force this situation in a new game.

Having said all this, I do not understand why speaking to Ogden after visiting dungeon level 3 should ever change `_qvar1`. If `_qactive == QUEST_INIT`, then `_qvar1` should already be 1. This also appears to be true in vanilla as well so this assignment seems entirely unnecessary. Perhaps we should consider removing that code regardless.

---

Here's the long version.

After ruling out `InitQuests()`, I figured the player must have simply deferred talking to Ogden until after having retrieved the sign. However, testing reveals that this doesn't cause the error. Here is how the `_qactive` variable prevents this situation from happening.

When talking to Snotspill:
https://github.com/diasurgical/devilutionX/blob/85ea90c2c40596b5ab7009afd8885bdd0b8a50f1/Source/monster.cpp#L1752-L1754

When talking to Ogden:
https://github.com/diasurgical/devilutionX/blob/85ea90c2c40596b5ab7009afd8885bdd0b8a50f1/Source/towners.cpp#L324-L327

In other words, if you progress the quest by talking to Snotspill, `_qactive` gets changed from `QUEST_INIT` to `QUEST_ACTIVE`. Talking to Ogden only changes `_qvar1` if `_qactive == QUEST_INIT`. Therefore, the only way Ogden could have changed `_qvar1` is if `_qactive` regressed from `QUEST_ACTIVE` to `QUEST_INIT` after having talked to Snotspill.

It turns out, the only time any quest is ever set to `QUEST_INIT` is in `InitQuests()`. This is still just as unlikely because it would have reset the quest log.

**Comment by AJenbo** [comment]
I think this was reported around the time we fixed the bug with monster talk being 0 instead of -1 when they do not have a dialog. So it might be related to that rather then the state of the quest?

**Comment by julealgon** [comment]
> I'm completely stumped on this one.

Can the quest be exploited in any way by taking the tavern sign, not talking to anyone, and then saving and starting a new game where the tavern sign quest is enabled? What happens if you drop/pick-up the sign in a new game without opening the chest?

**Comment by StephenCWills** [comment]
> I think this was reported around the time we fixed the bug with monster talk being 0 instead of -1 when they do not have a dialog. So it might be related to that rather then the state of the quest?

I can't seem to find the fix you're referring to, but maybe 8b8caf5 has something to do with it. In fact, the discussion in #1152 seems particularly relevant. Though, I had been assuming that this player was using 1.2.0 at least given the timeframe of this report.

**Comment by StephenCWills** [comment]
> Can the quest be exploited in any way by taking the tavern sign, not talking to anyone, and then saving and starting a new game where the tavern sign quest is enabled? What happens if you drop/pick-up the sign in a new game without opening the chest?

That does indeed create an unusual situation, but I still can't reproduce the error. Picking up the sign doesn't affect quest state, but you can turn in a sign from a previous game to Ogden before talking to Snotspill. This will trigger the ambush, opening up the room next to Snotspill, but Snotspill himself won't be made hostile. If you talk to Snotspill, the quest will regress to `_qvar1 == 2` allow you to open the chest, and if you go back to town and return, the ambush room will be closed again. However, the quest remains completed at that point so you can't turn it in to Ogden a second time. At that point, your only option is to turn it in to Snotspill.

FYI, in the attached savegame, it appears as though the chest was opened and the quest was never completed, but I couldn't find any trace of the sign. Given the location where the player saved, they had probably just turned in the tavern sign to Ogden and were preparing to fight Snotspill.

**Comment by obligaron** [comment]
I also can't reproduce the issue with current master.
Perhaps we should close this pr as it seems to be fixed by the monster talk change.
