### ISSUE TITLE
Magic rock anomalous alt highlightning flicker

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2108]
The magic rock description flickers at regular intervals.
This is probably because the item is permanently animated.

How it looks like:
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6580137/output.mkv.zip)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6580139/single_0.hsv.zip)

**Comment by AJenbo** [comment]
magic rock is animated, so probably that is why this happens.

**Comment by nickgavran** [comment]
I spoke with qndel about this a few weeks ago, when he was messing around with alt-highlighting. He is aware of the issue, and it does indeed happen because the magic rock is animated.

**Comment by Chance4us** [comment]
If the flickering of the magic rock cannot be resolved or if the effort is too great, it can stay as it is.

**Comment by julealgon** [comment]
> If the flickering of the magic rock cannot be resolved or if the effort is too great, it can stay as it is.

Keep in mind that we want to make sure game systems work consistently regardless of how many occurrences there are in vanilla. Even if the magic rock is the only affected item in the game, it is still important to fix it since we want modders to be able to introduce their own animated items if they want to do so.

This will most surely be fixed.

**Comment by qndel** [comment]
I literally forgot about this :D

**Comment by Chance4us** [comment]
> I literally forgot about this :D

You probably expected that I would find it anyway. I seem somehow particularly talented in finding bugs.
