### ISSUE TITLE
Missing font in InitFont()

### ISSUE THREAD

**Issue by pgielda** [diasurgical/devilutionX#215]
There is a part of UI code that opens "CharisSILB.ttf" using SDL_ttf. This line fails (there is no such file). Apparently with no bad side effects... but maybe I am missing something.
This seems to be the only place where SDL_ttf is used at all.
Is that some leftover or am I missing something?

**Comment by pgielda** [comment]
Ok, after I wrote this I checked in more detail and it seems to be used only in credits. Rest of the game is rendering things using some internal mechanism.
Why is this custom, how was that implemented in the original game?

**Comment by MBeijer** [comment]
It is a free font, just download it.

**Comment by pgielda** [comment]
I know how to download this font (I would consider bundling some font in the repo though as nobody will figure out you have to download it in the first place), my question was more about the reason of SDL_ttf usage - it seems to be used only for this specific font in credits. Or am I mistaken? Was original diablo also using a ttf file there?

**Comment by AJenbo** [comment]
The font is also used for the cancel button during the sync part of joining a multiplayer game. It is also used for a few other parts of the original UI, though non of these are really relevant for DevilutionX (most of them being part of BattleNet)

In the original game it was assumed that Times New Roman Bold was available, but since this is not a safe assumption on non-Windows platforms, and there not being cross platform way of loading a system font, we instead went the route of including a similar font that looks decent when rendered as the size with no anti-aliasing (most fonts today are not tuned for this). The font is included in the releases so probably you just compiled the source with out downloading a release.
