### ISSUE TITLE
zerotier error

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2197]
**Important information**
latest - https://github.com/diasurgical/devilutionX/commit/b478d8295c41de0475d925488016d3e08552b39b

**Describe**
no idea
![image](https://user-images.githubusercontent.com/14297035/122655768-585f5480-d155-11eb-8b3e-d2cb43477a8e.png)

**To Reproduce**
enter zerotier menu
select hero
select create game
select any difficulty
go back
select join game
spam esc till game quits 
ERROR

**Expected behavior**
No error

**Comment by ThomasChr** [comment]
Can't reproduce in c11929e282b1efb6c9e72b6701f2372fe7f2b13e

**Comment by obligaron** [comment]
I still get the error with 63d8e38d
Note: The program shuts down, but ... with internal exceptions 😉

**Comment by ThomasChr** [comment]
Strange. I tried reproducing with Linux. Could you try on Linux?

**Comment by obligaron** [comment]
Currently not.
But I only tested it on windows with msvc.
Perhaps it's only related to one of those two. 🤔

**Comment by ThomasChr** [comment]
Could you upload the Windows Build you're using?
Currently I'm having problems to get the windows build going. Tried for three days now and I'm tired...

**Comment by obligaron** [comment]
Here you go [localbuild.zip](https://github.com/diasurgical/devilutionX/files/6960014/localbuild.zip) 🙂

**Comment by ThomasChr** [comment]
Still can't reproduce. For sure I'm doing something wrong. Do you can make a video?

**Comment by ephphatha** [comment]
Looks like a double-free when the zerotier thread exits. Navigating to Multiplayer > Zerotier then waiting until the debug log shows that the connection is established (`INFO: ZeroTier: ZTS_EVENT_NETWORK_READY_IP6`) is enough to trigger the crash.

tailBlock and tailIndex have the value 0xDDDD which msvc uses for freed memory. Annoyingly this error doesn't occur if you quit the game while zt is still negiotiating the connection. It isn't fixed by calling `zts_free` either.

I think it's something internal to zerotier as devilutionx only calls stop once. Removing the call to zts_stop "fixes" the crash, not sure if that's appropriate use of the library though.

**Comment by qndel** [comment]
I just got it while testing something else so definitely still around

**Comment by StephenCWills** [comment]
> I think it's something internal to zerotier as devilutionx only calls stop once. Removing the call to zts_stop "fixes" the crash, not sure if that's appropriate use of the library though.

It seems that `zts_stop()` is a non-blocking call. In other words, calling `zts_stop()` from an `atexit()` handler essentially guarantees that the `ZTS_EVENT_NETWORK_DOWN` event will lose in a race against static object destruction.

As for appropriate usage of the library...

> At the end of your program or when no more network activity is anticipated, the user application can shut down the service with `zts_stop()`. However, it is safe to leave the service running in the background indefinitely as it doesn't consume much memory or CPU while at idle. `zts_stop()` is a non-blocking call and will itself issue a series of events indicating that various aspects of the ZeroTier service have successfully shut down.
