### ISSUE TITLE
Game runs out of memory

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#23]
![memory](https://user-images.githubusercontent.com/27356954/53522291-55e71580-3ada-11e9-9c91-b067856d9f0e.png)
I played the game for 6 hours straight (got down to the 2nd level of caves) and the game ran out of memory. I attached the error message.

**Comment by AJenbo** [comment]
We do currently have some memory leaks in the engine. Especially things are often not unloaded in some places; like audio handling and video loading. I don't think anyone has tested Devilution for 6 hours continuously so that might be a bit of a feat :smile: Did you happen to check the actual memory usage at the time?

For now, restarting the game every 5 hours should work. Do you remember what specifically was happening at that point in the game (where you enter the level, did you find a new item, etc?

If you want to look into solving some of the issues the debug build does a pretty good job of listing some of the leaks when the games exits, so it should fairly straight forward to start chipping away at.

**Comment by predator8bit** [comment]
I was on level 10, I think actually in combat killing something. The game looked like hitting the 32bit memory usage limit to me, around 3gigs of memory used when this happened.

**Comment by predator8bit** [comment]
Now it just crashed silently, my system monitor says it is still using 2.9gigs of memory.

**Comment by AJenbo** [comment]
@predator8bit please try out the latest release, it should have fixed most of the leaks.
