### ISSUE TITLE
Some monsters seem to move oscillating/vibrating

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2365]
Look how black death moves compared to the dark one to see the difference.
I recorded at 60 fps on purpose and hope you can see the difference.

https://user-images.githubusercontent.com/45902449/125350571-35dce780-e35f-11eb-87ae-2e67033a8c2d.mp4

Savegame (more monsters in the east direction):
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6804183/single_0.hsv.zip)

**Comment by julealgon** [comment]
Seems like some sort of precision issue.

**Comment by Chance4us** [comment]
In the following you can see it much more clearly.

https://user-images.githubusercontent.com/45902449/125357864-7b51e280-e368-11eb-8daa-968a6b3a93a3.mp4

Better savegame:
[black_death_edit.zip](https://github.com/diasurgical/devilutionX/files/6804459/black_death_edit.zip)

**Comment by julealgon** [comment]
Isn't this similar to what someone created for that hellfire abomination monster recently? Seems like it is tied to walking in the main cardinal directions too (the "diagonals" in screen-space). Could be either precision-related, or something silly like incrementing and then decrementing deltas across ticks.

Also @Chance4us , when creating these videos, consider using the in-game zoom feature to showcase it even better.

BTW... I love seeing these smooth movements in the game. Goddamn. Once we get proper dynamic lighting in place, it will look amazing.

**Comment by obligaron** [comment]
@Chance4us reported it [before](https://github.com/diasurgical/devilutionX/pull/2230#issuecomment-870030965).
I looked at it again and added debug squares that are printed at monster rendering location.

This is the current master at game speed 10%

https://user-images.githubusercontent.com/25415264/125364614-194aaa80-e373-11eb-8a29-81282ff81394.mp4




It seams that the squares don't vibrate.
So it still seams that the animation and the position updating don't play that well together.
But we only have these animation frames. :cry:

What we could change is to increase the rendering precision as mentioned in #1987, That would avoid the stuttering in position updating and would leave us only with the animation stuttering. 😅 

Or we could remove the [diagonal special](https://github.com/diasurgical/devilutionX/blob/5d99cb49251fae43e431f5c6b93f726d6bbdf8ae/Source/scrollrt.cpp#L264-L270).
This is the same scene without it:

https://user-images.githubusercontent.com/25415264/125364842-7c3c4180-e373-11eb-8510-a60cf215d34b.mp4

But without this diagonal updates are not steady. And I noticed this with player camera updates. So if we want to change it, someone who is sensitive to this kind of differences should play-test it.

**Comment by Chance4us** [comment]
> But without this diagonal updates are not steady. And I noticed this with player camera updates. So if we want to change it, someone who is sensitive to this kind of differences should play-test it.

I suggest that we all  together do a little play testing to make the right decision.
I would also like to see what it looks like at normal speed in game.

**Comment by Johoely** [comment]
What does it look like at normal speed?

**Comment by Chance4us** [comment]
I would like to add that I noticed that it only happens with monsters that move very slowly.
Would it make sense to repeat some frames more often?

**Comment by NikoVP** [comment]
I think to actively solve that you need subpixel movement, so you can make the trajectory the black death follows a true straight line.

**Comment by julealgon** [comment]
> I think to actively solve that you need subpixel movement, so you can make the trajectory the black death follows a true straight line.

I don't think this is true. Sub-pixel movement would help in smooth transitions from one pixel to the other, but that is not the problem here. The problem is that it is moving back and forth, which shouldn't be the case: it should only transition to "the next pixel" when it moves past halfway to it, and then never come back again to the previous "line".

The problem is that instead of moving "only forward", it is moving forward, then backward, then forward again. Sure, subpixel rendering would "smooth" this a bit, but it is just logically wrong in the first place IMHO.

This seems like another one of those precision problems, like the one automap had.

**Comment by AJenbo** [comment]
@obligaron could you record a video at normal speed with diagonal special removed.

**Comment by obligaron** [comment]
This is the video with diagonal special removed

<details><summary>Video with diagonal special removed (normal speed)</summary>

https://user-images.githubusercontent.com/25415264/126680931-9b8fdfec-e17e-4aa6-8d2e-8b38cbbebe27.mp4

</details>

I also made with fallen and zombie animations videos with [Diablo 1 Graphics Tool](https://github.com/savagesteel/d1-graphics-tool)

<details><summary>Zombie Walk Diablo 1 Graphics Tool</summary>

https://user-images.githubusercontent.com/25415264/126681213-5a37eac7-230d-43e6-a300-c74b07da950f.mp4

</details>

<details><summary>Fallen Walk Diablo 1 Graphics Tool</summary>

https://user-images.githubusercontent.com/25415264/126681224-76d2f0f8-c7aa-4b64-87f6-040a0bf4b717.mp4

</details>

### Issue

It is a precision issue and more like @NikoVP said.

When you look at my example video with the squares, you see that the squares don't move back and forth.
And the squares are the positions where we render the monster (see Diablo 1 Graphics Tool Video).
The squares still don't update smooth. They still jump a little bit.

The reason is that we pass the [position information](https://github.com/diasurgical/devilutionX/blob/d2b2a5a4fc96065bebcac39507866b4cf622a8a9/Source/scrollrt.cpp#L763) to the software rending.
And the software rendering has it's own resolution (the original resolution of diablo). And this resolution can differ from the monitor (and is in most cases lower).

### Long term solution

To make this more exact (a straight line) we could

- increase the software renderer resolution
- change to hardware renderer that uses floating point calculation

The best would be a hardware renderer, cause this would also enables things like pixel lightning.

### Short term solution

To lessen the issue we could 

- check if removing the diagonal special helps a little
- disable ADL-walking-positioning for specific monsters

... or wait for the long term solution 😉

But perhaps I miss something. 🙂

**Comment by AJenbo** [comment]
It looks like removing the diagonal special helps. Would it make sens to only apply diagonal special to the local player?

**Comment by obligaron** [comment]
I would remove it entirely and would see if someone misses it.
it could be not needed, cause no one plays it with 10% game speed as I tested it.
Also less code is better. 😁

**Comment by AJenbo** [comment]
Could you prepare a PR for that then we can test the builds form it.

**Comment by obligaron** [comment]
I opened PR #2446 🙂

**Comment by Chance4us** [comment]
Thanks guys.
I've tried PR and I really like the change and the approach for the solution.

It looks simple and effective.
I could not see any graphic inconsistencies and the issue is gone.

As a short-term solution, it is sufficient until hardware rendering is used.
