### ISSUE TITLE
Installation Trouble

### ISSUE THREAD

**Issue by welt3r** [diasurgical/devilutionX#2370]
I've followed the instructions in the Wiki for Extracting the .MPQs from the GoG installer. When I go to use innoextract however, the output says it could not open the file. Here's the input and output: 

$ innoextract -I DIABDAT.MPQ -I hellfire.mpq -I hfmonk.mpq -I hfmusic.mpq -I hfvoice.mpq 'setup_diablo_1.09_hellfire_v2_(30038).exe' && mv hellfire/h*.mpq ./ && rmdir hellfire

Could not open file "setup_diablo_1.09_hellfire_v2_(30038).exe"
Done with 1 error.

Can anyone help me resolve this? I followed the instructions and even restarted from the beginning, reinstalling everything. For reference, I am running Mac OS 10.14.6.

Apologies if this post doesn't fit the format or isn't appropriate. I'm new to this.

**Comment by ephphatha** [comment]
Those instructions are for extracting the data files from the offline installer, if you've already installed the game using GoG Galaxy or running the installer the MPQs are extracted as part of the install process.

You can find them by opening the install folder:
![2021-07-13T160936_GOG_Galaxy_2 0 37](https://user-images.githubusercontent.com/357684/125400198-f8c33480-e3f4-11eb-9f3b-2995cb8b02a9.png)
DIABDAT.mpq is in the folder that appears and the hellfire MPQs are in ./hellfire (this is on windows, the mac client may be different).

Otherwise the error sounds like the command is not running in the same folder as you've saved the installer. Can you confirm that the file setup_diablo_1.09_hellfire_v2_(30038).exe exists by running `ls setup_diablo*` and confirming it lists at least one file?
