### ISSUE TITLE
Hardware cursor not supported on Raspberry Pi 4, but still enabled

### ISSUE THREAD

**Issue by rayhern** [diasurgical/devilutionX#2445]
When using the joystick on a raspberry pi 4 I cannot see where the mouse pointer is when navigating to boxes in my inventory or increasing character stats. This was working not too long ago, im afraid it may have been removed.

**Describe**
I cannot see where the mouse pointer is on the screen when managing my inventory items or increasing character attribute points after leveling up.

**To Reproduce**
Use a controller when playing devilutionx, and go try to move your gold around. even better move it to the middle of the inventory close your inventory, and try to pick up the gold again. It will be difficult.

**Expected behavior**
See which box the mouse cursor is on so I know which button to press on the joystick when managing inventory or increasing character stats.

**Comment by AJenbo** [comment]
Does it work if you use a mouse?
Does it work if you pick up an armor?

**Comment by rayhern** [comment]
It does not work if I use a mouse. The game responds to clicks from the mouse, but I cannot see the pointer anywhere. I tried with the gamepad and the mouse. I also tried picking stuff up and moving it like armor and no luck.

**Comment by rayhern** [comment]
When I pull the tag 1.2.1 and roll back it allows me to see the cursor with the joystick and with the mouse, so it is definitely something new.

**Comment by AJenbo** [comment]
Ok, it sounds like it does not support hardware cursors. You can try and disable it in the ini file.

**Comment by glebm** [comment]
Is it possible that this is related to the recent regressions in cursor stuff, such as #2448?

**Comment by glebm** [comment]
Do you have something like the `SDL_NOMOUSE` environment variable set?
If not, then it seems like a bug in SDL: we fall back to software cursor if hardware cursor creation fails.
Also, what's your distro?

**Comment by AJenbo** [comment]
Looks like Android might also be affected by this

**Comment by glebm** [comment]
I may be able to have a look at the Android issue some time next week.
Looking at SDL source, this should be supported just fine on Android https://github.com/libsdl-org/SDL/blob/main/src/video/android/SDL_androidmouse.c

**Comment by AJenbo** [comment]
That would be helpful :)

Note that this doesn't apper to be an issue on the emulator, but is on at least the two phones we have tested (Samsung s40 and what @StephenCWills uses)

**Comment by StephenCWills** [comment]
I have the Google Pixel 4.

**Comment by StephenCWills** [comment]
The issue on Android appears to be unrelated. When using the hardware cursor, SDL uses the `PointerIcon` API provided by the Android SDK which responds to native mouse events generated by a hardware mouse. If you plug a mouse into the Android device, you should be able to see the hardware cursor. When not using the hardware cursor, the C++ code draws the mouse cursor in the appropriate location based on SDL mouse events. SDL emulates SDL mouse events when the user interacts with the touch screen so that's why the software cursor moves based on touch input.

I reproduced the issue on Raspbian Buster, which is currently using SDL 2.0.9. I tested by building against the SDL 2.0.14 codebase, and the issue was fixed. So this seems to be an issue with older SDL versions (as @glebm has suggested). Based on the report from #2493, it sounds like this is also a problem on Ubuntu 20.04 which uses SDL 2.0.10. Perhaps the next step is to narrow down to the version that fixes the issue.

**Comment by AJenbo** [comment]
@StephenCWills should we open a new issue for Android?

**Comment by StephenCWills** [comment]
> should we open a new issue for Android?

I think the visibility of the cursor there is really a non-issue. You don't need to see the cursor to know where on the screen you are tapping, and the cursor should be visible when using mouse and keyboard. And a fix would be even more pointless once proper touch controls are implemented.

**Comment by glebm** [comment]
When you control the cursor with the gamepad, it's visible on Android, right?

**Comment by StephenCWills** [comment]
> When you control the cursor with the gamepad, it's visible on Android, right?

Good point. No, it's not. I guess that does make this an issue.

**Comment by AJenbo** [comment]
The cursor is also used to show what item you are moving in your inventory and what stat you are about to increase.
