### ISSUE TITLE
Generate devilutionx.mpq using smpq and have it's files directly in the repo instead

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2488]
https://launchpad.net/smpq

If smpq is not available it should simply skip this part of the build process, or possibly have it as an opt in the way generating language .mo files work atm.

The following command will work in bash:
`find * -type f -exec smpq -M 1 -C PKWARE -c devilutionx.mpq {} +`

This has the huge benefit of correctly generating the listfile internally in the MPQ as well as making things easier to manage.

**Comment by julealgon** [comment]
What are the benefits of even having our own content inside an MPQ again? Wouldn't it be simpler for us to just have the files in the folder directly?

**Comment by StephenCWills** [comment]
Benefits that I have identified:
* Compression
* A single file for (optional) deployment
* The same code is used to access ours and vanilla's resources

**Comment by julealgon** [comment]
> Benefits that I have identified:
> 
> * Compression

Can't you still compress everything when deploying even without having the MPQ container? The MPQ itself doesn't perform any compression, or does it?

> * A single file for (optional) deployment

It is currently not optional though, is it?

> * The same code is used to access ours and vanilla's resources

Don't we already have the native fallback to reading directly from the file system in case the MPQ is not found? I don't think this one is an actual argument in that case.

**Comment by StephenCWills** [comment]
> Can't you still compress everything when deploying even without having the MPQ container? The MPQ itself doesn't perform any compression, or does it?

Of course, there's no reason you couldn't compress the data using another, more widely supported archive format. There's also not necessarily any reason we require compression of assets, but I'd say that it is indisputably a benefit of the format that another strategy may or may not support.

> It is currently not optional though, is it?

I believe it is currently only required if you turn on monster health bars or the experience bar. There are also some assets used for widescreen resolutions, but I don't think they're ever required.

> Don't we already have the native fallback to reading directly from the file system in case the MPQ is not found? I don't think this one is an actual argument in that case.

Yes, the code does check the native filesystem first. However, it only looks for assets on the "base path", whereas the MPQs can be loaded from a handful of supported directories (for example, the `--data-dir` path). Regardless, the function call is the same whether you're loading assets directly from the base path or from one of the MPQs. At the moment, it's best to avoid using any other APIs for loading assets because this one resolves discrepancies around case-sensitivity and path separators.

**Comment by AJenbo** [comment]
MPQ 1.0 (which is all we support) supports the same compression as .zip, switching to standard zip files would be a sensible choice, but someone would need to implement support. Possibly via physfs (by implementing MPQ support for it), and that would give us many of the same benefits in a generic way.

Our MPQ is never strictly required, you can also just provide all the content as loose files.

A benefit of having all our data files in a single archive is that it becomes very easy for end users to check if they have all the right data, as well as overwrite parts of it while easily reverting back to the original files.

**Comment by StephenCWills** [comment]
Closed via #2966
