### ISSUE TITLE
Android: Port over the Java changes from SDL

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#2503]
We're probably missing some of these:
https://github.com/libsdl-org/SDL/commits/main/android-project

**Comment by StephenCWills** [comment]
FYI, we are currently up-to-date with the 2.0.14 release.
https://github.com/libsdl-org/SDL/commits/release-2.0.14/android-project

**Comment by AJenbo** [comment]
Diff with 2.0.14:
android-project/gradle.properties
`org.gradle.jvmargs=-Xmx1536m`
(I didn't think setting it to that made any sens for us)

android-project/app/src/main/AndroidManifest.xml
`        android:theme="@android:style/Theme.NoTitleBar.Fullscreen"`
The theme has an Android 4 styling which looks terrible on modern devices. But this is no longer a problem now that we use a separate "activity" with a separate theme instead of a simple alert box. Reverting this also solves the issue of the app flashing on startup, and not being properly fullscreened on Android 4.3.

**Comment by AJenbo** [comment]
Diff with SDL master:
- "Enable TV game mode by default on Android" causes build error `attribute android:preferMinimalPostProcessing not found`
- "Android: don't need to set the SurfaceHolder format from java code" requires changes to the C code.
- "add SDL_AndroidShowToast for" requires C changes.

The reset can be found in #2504
