### ISSUE TITLE
Show completed quests in the quest log

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#2600]
It can be difficult to remember which quests you've finished on a character you haven't played for a while. It can also be difficult to remember if you've skipped any quests for whatever reason.

One fairly straightforward way of fixing this is to divide vanilla and hellfire into 2 pages. Gray??? = undiscovered while red = finished. Selectable White = active as usual.

![questlog4](https://user-images.githubusercontent.com/57089001/129444077-6b10e9d4-8005-436b-a3d3-da98f0fe8673.png)
![questlog4q](https://user-images.githubusercontent.com/57089001/129442527-caf4173b-a967-44d2-9406-39b49c15701b.png)

**Comment by AJenbo** [comment]
I like the idea. Red might not be the best color for completed quests
I don't think we should show undiscovered quests.

**Comment by FitzRoyX** [comment]
Yeah gold's probably better, but IDC that much. I was also intending for them to be unselectable, but you could also let them be clicked and display a "This quest has been completed" message somewhere instead of the dialog that normally plays.
![questlog8](https://user-images.githubusercontent.com/57089001/129452767-ea938755-287c-4873-9fe7-d8fc30f31216.png)

**Comment by AJenbo** [comment]
I don't think that is nessesery, them not being clickable should be enough, even better if we can make them also not selectable.

**Comment by qndel** [comment]
This looks really good

**Comment by julealgon** [comment]
I like the idea of using gold to mean complete. It would mostly match the intend of other places that also use gold to signal "maximum"/"complete".

Should completed quests appear before uncompleted ones? In other words, should we group quests by completion status? Usually people would care more about pending quests, so to me it would make sense to show the pending ones separately, maybe.

Second question/proposal is in regards to the overall order that they appear. I vote for showing them in "discovery" order instead of canonical order. So if you don't talk to the wounded townsman, then get the anvil of fury quest from griswold, and _then_ talk to the wounded townsman, the anvil quest would be shown prior to the butcher one. I assume that's a change in behavior from vanilla.

I'd also like to bring up the hidden title of the quest log panel here. IIRC @qndel made a change somewhere to show the missing title. Wasn't that hidden due to call order?

We should ideally consider that title when looking into this imho.

**Comment by julealgon** [comment]
I also think we should consider adding scrolling to the quest log panel once the list of quests doesn't fit.

**Comment by FitzRoyX** [comment]
The advantage to displaying them order of attainability is that there are multiple quests per dtype and this gives you an idea of what dlvl a quest is on. So per the example image, I know that Zhar is in the late catacombs if I want to go back and finish it.

**Comment by vladtepesch** [comment]
oh - lol I also implemented a variant: https://github.com/diasurgical/devilutionX/pull/2609
