### ISSUE TITLE
User Interface Panel Buttons does not reflect panel state

### ISSUE THREAD

**Issue by vladtepesch** [diasurgical/devilutionX#2611]
**Important information**
current master

**Describe**
The Panel Buttons for e.g. Quest, Char, Map ... are not changed to their pressed version if the panel is open,

**To Reproduce**
1. run game
2. open a side panel

**Expected behavior**
pressed down version of the Buttons from (`ctrlpan\panel8bu.cel`)  should be shown to reflect the state of the panels

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1601159/129494212-cfe9e810-66cc-413c-9cb5-4d849eb4b12d.png)

**Comment by qndel** [comment]
Actually that's how it works in vanilla, so dunno if you are submitting this as a bug or a feature request

**Comment by AJenbo** [comment]
Letting this stay open a bit longer :)

**Comment by vladtepesch** [comment]
okay then sorry - my memories were wrong about this. currently I have no running original game running

**Comment by AJenbo** [comment]
> okay then sorry - my memories were wrong about this. currently I have no running original game running

I'm in the same situation, digging through YouTube for reference can be time consuming 😅

**Comment by julealgon** [comment]
I really like this suggestion. Would make the UI considerably more intuitive. I think we should reopen it.

**Comment by StephenCWills** [comment]
> I really like this suggestion. Would make the UI considerably more intuitive. I think we should reopen it.

The depressed state of a button provides a visual indicator that the user is interacting with the button, whereas the panel's visibility provides a natural indicator of the panel the user is interacting with. If the depressed state of the button reflects what the visibility of the panel is already telling you, then all we'd be doing is eliminating the feedback that the UI provides for button interaction.

There does seem to be a bit of a disconnect between the keyboard shortcuts and the corresponding mouse interactions. The keyboard shortcuts don't simulate button interactions so there's no visual feedback to link a given keyboard interaction with the corresponding mouse interaction that would trigger the same panel. This is perhaps not a big issue, however, because the keyboard shortcut corresponding to each button can be observed in the info panel by hovering the mouse over the button.

**Comment by AJenbo** [comment]
Currently my plan is to treat the ui like a virtual interface, meaning pressing the inv button with the mose, pressing "I" on the keyboard or "L2" on the gamepad all call the same bit of code. This would mean that the current behavior makes sense since pressing the keyboard isn't triggering the button, rather they both signal the inventory.

**Comment by julealgon** [comment]
> The depressed state of a button provides a visual indicator that the user is interacting with the button, whereas the panel's visibility provides a natural indicator of the panel the user is interacting with. If the depressed state of the button reflects what the visibility of the panel is already telling you, then all we'd be doing is eliminating the feedback that the UI provides for button interaction.

I don't disagree, but I'd then suggest the "open" state should be represented differently compared to the "pressed" state. That would provide redundant feedback, which is desirable especially considering some panels don't have a heading/title.

**Comment by AJenbo** [comment]
Idk, the panels are pretty ovoius, and destinct to easy to learn even if you don't know what inv stands for.

**Comment by julealgon** [comment]
I think not having any association between the open panel and the UI which is responsible for opening it is bad UI design. This is why this felt like an interesting issue that I think would make sense looking into (even though I'd agree it is very low priority).

I'm also in favor of having close buttons on the panels for the same reason. Yes, most people will probably not use them, but people that are very new to the game or gaming in general will get confused about it.

These things are tailored to really newbie players, obviously.

**Comment by vladtepesch** [comment]
maybe another button grafic could be created that looks a bit more recessed and slightly darker.
this could then used for the moment of the click and the original button may be used for the state. So that it acts like a real toggle button

**Comment by StephenCWills** [comment]
> I think not having any association between the open panel and the UI which is responsible for opening it is bad UI design.

The association occurs when you press the button and it toggles the panel. It's like double-clicking a file and the file opens. Or clicking the "Open File..." button and you get an open file dialog. Or going to "File > New Project" and you get a new project wizard. None of these types of buttons would indicate the state of the window, panel, or tab that they spawn.

To be fair, I think I can see where you're coming from. The action performed by these buttons is similar to a toggle and so it does seem natural to think that perhaps the toggled state should be indicated visually by the buttons. However, that doesn't make it bad UI design to visually represent these as buttons rather than, say, checkboxes.

For example, if it could be shown that the user is prone to accidentally closing the quest panel because they didn't know it was open, I would consider that a good reason to find another way to indicate visually whether the quest panel is open.

**Comment by julealgon** [comment]
> It's like double-clicking a file and the file opens. Or clicking the "Open File..." button and you get an open file dialog. Or going to "File > New Project" and you get a new project wizard. None of these types of buttons would indicate the state of the window, panel, or tab that they spawn.

It tends to vary from what I see. For instance, take the taskbar on Windows:
![image](https://user-images.githubusercontent.com/461579/129743780-89613ee6-93a6-40e0-bee1-d567b79fc209.png)

Notice how it highlights Edge because that's the window I have opened. Similarly, the tabs in the browser follow the same design.

At the same time, the examples you gave are valid, as is the toolbar in the right-hand side of the taskbar, which also serves as shortcuts but with no highlight.

In any case, I do still consider this quite minor.
