### ISSUE TITLE
Normalize line endings throughout

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#262]
Currently some files in the project use CRLF while others use just LF.

This makes it difficult to configure some editors, such as VS Code.

We should make line endings consistent throughout (don't care which).

However, we should probably do this *after* the large outstanding PRs are merged, because rebasing and resolving merge conflicts is painful when line endings change.

**Comment by AJenbo** [comment]
I personally strongly prefer LF, but seeing as how upstream is CRLF I think we should stick with it (it's what is configured in the project after all)

**Comment by telamon** [comment]
my editor supports `.editorconfig`, and using latest `.gitattributes` but i think your combo is misconfigured. 

No matter what i do i'm either seeing added `^M` line-endings in `git-diff` or entire files changed.

Please consider:
```bash
# .gitattributes
* text=auto eol=lf
```

**Comment by AJenbo** [comment]
These settings do not match what we use, also I don't think having git magically convert line endings is a good idea it creates more issues then it solves.

The ^M could just be an issue with what ever program you have set to the default for `git-diff`, it's hard to say since you don't say what platforms or tools you use.
