### ISSUE TITLE
Crash when viewing part of level

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2621]
Since commit e9f1d6ad882b4be26d513857a6cf6fa54206a696 the game crashes in a special situation.

To reproduce load attached game and try to walk to the east direction.
[crash.zip](https://github.com/diasurgical/devilutionX/files/6993647/crash.zip)

**Comment by AJenbo** [comment]
You likely have a save that was create between that and https://github.com/diasurgical/devilutionX/commit/f289fbcec5f984da8428445530f452880063f617

**Comment by ThomasChr** [comment]
Debug on dc059dadb8addbfe79524b314c45e31905424bf8 (Linux)
I get an error message straight on load: 
![image](https://user-images.githubusercontent.com/13014163/129606645-4680eafa-7659-43b6-a512-fee2d013551b.png)

**Comment by Chance4us** [comment]
However, in vanilla the game doesn't crash with the savegame.

**Comment by Chance4us** [comment]
So if the next created games should not have any more problems we can ignore this bug report.

**Comment by Chance4us** [comment]
> There is a dead monster with nullpointers in it. So it mast be really, really dead!

Can/Should we fill the null pointers with dummy values so that the game doesn't crash?

**Comment by ThomasChr** [comment]
It's exactly the line 
```
nd++; // Unused blood spatter
```
from commit e9f1d6ad882b4be26d513857a6cf6fa54206a696

This does jump over Array Index 8 which is the one index provoking the crash because of not having been initialized.
Problem is: I just don't know enough to really see why 'nd++;' is needed here.

**Comment by Chance4us** [comment]
I suppose it's this one monster that looks similar to snotspill.
![monster](https://user-images.githubusercontent.com/45902449/129612361-32aac674-a45b-4d55-b1b9-ccb14d93d5a9.png)

**Comment by Chance4us** [comment]
> You likely have a save that was create between that and [f289fbc](https://github.com/diasurgical/devilutionX/commit/f289fbcec5f984da8428445530f452880063f617)

@AJenbo Most likely, can we ignore the case?

**Comment by Chance4us** [comment]
One more thing has arisen that I would like to report on. I continued to play the savegame above and discovered that if gharbad is killed the game crashes immediately.
Next savegame:
[gharbad.zip](https://github.com/diasurgical/devilutionX/files/6994784/gharbad.zip)

**Comment by AJenbo** [comment]
> One more thing has arisen that I would like to report on. I continued to play the savegame above and discovered that if gharbad is killed the game crashes immediately.
> Next savegame:
> [gharbad.zip](https://github.com/diasurgical/devilutionX/files/6994784/gharbad.zip)

Invalid save games are invalid

**Comment by AJenbo** [comment]
To elaborate a bit here, in https://github.com/diasurgical/devilutionX/commit/f289fbcec5f984da8428445530f452880063f617 i removed the unused blood splatter from the game, since it was not the last of the "corpses" it shifts the array indexes, I initially intended to remap them when loading save games, but submitted the code before doing so as it solved some other issues (missing missiles).

Shortly after I ended up deciding against remapping the index since it would mean that there would be some backwards comparability issues in doing so, and simply having an empty index where the previously unused one used to be was a much simpler fix.

The consequences then was that save games made in this time frame would have invalid monster corpses which leads to crashes, but that is acceptable for development versions.

The end result here is that we are both stable and compatible, but players should avoid that range of commits as it will generate invalid saves.

@Chance4us thanks as always for testing and reporting :)
