### ISSUE TITLE
Shift clicking locks on original position of first target

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2695]
**Describe**
When shift clicking on a monster/item/object the player will keep attack in the direction of the same tile.

**To Reproduce**
1. Go to dungeon
2. Fine an item or an object
3. Point to the item/object
4. Hold shift+click
5. Move the mouse around
6. Notice that you keep attacking in the same direction.

**Expected behavior**
The high light should not be locked when shift was activated, and attack should track the mouse movement.

**Comment by julealgon** [comment]
This is directly related to my change here:
https://github.com/diasurgical/devilutionX/pull/1366

The problem is that SHIFT+Attack turns into a `ATTACK_XY` command, which is positional (targets a XY tile), while attacking a monster without SHIFT clicking produces a `ATTACK_ID` command, which targets a specific entity ID.

I believe that fixing my PR to work with the newer version of the code would fix this, but I have not been able to make it work after the "hold to attack" feature was added.

**Comment by AJenbo** [comment]
That sounds like the opposit of what I am saying here. Shift+click should result in ATTACK_XY, the problem here is that it always happens for the same coordinate despite mouse movement.

**Comment by julealgon** [comment]
> The intent of shift+click is to ignore targets and make attacks in specific directions. If you want to attack targets, don't hold shift.

I disagree. The intent should only be restricted to "not move". I think actually targeting monsters when shift+clicking on them leads to a far better gameplay experience, and this goes for both ranged and melee.

It should only ignore targets when targeting the floor, in which case it should be ATTACK_XY and track the mouse cursor.

**Comment by AJenbo** [comment]
But that could results in movement if the target moves between issuing the command and execution. And for ranged attacks it makes it near impossible to do deflection shooting.

**Comment by julealgon** [comment]
> But that could results in movement if the target moves between issuing the command and execution.

Not with my change. I introduced a flag to prevent movement in the `ATTACK_ID` command, so if you clicked a monster while holding shift, it will never move. When the command is executed, the target is tracked even if it moves (this is actually why normal attack is more precise than shift+attack as I mentioned in the stream).

> And for ranged attacks it makes it near impossible to do deflection shooting.

Not sure exactly what you mean here. Is it to predict the position and attack there? You can still do that by targeting the tiles instead of the monsters.

**Comment by AJenbo** [comment]
I see shift+click as a way to switch to manual aim, so combining it with auto aim seams a bit counter productive. Maybe we need ctrl+click :D
We could actually make a seperate mode and you can then bind either to shift+click depending on preference.

> Not sure exactly what you mean here. Is it to predict the position and attack there? You can still do that by targeting the tiles instead of the monsters.

It can get problematic in some situations.

**Comment by StephenCWills** [comment]
I agree with AJenbo from the perspective of advanced tactics. However, I do think julealgon is right in that `ATTACK_ID` does likely provide a better gameplay experience in general.

> We could actually make a seperate mode and you can then bind either to shift+click depending on preference.

I've been thinking for a while that we need something like this. Ideally, I'd like if we could decouple input states from game action states and then provide a data-driven mapping between them so they can be freely remapped by the user. Easier said than done, of course.

**Comment by julealgon** [comment]
I'd suggest renaming this issue to "Shift hold clicking..." to avoid confusion in the future.

**Comment by StephenCWills** [comment]
> I'd suggest renaming this issue to "Shift hold clicking..." to avoid confusion in the future.

What did you think this was about?

**Comment by julealgon** [comment]
> What did you think this was about?

When looking at the issue title popping up again, it gave the impression that it was talking about vanilla shift+click functionality.

Only after checking the discussion again I remembered it was related to the hold-mouse button-to-attack feature.

**Comment by AJenbo** [comment]
But in vanilla you also hold down shift continually while clicking. Someone might still miss understand and need to read the description before realizing exactly what the issue is about. Or they remember the old title and think this is a different issue.
