### ISSUE TITLE
Don't show text for inactive town entrances

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2785]
![image](https://user-images.githubusercontent.com/14297035/131847779-d49494cd-5384-474e-b6af-66d7a367c5f9.png)

It works fine in vanilla, so this is a devilutionx issue.

**Comment by AJenbo** [comment]
The cave graphics is set here: https://github.com/diasurgical/devilutionX/blob/03eb86b1186f69e1e87366b1ed5e59556fa9d231/Source/town.cpp#L173

And the text is set here:
https://github.com/diasurgical/devilutionX/blob/01823e1324f02824cc22d1dae8a8c04f024cf356/Source/trigs.cpp#L362

This could potentially happen if the players level increased while in town, 
https://github.com/diasurgical/devilutionX/blob/01823e1324f02824cc22d1dae8a8c04f024cf356/Source/trigs.cpp#L86

Was debug commands used in this run?

**Comment by qndel** [comment]
yup :D

**Comment by julealgon** [comment]
I think closing this altogether is premature. This is an opportunity to make the command and handling more robust.

**Comment by qndel** [comment]
> I think closing this altogether is premature. This is an opportunity to make the command and handling more robust.
> 
> EDIT: Note that a mod might have stuff like "+EXP rewards for quest completion" and it would cause the same issue. Fixing this would be very beneficial.

I'm not sure I understan ... can you elaborate? xD

**Comment by AJenbo** [comment]
Just call the town update function like other quests, there really isn't much to fix here, hacking your level is not supported.

**Comment by julealgon** [comment]
> Just call the town update function like other quests, there really isn't much to fix here, hacking your level is not supported.

I think you are misunderstanding me here. 

Do we refresh town when the player levels up? If town has elements that are triggered based on player level, then it should properly react to player level changes. It seems we don't today. And this is what I'm proposing we do, so that mods can leverage level ups in town without worrying that it will break things like what happened here.

Level up in town would also cause Griswold items to refresh.

Again, I'm saying in generic terms that we should make the game rules consistent regardless if level ups can or cannot happen in town right now, because it would make sense for them to happen eventually.

I know "hacking your level is not supported".

**Comment by qndel** [comment]
Who cares, show me someone making a mod and I'll care xD

**Comment by NiteKat** [comment]
Wait... isn't this a bug anyway? Was this in single player? You aren't supposed to have the text at all in Single Player until you take the shortcut from floor 9, so the text shouldn't be level dependent, and in Multiplayer it always displays open and shows the text regardless of character level, unless I'm missing something...?

**Comment by AJenbo** [comment]
You are in Hellfire

**Comment by NiteKat** [comment]
They really messed everything up with Hellfire, didn't they? 🤣
