### ISSUE TITLE
[vanilla] Oil of hardening doesn't always work

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2824]
Oil of hardening doesn't always work. Same issue like in vanilla tested. I don't know if it is by design.
![hardening](https://user-images.githubusercontent.com/45902449/132398612-add42b7b-f84e-46ac-b34c-13032a35e8dc.png)
Savegame:
[hardening.zip](https://github.com/diasurgical/devilutionX/files/7123863/hardening.zip)

How to reproduce:
1. Load attached game
2. Try to upgrade the armor class of the armor
3. Notice that there is no improvement, but the oil is used up

**Comment by julealgon** [comment]
It only increases armor up to 60.

> Hardening | 2 500 | 1 | Adds 1-2 AC (if < 60) 

Section 3.2.1 Runes and oils in Jarulf's guide.
http://www.bigd-online.com/JG/JGFrame.html

**Comment by AJenbo** [comment]
@Chance4us thanks for testing, in case you aren't aware we expect the 1.3.0 release to come out in October so we need to get things stable for that :)

**Comment by Chance4us** [comment]
> @Chance4us thanks for testing, in case you aren't aware we expect the 1.3.0 release to come out in October so we need to get things stable for that :)

I play a lot of games and haven't noticed any new bugs so far. The quality of the program code is very satisfactory at the moment. I am very happy and thank you much for the great work. I will continue to test intensively so that we can get a good release.

**Comment by julealgon** [comment]
BTW, the original design here is clearly less than ideal. At some point, I think we should improve it by:
- Improving the description on the item to add the restriction explicitly so the player knows upfront
- Instead of "zero feedback", play some message explaining it can't be used (lots of voice lines could be used for this purpose)
- Instead of destroying the source item, do nothing when it cannot be applied

The last point obviously is something much bigger than just oils. The same issue happens when using anything that is targetable, like TP scrolls, identify, etc.

Changing that part will require some work in the engine to avoid consuming the item when it is first right-clicked to just "temporarily disabling the item", like D2 does. If the cast is cancelled for any reason, the item is reactivated and not consumed.
