### ISSUE TITLE
Arrows Bypass Target Tile at Certain Angles and Distances

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#2837]
**Important information**
Windows 10 / 1.2.1 / Downloaded Release

**Describe**
At certain angles and distances, your arrows will bypass the targeted tile. This can make it impossible to hit a monster without moving slightly to the side or another direction.

**To Reproduce**
1. Load attached save file.
2. Move mouse over the monster shown in the screenshot.
3. Click on it to your hearts content. Your arrows will never land.

**Expected behavior**
With no obstructions between the player and monster, the player should be able to hit them.

**Screenshots**
![image](https://user-images.githubusercontent.com/28605404/132920311-f9f3e899-04c0-44a1-9601-433697084eac.png)

**Additional context**
If you move slightly to the right (non-isometrically, so thinking +1 in x-axis), the monster stays on screen and can be hit with arrows by clicking on them, and you can hit them pretty easily, so I do not believe this is a case of the to hit dropping to 0 from the distance.

[single_2.zip](https://github.com/diasurgical/devilutionX/files/7146605/single_2.zip)

**Comment by obligaron** [comment]
I tested it with master and #2831.
In master I can't hit the target (as described) but with #2831 I can kill the monster.
So hopefully #2831 should fix this issue. 🙂

**Comment by StephenCWills** [comment]
The monster is on (72,34) and the player is on (71,43) here's the set of collisions along the path of the missile.

```
INFO: [0] Collision (71,42)
INFO: [0] Collision (71,41)
INFO: [0] Collision (71,40)
INFO: [0] Collision (71,40)
INFO: [0] Collision (71,39)
INFO: [0] Collision (71,37)
INFO: [0] Collision (71,37)
INFO: [0] Collision (71,35)
INFO: [0] Collision (71,34) **
INFO: [0] Collision (72,33) **
INFO: [0] Collision (72,33) **
INFO: [0] Collision (72,32)
INFO: [0] Collision (72,31)
INFO: [0] Collision (72,30)
```

So it transitions the x-coordinate from 71 to 72 right as it reaches the target tile, but it misses that tile completely. I also find it really interesting that it passes over (71,38) and (71,36) but hits (71,37) twice. I thought arrows moved slow enough that skipping tiles wouldn't be an issue, but perhaps I was wrong.

**Comment by NiteKat** [comment]
> I thought arrows moved slow enough that skipping tiles wouldn't be an issue, but perhaps I was wrong.

I bet it's angle dependent. It's probably just passing over like the corner of a the tile in the path, and not there "long enough" to register a check on that tile.

**Comment by NiteKat** [comment]
@julealgon Should add the Vanilla tag too, as this is in Vanilla.

**Comment by julealgon** [comment]
> In master I can't hit the target (as described) but with #2831 I can kill the monster.
> So hopefully #2831 should fix this issue. 🙂

Can you add a `fixes`-type comment so there is a strong link there?

**Comment by StephenCWills** [comment]
> I bet it's angle dependent. It's probably just passing over like the corner of the tile in the path, and not there "long enough" to register a check on that tile.

As far as the target tile is concerned, I was initially thinking that it must be due to the truncation when translating pixel coordinates to tile coordinates. If the tile coordinates are directly translated to pixel coordinates without any adjustment, it would mean that you're actually aiming at the north corner of the target tile rather than the center of it, so the missile would only have one point along the path at which it could actually collide with the target tile. However, if that were really the case, you'd have the same problem at any angle that's more east/west than north/south so that must not be it.

The (71,38) and (71,36) tiles are more interesting, IMO, because there's no x-coordinate transition there. The missile just literally skips over them even though they're right in the middle of the arrow's path. It kind of looks like there's a weird rounding issue going on there, too, because apart from those two tiles, the arrow looks like it's moving just a tiny bit slower than one y-coordinate per tick.

**Comment by obligaron** [comment]
> Can you add a `fixes`-type comment so there is a strong link there?

done 😉
