### ISSUE TITLE
Monsters and Players occupying same tile

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#2838]
**Important information**
Windows 10 / 1.2.1 / Downloaded Release

**Describe**
If a monster is on the tile where the player will spawn on a floor, the game will put the player on that tile at the same time as the monster.

**To Reproduce**
1. Load attached save file.
2. Click to enter the 1st floor

**Expected behavior**
The player should not spawn on top of a monster. Maybe the game should search for an open tile to spawn on?

**Screenshots**
![image](https://user-images.githubusercontent.com/28605404/132923743-21162765-85a9-459a-a448-15e2f4ffebf3.png)

**Additional context**
This is also a vanilla bug.

[single_0.zip](https://github.com/diasurgical/devilutionX/files/7146727/single_0.zip)

**Comment by julealgon** [comment]
Would it make sense to actually prevent the monster from moving into the trigger tile in the first place I wonder?

Sure it would be slightly weird, but it would be a fairly straightforward fix compared to the more obvious "check all adjacent tiles in a certain order until you find an empty one".

**Comment by StephenCWills** [comment]
> Would it make sense to actually prevent the monster from moving into the trigger tile in the first place I wonder?

I think that's not the trigger tile, but rather the player's spawn tile. Players already avoid spawning on each other's tiles so they just need to avoid monsters (and solid pieces #1492) as well.

**Comment by FitzRoyX** [comment]
Couldn't a mob of monsters occupy all but 1 tiles around the stairs if you were chased there? Then there would be no place to spawn players except ontop of monsters.

**Comment by StephenCWills** [comment]
> Couldn't a mob of monsters occupy all but 1 tiles around the stairs if you were chased there? Then there would be no place to spawn players except ontop of monsters.

You have compelled me to search for the logic that determines the player's initial spawn location. Apparently, the game uses different logic for Single Player and Multiplayer.

The Single Player logic is hardly worth mentioning. It literally just spawns you on the default spawn tile regardless of any possible obstacles. I suppose the assumption is that there shouldn't be any obstacles because there are no other players in your game, but there are obvious counterexamples that we've already found.

It looks to me like the Multiplayer logic already avoids spawning the player on monsters and obstacles. It seems to be searching for an available tile within 50 tiles of the default spawn tile. So it seems pretty unlikely that there would be no available tiles on which to spawn. For the sake of argument, if there were no available tiles, it would just place the character on the last position it checked, which appears to be 50 tiles to the south of the default spawn tile. It's worth noting that this logic does not use the crawl table, but rather just keeps widening the search area and checking every tile within. So there's a lot of time spent checking tiles that have already been checked.
