### ISSUE TITLE
[vanilla] Defective lava with mirroring effect

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3130]
The issue looks similar to #477 but is not the same.
The savegame also looks the same in vanilla. 
[mirroring.zip](https://github.com/diasurgical/devilutionX/files/7346719/mirroring.zip)
![lava](https://user-images.githubusercontent.com/45902449/137335758-2c7608c4-32ea-46e9-be95-220473556874.png)

Or could there be a regression? Somehow it looks exactly the same.

**Comment by galaxyhaxz** [comment]
Hmm I partially blame myself for not explaining my bugfix properly: https://github.com/diasurgical/devilutionX/issues/477#issuecomment-554682878

It appears @AJenbo applied this fix in commit here https://github.com/diasurgical/devilutionX/commit/c3456e7dbd257bc8018adc3202ed04d1f38fcbaf

This fix ONLY fixes that particular map. It is a **_hack_** to manually change the two broken tiles on that specific map. The layouts of broken lava tiles vary greatly in these bugged maps, which the ***root cause*** is the function I mentioned before not filling them in.
