### ISSUE TITLE
IPX support

### ISSUE THREAD

**Issue by ghormoon** [diasurgical/devilutionX#325]
do you also consider IPX support? would be nice to be actually able to connect to original game runnig on win95/98 during retro gaming sessions (and that one doesn't to support tcp at all)

**Comment by AJenbo** [comment]
Not considered IPX, I wouldn't know where to start since most operating systems don't have a stack for it anymore 😅
Afaik most people use wrappers and not real IPX, but we have considered making the UDP implementation compatible with the originals (the original game supports UDP, but it is unlisted, it what was used for battle net, since battle net is just a list of running games it should be possible to join a game on a known IP).

**Comment by sskras** [comment]
Not pushing developers, just referencing a sample code to interface IPX via WinAPI for those possibly interested in the topic:
https://www.winsocketdotnetworkprogramming.com/winsock2programming/winsock2advancedotherprotocol4a.html (WinAPI)
https://www.codeproject.com/Articles/172/Checking-IPX-communication-and-obtaining-node-addr (WinAPI)
https://www.opennet.ru/base/dev/ipx_srv.txt.html (ru, Linux)
http://frolov-lib.ru/books/bsp/v08/ch2_4.htm (ru, DOS)

**Comment by sskras** [comment]
OTOH, there are working IPX tunnel over IP implementations which can be used to bridge to physical IPX network, like the `IPXbox` protocol / client implemented by the DOSBox:
https://github.com/fragglet/ipxbox

A ported Doom tutorial for connecting the multiplayer to old, physical machines. It describes a setup of tunneling client for both internal (DOSbox IPX) and external (IPXbox) tunnel servers:
https://www.chocolate-doom.org/wiki/index.php/IPX_protocol_support 
(Of which only the last is interesting here)

If `ipxbox` becomes a lib (at least a client lib), devilutionX could probably use it to do the same.
