### ISSUE TITLE
CMake: Option to use system SDL_Image

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#3384]
Writing a package definition for DevilutionX (for RetroLX) and discovered there's no way to tell it to use the system SDL_image.

**Comment by StephenCWills** [comment]
> Writing a package definition for DevilutionX (for RetroLX) and discovered there's no way to tell it to use the system libpng.

I feel like I'm missing something. Did you mean to say SDL_image in the comment as well?

https://github.com/diasurgical/devilutionX/blob/3f065d579498a92b0e2a4c1ee5e34c1dcae5b0a0/CMakeLists.txt#L92-L94

FYI, I didn't include an option for system SDL_image because we're using a subset of the full library. However, I suppose we should still be compatible with the full library.

**Comment by glebm** [comment]
Yeah libpng was a typo. For reference https://github.com/RetroLX/RetroLX/pull/26

**Comment by glebm** [comment]
Basically for distributions it is usually desirable to vendor as little as possible, in order to:
1) Reduce image size.
2) Be able to update dependencies wholesale.
