### ISSUE TITLE
Hellfire crashes on load with Nintendo 3DS

### ISSUE THREAD

**Issue by 3F2A8C4AE9** [diasurgical/devilutionX#3445]
**Important information**
This happened on both the 2DS and 3DS as mentioned in issue #3444, using the same .cia installation. Admittedly, I should've posted this first as clearing this hurdle brought me to that problem above. 

**Describe**
When Hellfire is set to "Intro = 1" in Diablo.ini, the game will crash after the Sierra logo sequence. Changing it to Intro = 0 and leaving Diablo as Intro = 1 works as expected. 

**To Reproduce**
1.) Install .cia to 2DS/3DS. 
2.) Without editing the diablo.ini file, try to load the game.
3.) Sit through or skip the Sierra logo sequence.
4.) Crash. 
5.) Edit the diablo.ini file and change Intro = 1 to Intro = 0 under [Hellfire]. 
6.) Relaunch the game.
7.) Skip the Sierra logo.
8.) Get the Hellfire title screen and options afterwards.

**Expected behavior**
The game should load the title and the Single Player/Multiplayer/etc screens after the Sierra video. 

**Screenshots**
I couldn't take screenshots of the crash happening.

**Additional context**
--

**Comment by StephenCWills** [comment]
Thanks for reporting. This issue was identified on Discord a couple days ago. The fix for now is to increase available RAM to 80MB at the cost of startup performance. I suspect the same issue would occur when playing the ending cutscene after defeating Diablo as well.

Since this is a pretty major issue, I updated the release just now with the build from 9060995. FYI, I have also replaced the zip file we had before with just the cia for a couple different reasons, not the least of which is that the 3dsx should still be afflicted by this issue.

**Comment by AJenbo** [comment]
> FYI, I have also replaced the zip file we had before with just the cia for a couple different reasons, not the least of which is that the 3dsx should still be afflicted by this issue.

Happy it's gone, lets remove it from the docs and builds as well
