### ISSUE TITLE
[Feature request] allow best alignment for item placement

### ISSUE THREAD

**Issue by twojstaryzdomu** [diasurgical/devilutionX#3535]
**Expected behavior**
A common problem occurs when the current weapon in use is moved back to inventory. The initial position for the item moved is somewhat centric, not left-aligned, which would be more optimal.

If there is space in the inventory, can a best alignment be used for item placement? A new item added to the inventory would be always left-aligned within the inventory or placed in the largest left-aligned contiguous region as large as the item.
This saves some time when cycling weapons, rather than having to spend time on aligning inventory items.

If this departs from the original Diablo, please consider making this alignment protocol enabled via a menu option or ini parametr.

**Comment by AJenbo** [comment]
There are good reasons for not just filling from the left, since items do not have the same size and so won't stack well if filled in a random order, see:

https://github.com/diasurgical/devilutionX/pull/1542

and

https://github.com/diasurgical/devilutionX/pull/1876

**Comment by twojstaryzdomu** [comment]
@AJenbo, you're closing this far too quickly.

Did you read the comment on using the largest available left aligned contiguous region?

I think you misread the FR, this isn't the proposal to use random placement but a smart one that attempts to left align as much as possible. This is far better than the current one when moving items.

**Comment by twojstaryzdomu** [comment]
Please open this for a discussion, it seems your closing is not welcoming any.

**Comment by qndel** [comment]
How about providing some screenshots or something? Atm I have no clue what's going on.

**Comment by StephenCWills** [comment]
> I think you misread the FR, this isn't the proposal to use random placement but a smart one that attempts to left align as much as possible.

FYI, I believe you're the one who misread. AJenbo said nothing about random placement, but rather placing items in a random order. In other words, we can't control what order the user decides to place items in their inventory so the algorithm must be generic under the random (or, if you prefer, arbitrary) ordering assumption and still make efficient use of space.

> This is far better than the current one when moving items.

Your proposed algorithm would potentially cause more conflicts in edge cases involving 1x1 items that would likely be undesirable for many players given the amount of space typically taken by 3-height weapons and armor in this game.

> I see weapons being off from the position they could fit in perfectly.

I'm with @qndel. I don't really understand what you're talking about. For me, 3-height weapons and armor always fill from the left for me. Rather than removing equipment, are you perhaps swapping equipment?

**Comment by twojstaryzdomu** [comment]
> Your proposed algorithm would potentially cause more conflicts in edge cases involving 1x1 items that would likely be undesirable for many players given the amount of space typically taken by 3-height weapons and armor in this game.

Take the item from the screenshot. The bow from the inventory overlaps when the items are moved from the body slot, clearly indiciating an issue.

BTW do you have an issue with this FR remaining open? 

It comes across as rude to the community when you close immediately without giving an opportunity to invite comments from others tracking open issues.

**Comment by AJenbo** [comment]
> Take the item from the screenshot. The bow that was in the body slot overlaps an item in the inventory, which is unwarranted there being ample space, cleared by moving the knife to the body slot. This often happens when the currennt weapon being moved from the body slot to the inventory gets a non-optimal position that needs to be manually adjusted, clearly indicating an issue.

I don't follow at all. By knife are you referring to the cleaver or the Scimitar?
I can't think of any scenario where the current implementation tries to position the bow where you are holding it in the screen shot. Also it's still not clear if you are talking about what happens when you try to swap items or another scenario. And what was the previous position of the items?

Even if things are sub-optimal it might not be trivial to change, in which case a long living issue creates more clutter then clarity. Especially if the issue is obvious. Once the given code is cleaned up efficiently to trivially solve the issue it would likely get picked up and solved at that time.

We already have 200 open issues and 100 open PRs, which is already a lot to manage for us. For that reason we are a bit judicial in what new issues should be created.

As you have noticed closing an issue also doesn't mean that it is no longer possible to comment on it, but it does avoid us having a lot of open issues that aren't ready to be worked on.

For ideas and features that are still in the idea phase we prefer that the chat is used to brain storm and evaluate before an issue is created. Please join our community and see how things are managed, it will help avoid misunderstandings like this: https://discord.gg/YQKCAYQ

We also take feasibility, as well as the likely hood that someone would be working on it, in to consideration. Is this something you intend to work on?

I hope that clears up the reasons why we manage things this way.

**Comment by twojstaryzdomu** [comment]
> I don't follow at all. By knife are you referring to the cleaver or the Scimitar?
The butcher knife that used to sit in the 3x2 slot in the inventory and has been replaced with the bow in the body slot. Both items are 3x2 and yet the bow does not get the slot vacated by the butcher knife. The bow is in the position after the item swap. Does it help? I'm sorry if the weapon names are slightly different, I'm playing a non-English language.

On closing issues, I perfectly realise the purpose it serves to free up the roster from clutter yet if these disappear all too quickly as closed then nobody but the few that saw it get the chance to pitch in. I believe there is some merit to the problem voiced here that warrants community feedback.

**Comment by AJenbo** [comment]
> The butcher knife that used to sit in the 3x2 slot in the inventory and has been replaced with the bow in the body slot. Both items are 3x2 and yet the bow does not get the slot vacated by the butcher knife. The bow (on the left) is in the position shown in the screenshot after the item swap. Does it help?

In your screen shot the bow is being held in the cursor and not placed in the inventory.

I take swapping to mean you hold shift and clicking on an item from the inventory. But what you are showing appears to be an inventory that is was full, meaning that you would not be able to do an automatic swap. Simply nothing would happen, (bow would still be equipped and the cleaver would still be in the inventory) and the hero would would say that the action isn't possible.

Is the screen shot really from the described scenario, or are you trying to illustrate it with a proxy?

Can you provide a gif/video/save so that we can better see what you are doing?

**Comment by StephenCWills** [comment]
I think I get it now. He's using the gamepad to swap weapons by picking up the cleaver from his inventory, swapping for the bow that was equipped, and then moving the cursor with the bow back down to the inventory space. The placement of the cursor isn't optimal for placing the bow in the location where the cleaver used to be.

**Comment by twojstaryzdomu** [comment]
A virtual gamepad. After the desired item is the weapon slot, I swipe down to move the former weapon from the slot down to the inventory.
At this point, the weapon (bow as evidenced in the screenshot) gets the non-optimal position, o erlapping the staff.
Yes the screenshot is from an actual game, not doctored or anything.

**Comment by qndel** [comment]
it doesn't work like this, even with mouse lol

**Comment by StephenCWills** [comment]
> it doesn't work like this, even with mouse lol

This isn't really applicable for mouse because it has to do with the way we snap the cursor position to inventory slots when using a d-pad or analog stick.

**Comment by AJenbo** [comment]
> A virtual onscreen gamepad from the android game.

Ok, this is a known issue when using a gamepad. It doesn't affect mouse/keyboard. If you have time to work on fixing it that would be helpful.

**Comment by twojstaryzdomu** [comment]
> Can you provide a gif/video/save so that we can better see what you are doing?



> Can you provide a gif/video/save so that we can better see what you are doing?

![Screen_Recording_20211118-183141_DevilutionX](https://user-images.githubusercontent.com/54865449/142476672-15a67cca-de72-4f20-b648-bd764be6ea35.gif)

**Comment by StephenCWills** [comment]
> BTW do you have an issue with this FR remaining open?
> 
> It comes across as rude to the community when you close immediately without giving an opportunity to invite comments from others tracking open issues.
> 
> Much I'd like to get involved in contributing and improving the software, @AJenbo is sending a dismissive message closing without a chance for it to elicit community feedback.

I hope I'm not simply reigniting an otherwise resolved point of contention, but I think it's worth contributing another point of view here. Truthfully, I was initially 100% in agreement with AJenbo's decision to close this issue. The message sent by closing an issue may indeed be taken as being dismissive, but you should also consider the message you send by stripping down the issue template. The title and issue description does not provide enough detail or clarity for us to identify the behavior you were attempting to describe.

Knowing what we know now, I would support reopening this issue if the title and description were updated to provide better clarity.

**Comment by twojstaryzdomu** [comment]
> > BTW do you have an issue with this FR remaining open?
> > It comes across as rude to the community when you close immediately without giving an opportunity to invite comments from others tracking open issues.
> > Much I'd like to get involved in contributing and improving the software, @AJenbo is sending a dismissive message closing without a chance for it to elicit community feedback.
> 
> I hope I'm not simply reigniting an otherwise resolved point of contention, but I think it's worth contributing another point of view here. Truthfully, I was initially 100% in agreement with AJenbo's decision to close this issue. The message sent by closing an issue may indeed be taken as being dismissive, but you should also consider the message you send by stripping down the issue template. The title and issue description does not provide enough detail or clarity for us to identify the behavior you were attempting to describe.
> 
> Knowing what we know now, I would support reopening this issue if the title and description were updated to provide better clarity.

This wasn't a bug report but a feature request initially. Closing by default without asking for feedback is merely a sign of maintainer arrogance and a sign of poor judgement. As a long term policy it's discouraging feedback from users. Whether a template was stripped down is immaterial.

**Comment by AJenbo** [comment]
I have already explained that the high number of issues means that the ones with insufficient merit may get closed. If additional information is added they can be reopened. The template is there to help us manage the many incoming issues created by people. Disregarding it means you are putting an extra burden on us, which is limiting how much time we can invest in each issue.

Your communication seams both aggressive and hostile and at this point, I am not appreciative. I don't think it's productive to focus on this aspect any longer.

> That said, I'm happy if the FR helped identify an issue.

As mentioned it is a known issue with the gamepad navigation.

**Comment by StephenCWills** [comment]
> Not much was missing in truth from the report.

It sounds to me that you feel there is nothing left to contribute to the discussion. I believe we've reached an understanding about the behavior in question so I am locking the discussion.
