### ISSUE TITLE
Diablo II support ?

### ISSUE THREAD

**Issue by liberodark** [diasurgical/devilutionX#355]
Hi,

Just one question have possibility to support later Diablo II 1.14d ?

Best Regards

**Comment by galaxyhaxz** [comment]
We'll add that when were finished adding Pizza party support.

**Comment by AJenbo** [comment]
No aspirations to do so, the games aren't that similar, should probably look to a different project for D2 implementation.

**Comment by liberodark** [comment]
thanks for your reply ^^

**Comment by AZRAEL-III** [comment]
Diablo 2 when, OpenDiablo2 is dead so if y'all folks can do it, i will donate

**Comment by qndel** [comment]
> Diablo 2 when, OpenDiablo2 is dead so if y'all folks can do it, i will donate

I simply love when people act as it is something that can be pulled out of our asses during the weekend, we are talking about years of work + blizzard is still actively involved in d2 (d2r) so yeah even if your donation was a million dollars (I'm pretty sure that's the amount we are talking about right? RIGHT?), split it between all people involved + add potential legal trouble from blizzard = no thanks

**Comment by AZRAEL-III** [comment]
i was just asking if this was in the project, i was just asking okay ? I know that's a long thing to do, but okay, i understand.

**Comment by sskras** [comment]
@AZRAEL-III, it was answered by @AJenbo already [4y ago](https://github.com/diasurgical/devilutionX/issues/355#issuecomment-541321247):

> No aspirations to do so, the games aren't that similar, should probably look to a different project for D2 implementation.

I suppose you were asking but not reading. No offense, and merry Christmas:)

**Comment by AZRAEL-III** [comment]
> @AZRAEL-III, it was answered by @AJenbo already [4y ago](https://github.com/diasurgical/devilutionX/issues/355#issuecomment-541321247):
> 
> > No aspirations to do so, the games aren't that similar, should probably look to a different project for D2 implementation.
> 
> I suppose you were asking but not reading. No offense, and merry Christmas:)

Yeah thanks, i read all that, an there's only OpenDiablo2 (which doesn't work anymore in the newer builds of linux Mint and Ubuntu), i were asking, but i've got my response. Thanks again

**Comment by AJenbo** [comment]
Merry Christmas

**Comment by PhoenixBlade24** [comment]
I would gladly donate to support a Free engine replacement for Diablo II, particularly if one of it's end goals being a Free asset replacement similar to Freedoom. If there was no legal risk present for Diablo I, a game that is still being sold to this day on GOG and Battle.net, then I doubt Diablo II would run into any issues. Some talented folks are even working on engine replacements/decomps/recomps for Nintendo games, the most brutal corporation in gaming when it comes to copyright trolling and C&Ds. Blizzard would have no legal capability to sue a project of this kind, because it's not using any of their copyrighted code or assets. The users would have to supply the game data themselves, which they can if they purchase a legal copy of Diablo and Diablo II.

A Free asset replacement would be a dream of course, since it would bypass any risk whatsoever, being that it would be perceived as legally distinct and therefore immune to any and all legal actions by any major corporation. But to craft an engine + an asset replacement is an incredibly lofty undertaking, such a prospect would take a lot of time. But for one of the greatest games of all time, I believe there would be quite a few who would donate to such an effort. If only to see Blizzard seethe and cope.

**Comment by julealgon** [comment]
@PhoenixBlade24 I think you'll need to ask somewhere else. As you can see from all the replies above, this project here is focused on D1 and D1 and D2 are actually substantially different from each other.

Try to track down Nefarius and check with him how is the progress on MetalStorm maybe.
- https://d2mods.info/forum/viewforum.php?f=157
