### ISSUE TITLE
[Feature request] reveal item location on map at any time

### ISSUE THREAD

**Issue by twojstaryzdomu** [diasurgical/devilutionX#3569]
Eager but hasty admins: Reopening this feature request under the correct project. Don't close, allow others to view and comment by those who view development only on github and have no discords capabilities.

The FR is to allow revealing the location of items on map via an ini option. This is regardless of a spell in use and would work at any time in the game.

**Comment by qndel** [comment]
It's not for you to decide if it will be closed or not.

**Comment by AJenbo** [comment]
To clarify, you where already given a reason why this feature would not be accepted even if posted in the right repo.

https://github.com/diasurgical/devilution/issues/2264#issuecomment-974780371

> That's what hellfire's search spell does.

I can understand if this might not have been fully clear to you.

> allow others to view and comment by those who view development only on GitHub and have no discords capabilities.

Very few users comment or view on GitHub (177 vs 1007 on Discord). Discord can be run from most browsers. So not using it is probably a choice not a lack of capabilities?

Discord is one of the tools we use to coordinate development so that makes it a development tool for this project, it doesn't matter if other projects do things differently. You are welcome to suggest alternative ways to manage things. But doing so should be brought up separately from other issues and not as a meta comment.

**Comment by twojstaryzdomu** [comment]
@qndel you ought to calm down with how you approach people offering suggestions to improve the software. This is textbook abuse of a priviledge and wrecking your street cred as a project.

**Comment by twojstaryzdomu** [comment]
@AJenbo I added this is orthogonal to the spell.

**Comment by qndel** [comment]
> @qndel you ought to calm down with how you approach people offering suggestions to improve the software. This is textbook abuse of a priviledge and wrecking your street cred as a project. Threatening bans, closing without a discussion is not the way to go.

Oh believe me, I am calm, I've dealt with nutjobs like you thinking they are some "community ambassadors". Somehow other people have managed to follow our rules and contribute, seems you aren't interested in that, nobody needs your "feature requests", begone foul creature

**Comment by AJenbo** [comment]
> please don't assume

I didn't that's why it was formed as a question.
