### ISSUE TITLE
[Feature Request] add / load other MPQ

### ISSUE THREAD

**Issue by Gunnar-GO** [diasurgical/devilutionX#3631]
There are some modifications out there, like `diabger.mpq` the extracted german text and speech, that allows to play the game fully in german language. For Hellfire the same, just `hfger.mpq` . 

At the moment i couldn't find any parameter to force the load or option to load these data without modifiing the original mpq, what I'm trying to avoid.

Can an option in ini or as parameter be set to (over)load the MPQ?

**Comment by AJenbo** [comment]
I do think we should add something like this, but for your specific case we already support loading an MPQ per language. So simply set your language to `de` and rename you MPQ to `de.mpq`.
(We already have a full German translation, except for voices)

**Comment by qndel** [comment]
Supporting loading user mpqs is planned, to load german stuff, do what @AJenbo said.

**Comment by Gunnar-GO** [comment]
thanks for the hint with de.mpq ... how does it works for hellfire?

to the point "we have allready" if Bert is translated to Wirt it is discussable quality, but yes i recongnised it by updating to 1.3

**Comment by AJenbo** [comment]
> to the point "we have allready" if Bert is translated to Wirt it is discussable quality, but yes i recongnised it by updating to 1.3

Is this the case for our German translation? If so then please report the issue. You could also help out by reviewing it and send in suggestions for it. Currently the German translation has been done by just one person. You can find the up to date German translation here: https://github.com/diasurgical/devilutionX/blob/master/Translations/de.po (I recommend using [Poedit](https://poedit.net/download) for editing) translations.

> There are some modifications out there, like diabger.mpq the extracted german text

To the best of my knowledge DevilutionX is the only version that allows for text to be loaded from the MPQ files. All other clients works by hex editing the exe and modified images.

This allows for things to be easily translated in text form, and the client is multilingual instead of being hard-coded to a specific language.

> how does it works for hellfire?

This doesn't make much sens to me, I think you have some expectations that you aren't presenting.

**Comment by Gunnar-GO** [comment]
>  If so then please report the issue. 
i'm not sure if this is an error, i recognised the difference. it could be some variation in the versions. also wasn't meant to offend.

> To the best of my knowledge DevilutionX is the only version that allows for text to be loaded from the MPQ files. All other clients works by hex editing the exe and modified images.

The old modifications uses an modified exe to add the mpq to beeing loaded. It overloads the english text/speech with the extracted data from the german PlayStation version.

> > how does it works for hellfire?

> This doesn't make much sens to me, 

There is an translated mpq for hellfire also. I assume the indirect answer is, if i use these hellfire file (needed or not) i need to swap both of the files?

**Comment by AJenbo** [comment]
> The old modifications uses an modified exe to add the mpq to beeing loaded. It overloads the english text/speech with the extracted data from the german PlayStation version.

Are you sure the text wasn't injected in to the modified exe? In my experience all translation project up to this point has handled it in this fashion, and the MPQ only contains the sounds and a few images. What happens if you use the same exe but do not provide it with the accompanied MPQ file?

> I assume the indirect answer is, if i use these hellfire file (needed or not) i need to swap both of the files?

It's hard to say without knowing what the MPQ files in question actually contain. Considering that they where accompanied by a modified exe I can't really give you a proper answer with out knowing what we are dealing with.

> It overloads the english text/speech with the extracted data from the german PlayStation version.

We have tools that you can use to creating a localized Audio MPQ from your PlayStation cd.

https://github.com/diasurgical/psx-tools#creating-localized-audio-mpqs
https://github.com/diabpsx/divination

**Comment by AJenbo** [comment]
Closing this since it turned in to more of a question regarding loading lang content and adapting PS1 audio.
