### ISSUE TITLE
Update libzt from upstream

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#3700]
We currently have a few workaround in CMake files, such as having to link the shared libzt library on Android.
Ideally, we'd switch to the upstream libzt but they haven't merged all of our patches yet.

Perhaps we can rebase our stuff on the current upstream?

**Comment by glebm** [comment]
@StephenCWills libzt just merged my 2 PRs that have been open for a few months, perhaps it's worth trying to upstream the rest of our fixes at this point?

**Comment by StephenCWills** [comment]
Yeah, I think it'll be good to review the changes we've made and try to move some of that upstream. The situation is a bit crazy since we've forked some of the submodules as well, but I'll see what I can do.

https://github.com/diasurgical/ZeroTierOne
https://github.com/diasurgical/lwip
https://github.com/diasurgical/lwip-contrib
