### ISSUE TITLE
DevilutionX Android User Interface 

### ISSUE THREAD

**Issue by Connaiseur** [diasurgical/devilutionX#3887]
The user interface is barely usable for touch devices.  Anyone who disagrees with this statement is both a madman and hypocrite.  This last is not an opinion either since diablo has always aimed at being ease to control  and devilutionX on a touch device is not easy to control nor does it follow the click to move philosophy which was originally implimented in the game.  Diabloweb did not just succeed in porting the game to the web but in extending blizzard's click to move to touch devices something the Devilutionx 1.3 is terrible at.

I simply ask that you maintain blizzard's vision by implentating diabloweb UI to devilutionX.  Perhaps it is a pain to do, but it is well worth it.

**Comment by StephenCWills** [comment]
> The user interface is barely usable for touch devices. Anyone who disagrees with this statement is both a madman and hypocrite.

Sorry, but this is empirically wrong. Labeling a large number of players as madmen and hypocrites just because you don't like the controls is a really aggressive way of proposing changes.

> I simply ask that you maintain blizzard's vision by implentating diabloweb UI to devilutionX. Perhaps it is a pain to do, but it is well worth it.

If your suggestion is to implement a touch-to-move control scheme on Android, then that seems like a potentially valid issue labeled as a feature request--although, we typically prefer feature proposals to be presented in Discord these days. As-is, your issue comes across as, "The controls suck so do something about it." Can you adjust your attitude to be a significantly less abrasive, instead focusing on any constructive feedback you might have, and maybe also post it in Discord rather than GitHub?

**Comment by AJenbo** [comment]
I would also add that a suggestion like this should come from someone that intend to add this feature (something we would not reject if done right). As a suggestion it doesn't serve much purpose, since it does not adding any information and might never be picked up.
