### ISSUE TITLE
devilutionx-linux-x86_64.tar.xz 1.3.0 version lacks the devilutionx.mpq file

### ISSUE THREAD

**Issue by needless** [diasurgical/devilutionX#3937]
**Important information**
Linux 64 bit / DevilutionX version 1.3.0 / binary

**Describe**

**To Reproduce**
1. Go to Download devilutionx-linux-x86_64.tar.xz 
2. unpack devilutionx-linux-x86_64.tar.xz
3. run the binary ./devilutionx

```
 INFO: Removed file: /home/needless/.local/share/diasurgical/devilution/Diablo1ReadOnlyTest.foo
 ERROR: Missing font kerning: fonts\42-00.bin
 ERROR: Error
 Failed to open file:
 fonts\goldui.trn
 
 File not found
 ERROR: Missing font kerning: fonts\22-00.bin
 ERROR: Error
 Failed to open file:
 fonts\yellowdialog.trn
 
 File not found

```
**Expected behavior**
It should have the  devilutionx.mpq contained.

**Additional context**
The error was not obvious, I have read user reports over here not related to the linux build:
https://gbatemp.net/threads/release-devilutionx-for-3ds.552299/page-5. Extracted the missing file **devilutionx.mpq** from devilutionx-linux-x86_64.appimage and could finaly run the game without the error.

Please fix the binary package for linux 64 bit to contain the missing file. Thanks in advance.

**Comment by AJenbo** [comment]
Thanks for reporting, I can't believe no one has mentioned this up till now.

Technically it is included since it can be found in both the .rpm and .deb file:
![image](https://user-images.githubusercontent.com/204594/148827989-91e7fc29-4c6d-43bc-9ed4-1ffe6146baee.png)
But this of cause isn't obvious or user friendly.

We do also link to the file for [direct download](https://github.com/diasurgical/devilutionx-assets/releases/download/v1/devilutionx.mpq) in the install instructions. Hopefully most users where able to get it that way: https://github.com/diasurgical/devilutionX/blob/master/docs/installing.md#installing

The number of downloads of the Linux x86_64 (non-appimage) has been rather low this time around with only 586 with most seaming to prefer the appimage or various distro specific archives.

The issue reported by KILZpro3 (I guess you are pintcat?) is actually a different one, the 3DS builds now has the MPQ embedded, but would still load the external first which unfortunately causes it to load the old one if present from previous installations (this is fixed for the next release). Thanks for bring that to my attention.

Since uploading a new build will wipe the stats and we are pretty close to the next release I have instead opted for adding a line regarding the issue right above the download:

> The Linux build does not contain devilutionx.mpq which must be downloaded separately instead or it will be unable to locate fonts\yellowdialog.trn.

**Comment by needless** [comment]
Hi, no I am not pintcat. **First** time trying out your port, it is cool. Thanks for the port.

To the problem, the binary would not run out-of-the-box, it cost me some time to find out howto get this thing running with version 1.3.0

The installation docs 

https://github.com/diasurgical/devilutionX/blob/master/docs/installing.md#installing

have written:

`DevilutionX comes with devilutionx.mpq which is required to run the game properly.`

Please fix the packaging in the next release and provide the game that it can run out of the box if the binary is already there. Do not expect users to check inside various distribution specific binary formats for a required file that should be already there, since the installation is already "complex" enough with various diablo and hellfire specific files. Correct, make this user-friendly.

Thanks

**Comment by StephenCWills** [comment]
> Do not expect users to check inside various distribution specific binary formats for a required file that should be already there, since the installation is already "complex" enough with various diablo and hellfire specific files.

To be clear, there is no such expectation. This was merely a mistake that took a while to get reported. Thanks again for reporting the issue.

**Comment by AJenbo** [comment]
I think you miss understood me.

> Please fix the packaging in the next release and provide the game that it can run out of the box if the binary is already there.

The implication of us making the next release soon is that the issue is expected to be corrected then.

> Do not expect users to check inside various distribution specific binary formats for a required file that should be already there, since the installation is already "complex" enough with various diablo and hellfire specific files.

We don't. But we are human and simply doing this in our spare time, please cut us some slack.

> Not everyone is running debian or red-hat based distro. In fact, gentoo is used here, so generally .rpm and .deb archive is not interesting to look into.

We are well aware. This is why we produce pre-build binaries for 16 different platforms. Even just checking the they all work is a complicated task with multiple pitfalls.

> Correct, make this user-friendly.

Be kind, we try out best.

**Comment by qndel** [comment]
@AJenbo you know I'm the first one to bash trolls or other "do what I want or I uninstall" mudcakes but I feel that this guy here is chinese or something and the tone of the message is not indentional and is coming from english not being his first language :D

**Comment by AJenbo** [comment]
Yeah, I did think that leaving it be might have been the better option. But added the edit to clarify in case there where miscommunications. Mostly I just wanted to make sure that things where stated clearly :)
