### ISSUE TITLE
Language reverts to english after restarting the game

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#4007]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
Windows 10 / compiled master https://github.com/diasurgical/devilutionX/commit/9536927301dafd33008bef6b4d5b5131541db5bc

**Describe**
Game seems to reset to english after restart

**To Reproduce**
Set the language to something other than english (either by editing diablo.ini or using ingame menu)
Restart game
See english

**Expected behavior**

**Comment by AJenbo** [comment]
Can you check what langauge it detects for your system.

`devilutionx.exe --verbose`

**Comment by qndel** [comment]
it didn't really work but I forced it directly in the code and this was in visual studio log after I changed language ingame to russian:
```
DEBUG: Couldn't open H:\devilutionX\build\x64-Debug\assets/ru.mo
VERBOSE: Loaded MPQ file override: C:\Users\qndel\AppData\Roaming\diasurgical\devilution\ru.gmo
VERBOSE: Paths:
    base: H:\devilutionX\build\x64-Debug\
    pref: C:\Users\qndel\AppData\Roaming\diasurgical\devilution\
  config: C:\Users\qndel\AppData\Roaming\diasurgical\devilution\
  assets: H:\devilutionX\build\x64-Debug\assets/
VERBOSE: MPQ search paths:
     1. 'H:\devilutionX\build\x64-Debug\'
     2. 'C:\Users\qndel\AppData\Roaming\diasurgical\devilution\'
     3. ''
VERBOSE: Missing: ru.mpq
```

**Comment by qndel** [comment]
```
DEBUG: Couldn't open H:\DiabloHD\devilutionX\build\x64-Debug\assets/ru.mo
DEBUG: Couldn't open H:\DiabloHD\devilutionX\build\x64-Debug\assets/ru.gmo
VERBOSE: Found {"en", "en"} user preferred locales
VERBOSE: Trying to load translation: en
VERBOSE: Best match locale: en
```

**Comment by AJenbo** [comment]
I'm not sure loading the translation from AppData was intended, so now i'm wondering why it's working at all :thinking: 

At least you should be able to solve it by installing gettext so that you can build the translations.

**Comment by xGnoSiSx** [comment]
I can confirm this bug. I was trying to see other localizations for how they handle stuff, and was instantly confused.

**Comment by AJenbo** [comment]
Is it a bug or incorrectly configured build environment :thinking:

**Comment by xGnoSiSx** [comment]
The build has failed on the CI side. But thinks that it has passed.

The resultant devilutionx.MPQ does not contain any of the translation files at the root.

I just confirmed this by browsing the base 1.3 stable release MPQ with what the CI build creates now.
At the very least there should be a verification step that would check if the resultant MPQ contains the specificed resource files.

**Comment by AJenbo** [comment]
The CI build does not contain translations. This is a known result of not having the translation tools of the CI runner, so not something we need to really test for imo since it is working as expected.

**Comment by StephenCWills** [comment]
@qndel helped me figure out this issue is not completely resolved. This is another in a long line of circular dependency issues between loading MPQs, loading translations, and displaying error messages.

The game loads translations after loading devilutionx.mpq because it expects to find them there. However, in the absence of an MPQ, you could theoretically also have your translations in `--data-dir`.

The game tries to load translations before any other MPQs because error messages depend on translations. The `HasTranslation()` function uses `OpenAsset()` to find the translation, but if there's no devilutionx.mpq, there's no `paths::MpqDir()` from which to locate the translations in `--data-dir`. Also, even if there is a devilutionx.mpq that happens to be located in an alternative directory apart from `--data-dir`, the game would be searching for translations in that alternative directory so you'd have the same problem.

By the time the settings menu is available, though, the game would have loaded diabdat.mpq from `--data-dir` so the `paths::MpqDir()` function would return the location where the translation files are placed. That enables the user to select the translation from the in-game menu and see the result, but the selection reverts the next time they run the game because of the aforementioned discrepancy with `paths::MpqDir()`.

**Comment by AJenbo** [comment]
If I'm understanding the issue correct this issue is only likely to affect translators and developers. As such It's not blocking for 1.4.0, but please correct me if I'm wrong here.

**Comment by AJenbo** [comment]
Some good considerations in this PR regarding what possible solutions we could use for this:
https://github.com/diasurgical/devilutionX/pull/4096

The PR it self is closed since it goes down a path that could hurt performance.
