### ISSUE TITLE
Language setting not work on 3DS

### ISSUE THREAD

**Issue by 8ar10der** [diasurgical/devilutionX#4080]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?

Luma3DS 10.2.1-e30cd7e
New2DSLL
DevilutionX v1.3.0 release version

**Describe**
I have changed the language code in the ini file (to zh_CN). But the game still in English

**Comment by StephenCWills** [comment]
I am unable to reproduce. Setting the language code in `diablo.ini` to `zh_CN` on my o3DS console renders the menu blank because I have not installed `fonts.mpq`, but it certainly does not leave the game in English. Can you confirm that there is exactly one language code setting in your ini and that you applied the change correctly using the following information?

In `/3ds/devilutionx/diablo.ini` on the console's SD card...

```ini
[Language]
Code=zh_CN
```

**Comment by 8ar10der** [comment]
> I am unable to reproduce. Setting the language code in `diablo.ini` to `zh_CN` on my o3DS console renders the menu blank because I have not installed `fonts.mpq`, but it certainly does not leave the game in English. Can you confirm that there is exactly one language code setting in your ini and that you applied the change correctly using the following information?
> 
> In `/3ds/devilutionx/diablo.ini` on the console's SD card...
> 
> ```ini
> [Language]
> Code=zh_CN
> ```

Hi @StephenCWills 

Thanks for your info, I just double check the `diablo.ini` file. I found the language code be set back to `en` by game itself.  I changed code again and everything work well now.
