### ISSUE TITLE
Desync when killing a player with 18+ gold stacks

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#4124]
**Important information**
Windows / DevilutionX 3b3419d / compiled MSVC 2022

**Describe**
If the host of a multiplayer game kills another player with a melee attack the logic for dropping the slain players items causes the host to see only 9 stacks/items appear on the ground. The host generates the expected messages and all other players see the correct state, and if the host leaves the level then returns they also see the correct state when the level delta messages are played back.

**To Reproduce**
1. Join a game with two clients.
2. Use `give gold` on the second player or ensure they have 18 or more full stacks of gold
3. Enter the dungeon with both players
4. Have the host kill the second player with a melee attack
5. Desync is visible at this point
6. Have the host leave the level then re-enter
7. Desync is corrected

**Expected behavior**
Items to appear the same on all clients the first time.

**Screenshots**
Step 5 desync:
![2022-03-06T142103_devilutionx](https://user-images.githubusercontent.com/357684/156907887-74923a0c-a027-4bf7-a3f4-89fd08865f5c.png)

Step 7 resync:
![2022-03-06T142136_devilutionx](https://user-images.githubusercontent.com/357684/156907893-9d1133a8-126d-49cc-a836-f7b7f6c81bd7.png)
(One of the gold piles on the stairs got picked up by the warrior due to auto-gold pickup)

**Additional context**
This appears to be due to the logic that stops dropping items when the local player has an item at their feet. Dead items usually ignore the distance logic and allow dropping further away than adjacent tiles however they also shouldn't drop on a tile where a living player is standing, notice the dead player in the screenshots does not see an item at the feet of the living player.

**Comment by qndel** [comment]
@ephphatha could you check if https://github.com/diasurgical/devilutionX/pull/3489 fixes it?

**Comment by StephenCWills** [comment]
This bug appears to be the cause of ground items disappearing as described in #4491. If a player dies in a corner, up against a wall, amidst a collection of items lying on the dungeon floor, or while carrying a large amount of gold, it increases the chance that an item will drop at the player's feet and none of the subsequent items will appear on the other player's client. If the dead player leaves the dungeon level and comes back, as is often the case with `Restart in Town`, they will essentially lose their claim over the items they previously dropped and will instead have to verify with the other player whether the item exists. Since it doesn't exist on the other player's client, the dead player will fail to pick up the item and it will eventually time out.
