### ISSUE TITLE
Remove discord_game_sdk.dylib from the Mac build

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#4213]
discord_game_sdk.dylib isn't supose to be placed in the dmg file (It's actually a duplicate as it is also correctly located with in the application container).

![image](https://user-images.githubusercontent.com/204594/159197101-4a3c0d8a-5929-4d62-aaea-923554c50c53.png)

**Comment by StephenCWills** [comment]
It must be because of this.
https://github.com/diasurgical/devilutionX/blob/e29bf228fd5ecb05ff89bea8a8d7c9f31a493583/3rdParty/discord/CMakeLists.txt#L34-L36

We've established that Mac doesn't need that, but I guess Windows and Linux do? Should we be including this file in the CI artifacts for those platforms?

**Comment by AJenbo** [comment]
It should only be included for Windows builds
