### ISSUE TITLE
Cornerstone doesn't work

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4320]
I tried to use the cornerstone and the item transfer doesn't work or I'm doing something wrong.
In the sorcerer's save file there is a bow (Windforce) on the cornerstone.
In the rogue's save file, I've made my way to the cornerstone, but the Windforce isn't there.
Both files are attached. The item transfer in a single player game should work if both files are in the same folder, right?
[cornerstone.zip](https://github.com/diasurgical/devilutionX/files/8404250/cornerstone.zip)

**Comment by StephenCWills** [comment]
The Sorcerer seems to have been saved after defeating Diablo, right before the ending cutscene. I was able to slip a `changelevel 21` in before Diablo died, but I naturally didn't find Windforce on the Cornerstone since the item is stored in diablo.ini.

I did, however, test a transfer between a couple freshly created characters. The transfer went okay, but I found that after the second character retrieved the first character's item from the Cornerstone, I was also able to retrieve the item using the first character by loading game, effectively duplicating the item. So that seems to be an issue.

**Comment by StephenCWills** [comment]
I think both of the issues here could likely be explained by #3984.

@Chance4us If you ever used the Load Game option on Crypt Level 1, then the tile will become inert so you won't be able to perform the transfer. To reactivate the tile, you have to leave the level and come back. So your best bet would be to pick up the item, use Town Portal to leave and come back, then drop the bow on the tile and save. If you want to avoid the possibility of duplicating the item, it should be safe to use Town Portal again to go to town before saving your game and the item will still be saved to the INI.

FYI, I'm closing this issue since it appears to be a duplicate.

**Comment by AJenbo** [comment]
I have been considering that maybe we should move the corner stone to it's own file, borrowing logic from the stash.

**Comment by Chance4us** [comment]
> I have been considering that maybe we should move the corner stone to it's own file, borrowing logic from the stash.

I find the cornerstone logic and the issue a bit confusing, so I think the above suggestion is a pretty good idea.
