### ISSUE TITLE
Something wrong with the loot RNG?

### ISSUE THREAD

**Issue by vlolteanu** [diasurgical/devilutionX#4426]
**Important information**
Linux / head of master branch as of 11-13 April, also 1.4.0 (the latter being the official build)

**Describe**
There might be something wrong with the loot RNG, at least at higher levels.

I've replayed Diablo over the past couple of days with a lvl 39-40 character in Hell difficulty. Anecdotally, I've seen the following happen way too often:

- The same spellbook dropping over and over from libraries/skeleton tomes.
- Items of the same type with the same affixes dropping in short succession. The most extreme case was when I got 2 such axes and 2 such staves as part of the same loot haul that I vendored.
- 2 scrolls of the same type dropping from a chest.
- Griswold selling nearly duplicate premium items (same type, same affixes, slightly different stats).

FWIW, I've also had a lot of other deja-vus that I couldn't place my finger on.

**Screenshots**
This is the second time I've seen Griswold do this:

![image](https://user-images.githubusercontent.com/3142367/163294020-d2aa826f-464f-4e22-b1a0-6fece63abc32.png)

Save file attached here:
[single_0.zip](https://github.com/diasurgical/devilutionX/files/8485556/single_0.zip)

**Comment by StephenCWills** [comment]
I can't speak for the other examples you found, but the two items in the savegame have completely different seeds.

![image](https://user-images.githubusercontent.com/9203145/163303360-0cad535c-c6a7-435e-ba7e-87d1a8f3e359.png)

I also probably didn't need to do this since we have the tests, but I went ahead and generated both of these items in vanilla and got the same result. So the attached example is something of a coincidence, although I won't discount the fact that the item generation code probably has several biases.

**Comment by vlolteanu** [comment]
All the item pairs that I've mentioned (excluding books and scrolls) were never exactly the same, so yes, they all had different seeds.

**Comment by AJenbo** [comment]
i guss what you are saying is that the idx appears to have bias

**Comment by StephenCWills** [comment]
I did a deep dive of the item generation logic for these two seeds, and it turns out that this item is actually relatively likely to appear compared to other magic items. Furthermore, your assumption that this is perhaps more likely to occur at high levels may have some truth to it since Griswold's premium items cap at ilvl 30. All six of his items will always have the same ilvl once you reach clvl 31.

FYI, this is just something you may find interesting in case you encounter more duplicates like this. Suffixes are much more likely to occur on magic items than prefixes. So if two near-identical magic items have prefixes, that would constitute a much more rare occurrence.

I'm closing this issue since I couldn't find any evidence of an error in the code.

**Comment by vlolteanu** [comment]
I've given this some thought as well, and the only two ways of getting rid of the bias would be to:
 * Bias the seeds in such a way as to remove the biases in how they're used to generate the items (extremely hard to pull off)
 * Start encoding items in save files using their resulting stats, then tweak the item generation code.

Both are no-gos.
