### ISSUE TITLE
    PS4/ 1.4.0 / not working.

### ISSUE THREAD

**Issue by Brutal-sam** [diasurgical/devilutionX#4443]
![vlcsnap-2022-04-15-05h06m27s734](https://user-images.githubusercontent.com/94696121/163516623-85a6f9fd-67ad-4e0d-8794-783425a71c86.png)

PS4 / DevilutionX 1.4.0 / downloaded a release.

installed the game pkg
copied MPQ files to /data/diasurgical/devilution

game doesn't start and crashes.

**Comment by bobmin132** [comment]
Same issue. I have .MPQs in /data/diasurgical/devilution and /mnt/usb0/diasurgical/devilution just in case it was reading from USB.

**Comment by john-tornblom** [comment]
Tracked down the issue, its language-related. Workaround:

create a file `/user/data/diasurgical/devilution/diablo.ini` with the following contents:
```
[Language]
Code=en
```

**Comment by rtx92** [comment]
thank you to fix this so fast and yes now it works on my end  again thank you kind sir

**Comment by Brutal-sam** [comment]
All good, works perfectly now

**Comment by AJenbo** [comment]
If any one has an account on psxhax.com could they let this person know the solution to getting it running?

https://www.psxhax.com/threads/devilutionx-v1-4-0-diablo-hellfire-source-port-ps4-pkg-by-diasurgical.12598/

I can't register an account because of there strict email requirements:
![image](https://user-images.githubusercontent.com/204594/163856953-91a8a429-d48c-4198-a46b-4d28042e759b.png)
