### ISSUE TITLE
Bring back DirectDraw support if possible

### ISSUE THREAD

**Issue by fearedbliss** [diasurgical/devilutionX#4452]
Hey all,

[I've recently been told](https://themovingcaravan.com/viewtopic.php?p=424#p424) that DevilutionX no longer supports DirectDraw. I think there is a lot of value in still retaining a DirectDraw interface (specifically for the benefits that can be provided when using cnc-ddraw). DirectDraw may be considered Legacy Code but I think otherwise. Original D1 had this method of video communication so it would be good to continue to support this for any existing DirectDraw related projects out there that support D1. Just making this bug report to express interest and support for this to return and to put it in the record. 

Thanks,
fearedbliss

**Comment by glebm** [comment]
> for the benefits that can be provided when using cnc-ddraw

Which benefits?

**Comment by fearedbliss** [comment]
Hey @glebm,

The biggest one that comes to my mind is shader (glsl) support, but probably most of the user things you may already be covering. Other cnc-ddraw users may have other type of workflows that are provided by it that I can't think of atm.

**Comment by AJenbo** [comment]
I think @fearedbliss is refering to ddraw wrappers that overwrite the dll on Windows and pipes the output through some other API.

Short answer: We do support it but you are using the wrong tools. Open a new issue for LibRetro Shader support instead.

Long answer:
The whole reason for the existence of cnc-ddraw is to translate ddraw in to something that is better supported (GDI / OpenGL / Direct3D 9). Translating it to OpenGL gives the option of adding additional post processing in the form of shades.

Since DevilutionX already deals with the compatibility issues by replacing it with SDL, and that supports outputting to OpenGL the same results are very much possible with DevilutionX, you just don't need the legacy handling of cnc-ddraw or similar ddraw wrappers.

There are several features that would not be possible using a DirectDraw implementation. You can very much see this by building using SDL1.2 which does come with a DirectDraw backend, and would allow you to use cnc-ddraw. But then you are dependent on cnc-ddraw for modern features and comparability.

A feature comparison:
- Supports Windows XP, Vista, 7, 8, 10, 11 and Wine
  - yes
- GDI / OpenGL / Direct3D 9 renderer (With automatic renderer selection)
  - yes
- Upscaling via glsl shaders - https://imgur.com/a/kxsM1oY | https://imgur.com/a/wjrhpFV
  - yes
- Windowed Mode / Fullscreen Exclusive Mode / Borderless Mode
  - yes (though we do not expose Borderless Mode)
- Alt+Enter support to switch quickly between Fullscreen and Windowed mode
  - yes
- Automatically saves and restores window position/size/state
  - yes (not sure about position)
- FPS Limiter
  - yes
- VSync
  - yes
- Optional mouse sensitivity scaling
  - no, but shouldn't be needed since we handle thing nativly
- Screen shots as jpeg
  - We should save them as PNG now that we support PNG, it's better then jpeg for this as well
- Preliminary libretro shader support - https://github.com/libretro/glsl-shaders
  - no

Since cnc-ddraw is Windows only, and uses libretro which is cross platform. It would make a lot more sens to support libretro shaders directly rather then going about it in a round about way that would both be harder to maintain, have less features and be limited in platform support.

**Comment by fearedbliss** [comment]
Hey @AJenbo, Thanks for the clarification. Yup I agree that if you already support all of the stuff with cnc-ddraw - natively in Devilution/X, then there is no need to maintain the DirectDraw backend. This would of course go in conjunction with your statement about it being better to just support libretro directly to provide the glsl support.

I personally play mostly older games that use DirectDraw (With some exceptions of newer games of course.. and by newer I mean things like Hellgate London 2007 LOL). So in my case I still want (and need) to use cnc-ddraw, but that's outside the scope of Devilution given the clarification above.

Keep up the good work and I'm happy that over the years Devilution has grown a lot. It's come a long way since I helped test the original Devilution source code back when it was released (Remember the "[Compatibility Matrix](https://github.com/diasurgical/devilution/blob/master/docs/compatibility_matrix.md)" haha?)

**Comment by AJenbo** [comment]
Yeah it's been an exciting ride. But you have actually been associated with the project for long then I, the matrix was already set and done when I joined :)

**Comment by fearedbliss** [comment]
@AJenbo Lol yea I made the file and used Wine as the base haha. You can see the first testing commits from me for the mingw compiler haha. But I was really just there for basic motivation support honestly and just some ground work testing and documentation for @galaxyhaxz. I never wrote single line of code, that's all @galaxyhaxz, you, and the rest of the team. Amazing work :).

**Comment by AJenbo** [comment]
P.s. sorry to hear that you feel the project has strived to long from the original :(

**Comment by fearedbliss** [comment]
@AJenbo Don't mind me on that lol, you keep doing your thing, it's a great foundation for allowing developers to make modifications to Diablo 1 - in any way - which is heavily needed. I don't really want another type of The Hell / Beelzebub - Closed source / Complicated Source type of situation.
