### ISSUE TITLE
Teleport sound effect interupted when teleporting to Lazarus

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#459]
To reproduce.
1. Issue seems only to appear when using upscale=0 in diablo.ini so you have to use it first
2. Enter the circle on picture and listen to the cut sound effect
![circle](https://user-images.githubusercontent.com/45902449/68708881-ded4ad00-0594-11ea-8f38-4cab2b059af8.png)
3. Following sound will be played too short
[Lazarus.wav.zip](https://github.com/diasurgical/devilutionX/files/3838149/Lazarus.wav.zip)

**Comment by AJenbo** [comment]
This doesn't appear to be specific to running `upscale=0`, does it play normally for you if you enable upscaling?

Could you check if this is also an issue in 0.4.0, I tested all the way back to  b90ef1336d0fa23288768b420fb2cbe5356fbfdd and the sound appears to be cut off to me even then.

**Comment by Chance4us** [comment]
Tested again. Yes, It play normally if I enable upscaling. It is interrupted when upscale=0.
0.4.0 can not be tested with above 64bit save game file because of crashing on load.

**Comment by AJenbo** [comment]
> 0.4.0 can not be tested with above 64bit save game file because of crashing on load.

64bit is out of beta now that it uses the same savegame format as the original 32bit game. In short if you save game work with 0.5.0 then it works with 32bit also.

The audio is being interrupted because `Mix_CloseAudio()` is being called as the video starts:
https://github.com/diasurgical/devilutionX/blob/4532f009ff672334125d0552ca270a69ff1df8fc/SourceX/storm/storm.cpp#L542
It's not clear why this happens earlier than the original, it could simply be down to faster execution, this could also explain why there might be a difference when using `upscale` since they resize the video in different ways.

**Comment by AJenbo** [comment]
Please also check this build: https://4715-143324737-gh.circle-artifacts.com/0/devilutionx_linux_x86_64

**Comment by AJenbo** [comment]
>     1. Issue seems only to appear when using upscale=0 in diablo.ini so you have to use it first

Since your screen shot shows 60fps it indicates that you where running with upscale=1

**Comment by Chance4us** [comment]
--> Since your screen shot shows 60fps it indicates that you where running with upscale=1
Yes, because i switched the setting for testing after you asked me "does it play normally for you if you enable upscaling?"

The sound plays normally if I enable upscaling. It is interrupted when upscale=0.

The mentioned build  https://4715-143324737-gh.circle-artifacts.com/0/devilutionx_linux_x86_64 plays normally with both settings upscale=0 and upscale=1.

**Comment by Chance4us** [comment]
I agree. A faster execution when upscale=0 is indeed a possible reason.

**Comment by Chance4us** [comment]
This is the only remaining bug of #445.

**Comment by AJenbo** [comment]
Please also test 0.4.0 and 0.5.0 if you haven't

**Comment by AJenbo** [comment]
I belive this will be fully solved once fades are time based instead of frame based as that would extend the time before the movie starts.

**Comment by AJenbo** [comment]
To make things even more, complicated the original game had fads run for 32 frames at full frame rate. So the actual duration would have depended on the CPU and monitor capability... pretty much exactly what's happening now. From the looks of it, the intent was 60hz, meaning 533ms, so that will be what we will use. Some might feel this is longer then what they get with the original game but would only be because they run it on modern systems.

**Comment by Chance4us** [comment]
Very fantastic solution. But now to another question that may be related to it.
The introduced FPS brake makes the game noticeably less fluid.
When walking around the level corners the picture stutters visibly.
Is it possible to make the FPS brake optionally via diablo.ini or would that cause the same cut sound problem?

By the way, I have discovered another challenge (rendering) while playing and will report about it on the weekend.

**Comment by AJenbo** [comment]
It might be better to move the delay to after the image is presented. We should also change the logic so that render is skipped if we are behind time, in the original the game would speed up for a bit until it caught up with current time.

Feel free to experiment with the delay and see if you can find out what the issue is or how to improve it.

**Comment by glebm** [comment]
@Chance4us Does #468 solve the stuttering for you?

**Comment by Chance4us** [comment]
@glebm It's hard to judge, but it definitely feels much better.
