### ISSUE TITLE
Ears from players often get bugged

### ISSUE THREAD

**Issue by Neratibt** [diasurgical/devilutionX#4641]
**Important information**
Win7 / DevX 1,4v. / Download

**Describe**
When I kill a player around 50% of the time the ear they drop has a different name, something like "i''or just some random letters and it can't be picked up. Sometimes the ear vanishes but if I kill that player again no ear will drop. I don't know what causes that except some desynch between the two players.

(Now so you don't rush a blame me for killing new people I'm not. I'm offering items in exchange for their ear)

**To Reproduce**
1. Kill a player
2. Watch for an ear with different nametag than the player
'3. See error

**Comment by StephenCWills** [comment]
Relevant images brought over from Discord.

![image](https://user-images.githubusercontent.com/9203145/172032074-8fa7cd06-5467-4a4f-b564-44827c7ac149.png)

![image](https://user-images.githubusercontent.com/9203145/172032078-ad3d1fba-2516-4b15-895f-31291ccc316c.png)

![image](https://user-images.githubusercontent.com/9203145/172032050-13fec4ac-0628-49bc-aca3-f9478b4818f2.png)

![image](https://user-images.githubusercontent.com/9203145/172032054-da22dbb4-0960-4d03-8d3d-6dc76796e29f.png)

**Comment by StephenCWills** [comment]
I'm thinking this is probably due to translations.

![image](https://user-images.githubusercontent.com/9203145/172033015-194f9cdf-5cf1-4ef0-aee5-a387f1cc2003.png)

![image](https://user-images.githubusercontent.com/9203145/172033021-aa903e55-54c1-495a-b1e7-b4a084252b69.png)

In the case of "Oído d**e spanish**", the bold part gets copied into the name data because the "í" is a two-byte character.

![image](https://user-images.githubusercontent.com/9203145/172033790-5faeb7d9-ba27-4509-b894-02bf9b42fafe.png)

https://github.com/diasurgical/devilutionX/blob/695851666efc35cdae14a1127f3d0183d8b86009/Source/msg.cpp#L2671-L2680
