### ISSUE TITLE
Render minor glitch

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#475]
Character Parts behind the house are drawn on top of it.
At the corner of the house it leads to transparency.
[0.mkv.zip](https://github.com/diasurgical/devilutionX/files/3854228/0.mkv.zip)

**Comment by AJenbo** [comment]
This is a vanilla bug, it's caused by bad sorting as actors move up or down the tile rows, there is a hack that partially fixes this but it doesn't handle when turning corners or when the actor is very wide (like the mage staff). The hack also causes double rendering leading to wrong transparency levels. Hopefully we can one day figure out how to do propper sorting of tiles but the way tiles are build (both floor and wall in the same tile) makes this hard to solve.

https://github.com/diasurgical/devilutionX/blob/master/Source/scrollrt.cpp#L498

**Comment by Chance4us** [comment]
I apologize for spamming.
I just had the feeling that that does not occur in 0.5.0.

**Comment by AJenbo** [comment]
no worries
