### ISSUE TITLE
Ctrl+Left Click Drop from Inventory when Standing on Item

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#4763]
**Important information**
Windows 10 / 1.4.0 / Download Release

**Describe**
When standing on an item and using ctrl+left click to drop items from inventory, there are three tiles the game cannot drop the items onto (will give audio feedback there's no where to place items if all other spots are taken and item will remain in inventory). The impacted tiles appear to be (-1, -1), (0, -1), and (-1, 0) relative to character position.

**To Reproduce**
1. Have an inventory with at least 7 items.
2. Drop one of the items such that it is on the same tile as your character.
3. Ctrl + Left Click on the other items in your inventory until the issue happens.

**Expected behavior**
If there is an open tile next to your character, you should be able to ctrl + left click drop items from inventory.

**Screenshots**
The described tiles in screenshot are empty, but cannot ctrl + left click drop items anymore.
![image](https://user-images.githubusercontent.com/28605404/174653610-59ca71b5-403f-4a4c-86b3-3b88dd1dff69.png)

**Comment by ephphatha** [comment]
This is due to the buggy logic in [TryDropItems](https://github.com/diasurgical/devilutionX/blob/127c6bc9e1b395982ce953cbfca3e8dca05ca949/Source/controls/plrctrls.cpp#L1808-L1847). 1.4.0 release tries to drop [to the southeast then to the southwest](https://github.com/diasurgical/devilutionX/blob/e5e446e25860ee522779cefc5f2605a17c89885b/Source/controls/plrctrls.cpp#L1872-L1877), master changed that to drop relative to the cursor then on the opposite side of the player. Because the inventory is on the right/bottom side of the screen items are dropped to the southeast then the northwest.
![image](https://user-images.githubusercontent.com/357684/174688406-11c898cc-a5a2-4901-acf3-41a5665ab687.png)

Similar to #3315, ctrl+click uses TryDropItem and CanPut to test whether an item can be dropped which causes early failures when you're standing on an item.

**Comment by qndel** [comment]
I think https://github.com/diasurgical/devilutionX/pull/3489 had no problems like these but good luck rebasing at this point lol
