### ISSUE TITLE
Make AnimationInfo smaller

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#4849]
`sizeof(AnimationInfo)` is currently 64 bytes, this is ~27% of the size of the `Monster` struct (after the optimizations in #4824).

@obligaron Can you please look into making it smaller?

One place to watch out for is this:

https://github.com/diasurgical/devilutionX/blob/ad7ca97ae1d6c0c23116f3960240e0501f9ce29a/Source/player.cpp#L1389

**Comment by AJenbo** [comment]
My god! We would only be able to fit 1000 of them on my first computer :thinking:

**Comment by glebm** [comment]
Mine too :D Commodore 64?

**Comment by AJenbo** [comment]
Yeah :) My memory leads me to think it must have been a C64G variant. And a 1541-II disk drive i belive, it guess that makes a lot of sens both came out around the same time. I do remember very clearly getting the 1530 cases drive for my birthday, it was used and had a snowman sticker on it, damn was that exciting to hook up :D

**Comment by obligaron** [comment]
Replacing all int's with int8_t changes `AnimationInfo` this from 64 byte to 48 bytes (x64).
I think this is possible. The linked code can be addressed otherwise and isn't stored in the save file.

Half of `AnimationInfo` would then be used by `std::optional<CelSprite>` (24 bytes).
Another thing could be in-lining the `std::optional` and the bool (`CelSprite` without `std::optional` has a size of 16 byte).
This could remove padding.

We could then combine the bool's (for `CelSprite` and `IsPetrified`) in a flag to get even more size (perhaps).
Or we could leave this to the compiler 😉 

Any thoughts how far we should go?

**Comment by glebm** [comment]
All of the above would be great!
We're close to being able to run on ~30 MiB RAM platforms and every KiB helps at this point!

**Comment by glebm** [comment]
I've inlined the optionals in #4858 -- there is no need for a bool because we can use `data_ptr_ == nullptr`.

**Comment by glebm** [comment]
@obligaron Can we also replace the floats with 16-bit fixed points like we do elsewhere?

**Comment by obligaron** [comment]
I think this should be possible.
We don't need a really large flexible range of values.
