### ISSUE TITLE
Unable to load saved game where animation counter has overflowed

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#4871]
**Important information**
Win 11 / DevilutionX since https://github.com/diasurgical/devilutionX/commit/a6132a1aa81bf3ef36d05602465195b24556ce9c / compiled

**Describe**
Loading a save where the ticksPerAnimationFrame value have exceeded the limits of int8_t triggers an assert and crashes the game.

**To Reproduce**
1. Try to load the attached save (has a monster with 314 ticks on the current frame, > int8_t::max)
[single_1.zip](https://github.com/diasurgical/devilutionX/files/9034919/single_1.zip)

**Expected behavior**
The game loads

**Additional context**
fails at https://github.com/diasurgical/devilutionX/blob/17f8cdddc4d2ae9aa53b6c345be4203c39785c3f/Source/loadsave.cpp#L597

Perhaps this should truncate instead of crashing in this context?

**Comment by aetn23** [comment]
I have read the code a little and I think that in this particular case removing the assert should work without breaking things. It will simply fallback to either min or max value available (because of clamp and arguments it gets in this function). In case of `TickCounterOfCurrentFrame` it will simply set a counter towards next frame of animation to max.

I wonder how it is even possible to have a save with monster with `TickCounterOfCurrentFrame = 314`? The type of this variable is int8_t, so it can't hold that big of a value. I think something can go south while saving, resulting in a monster having a variable with value that should be impossible. 

I tried reading saving/loading code and discovered that while saving the game `TickCounterOfCurrentFrame` is saved as as int32_t. I don't know if this is intentional or not (int8_t being saved as int32_t, then read as int8_t). Maybe this 314 is a result of some operations done while saving? 

Finally, I changed saving the `TickCounterOfCurrentFrame` to int8_t and after changing the loading similarly, I successfully managed to save and load, without any issues at first glance (of course first I have to do the saving, then save, then change loading, then load). This confuses me further regarding previous paragraph.

**Comment by glebm** [comment]
The type used to be `int` a few commits ago, the save is probably from before it was changed to `int8_t`

**Comment by AJenbo** [comment]
> I tried reading saving/loading code and discovered that while saving the game TickCounterOfCurrentFrame is saved as as int32_t. I don't know if this is intentional or not (int8_t being saved as int32_t, then read as int8_t). Maybe this 314 is a result of some operations done while saving?

The on disk format follows how things where original done in Diablo 1.09. We have cleaned up the runtime and do the conversion when loading and saving.

**Comment by aetn23** [comment]
Thanks for clarification. I checked the last commit (d4638f2), before changing `tickCounterOfCurrentFrame` to `int8_t` was merged. Save loads no problems. So changing the type of this variable, flips the assert in some saves.

**Comment by AJenbo** [comment]
I would like to also merge https://github.com/diasurgical/devilutionX/pull/4893 first

**Comment by ephphatha** [comment]
Both issues have now been merged :D
