### ISSUE TITLE
Gamma lowers while moving

### ISSUE THREAD

**Issue by Xyvyrianeth** [diasurgical/devilutionX#5005]
### Operating System

Windows x64

### DevilutionX version

1.4.0 (latest release)

### Describe

While moving, the gamma value dips a noticeable amount and makes it hard to see things while in motion, but goes back to normal once movement stops. I don't remember it doing this in vanilla.

### To Reproduce

1. be not moving
2. start moving

**Comment by AJenbo** [comment]
This sounds more like an issue with monitor ghosting, there is no way for the game to adjust gamma in the way you describe.

**Comment by julealgon** [comment]
I assume DevilutionX exacerbates LCD's overall terrible motion resolution because of the jump from 20fps to 60fps. Frame persistence is now 3 times lower which will for sure make it overall blurrier in any LCD.

If you could do any form of black-frame-insertion or backlight strobing this would be mitigated, or just go back to 20fps 🤣
