### ISSUE TITLE
[Xbox One] Inability to use ZeroTier for MP on Xbox One 

### ISSUE THREAD

**Issue by GrowPurps** [diasurgical/devilutionX#5019]
Xbox One version of DevilutionX doesn't allow for multiplayer through ZeroTier - game-list does not load and attempting to create a game gives an "Unknown Network Error" alert.

**Comment by AJenbo** [comment]
This appears to be Xbox firewall blocking the port

**Comment by StephenCWills** [comment]
There is no such firewall. ZT is using Win32 APIs to create the configuration directory, which isn't supported in UWP.

**Comment by StephenCWills** [comment]
I was wrong about the Win32 APIs, actually. The issue is in how the logic works for determining whether home path creation fails.

https://github.com/diasurgical/libzt/blob/37a2efb0b925df632299ef07dc78c0af5f6b4756/src/NodeService.cpp#L209-L231

If we assume a path like `C:\Users\swills\AppData\Local\Packages\b6830ff4-1ef5-4907-9d9e-1ba808edf70f_m56w1bqpxttt2\LocalState\diasurgical\devilution\zerotier` and unroll the loop, it's effectively doing something like this.

```c++
OSUtils::mkdir("C:");
OSUtils::mkdir("C:\\Users");
OSUtils::mkdir("C:\\Users\\swills");
OSUtils::mkdir("C:\\Users\\swills\\AppData");
OSUtils::mkdir("C:\\Users\\swills\\AppData\\Local");
OSUtils::mkdir("C:\\Users\\swills\\AppData\\Local\\Packages");
OSUtils::mkdir("C:\\Users\\swills\\AppData\\Local\\Packages\\b6830ff4-1ef5-4907-9d9e-1ba808edf70f_m56w1bqpxttt2");
OSUtils::mkdir("C:\\Users\\swills\\AppData\\Local\\Packages\\b6830ff4-1ef5-4907-9d9e-1ba808edf70f_m56w1bqpxttt2\\LocalState");
OSUtils::mkdir("C:\\Users\\swills\\AppData\\Local\\Packages\\b6830ff4-1ef5-4907-9d9e-1ba808edf70f_m56w1bqpxttt2\\LocalState\\diasurgical");
OSUtils::mkdir("C:\\Users\\swills\\AppData\\Local\\Packages\\b6830ff4-1ef5-4907-9d9e-1ba808edf70f_m56w1bqpxttt2\\LocalState\\diasurgical\\devilution");
OSUtils::mkdir("C:\\Users\\swills\\AppData\\Local\\Packages\\b6830ff4-1ef5-4907-9d9e-1ba808edf70f_m56w1bqpxttt2\\LocalState\\diasurgical\\devilution\\zerotier");
```

Each one of those calls is checking for the existence of a directory at that path and then attempting to create the directory if it doesn't exist.

```c++
static inline bool mkdir(const char *path)
{
    if (::PathIsDirectoryA(path))
        return true;
    return (::CreateDirectoryA(path,NULL) == TRUE);
}
```

The problem is that the UWP app is sandboxed such that it doesn't have access to any of those paths until you reach `C:\Users\swills\AppData\Local\Packages\b6830ff4-1ef5-4907-9d9e-1ba808edf70f_m56w1bqpxttt2\LocalState`. Essentially, the first seven calls to `OSUtils::mkdir()` are going to fail, but the eighth one will succeed. However, the logic assumes that if `OSUtils::mkdir()` fails on the parent directory, there's no way it could possibly succeed on any of the child directories so the whole loop bails on the first iteration.

After making a change to this logic, I was able to create and join games on ZeroTier using the UWP build. I haven't tested on Xbox, but it should probably work. It's late so I'll submit a PR tomorrow.

**Comment by AJenbo** [comment]
Yestaday I discovered that the Xbox One at the office has been removed. I'll see if I can track it down :D

**Comment by StephenCWills** [comment]
Here is the fix I came up with.
https://github.com/diasurgical/libzt/pull/9

And a CI build from my fork for testing. Don't mind the version number, it seems I don't have the latest tags.
https://github.com/StephenCWills/devilutionX/actions/runs/2929812677

**Comment by StephenCWills** [comment]
I submitted a draft PR for this so here's a test build with the correct version number. Also, I'm turning GitHub Actions off again on my fork, so the previous link is gonna be broken.
https://github.com/diasurgical/devilutionX/actions/runs/2930969873
