### ISSUE TITLE
Pause menu text doesn't use all-caps lettering

### ISSUE THREAD

**Issue by OpenRift412** [diasurgical/devilutionX#5129]
Just something I noticed today while I was playing is that the pause menu text doesn't use all-caps lettering like the vanilla game does. Not a super big deal, but just thought I'd mention.

Vanilla D1:
![D1pause](https://user-images.githubusercontent.com/29780788/180926104-a9229392-9770-4d19-80b1-e89e1c554600.png)

DevilutionX:
![image](https://user-images.githubusercontent.com/29780788/180926267-35e61204-da66-43b1-a5e4-0c614abeaabe.png)

**Comment by StephenCWills** [comment]
It's actually not all caps in vanilla.
https://github.com/diasurgical/devilution/blob/b86b8fd7c4966385e3a7dbcb29e6d7e05bdab95e/Source/gamemenu.cpp#L18-L27

The original font doesn't differentiate between uppercase and lowercase letters.

**Comment by OpenRift412** [comment]
> It's actually not all caps in vanilla. https://github.com/diasurgical/devilution/blob/b86b8fd7c4966385e3a7dbcb29e6d7e05bdab95e/Source/gamemenu.cpp#L18-L27
> 
> The original font doesn't differentiate between uppercase and lowercase letters.

Well if that's the case, then I suppose it's just that all the letters are supposed to be the same size in the pause menu then?

**Comment by StephenCWills** [comment]
That's how they are in vanilla, but I think it's a bit of a stretch to say that's how they're supposed to be.

**Comment by AJenbo** [comment]
It looks more like a limitation of the font. Despite using ISO-8859-1 for it's text encoding Æ was simply rendered as A. If it was intentional it would also have made more sens for them to have written as such rather then having to remap the text via a look up table at render time.

Most likely the ingame fonts where finalized much earlier then the ones used in the main menu (where lower case is included). You can somewhat see the effect of this by creating a character name with mixed cases and then comparing to how it looks ingame.
