### ISSUE TITLE
Miyoo Mini version ignore Language Code in diablio.ini

### ISSUE THREAD

**Issue by dem1980** [diasurgical/devilutionX#5135]
### Operating System

Other (please specify)

### DevilutionX version

1.4.0

### Describe

In version 1.4.0 (last build) for MiniUI or OnionOS, when we change the language in options, the game remains in english.
When i edit manually the file dialio.ini to replace code=en to code=fr (or code=de or code=es), the game display "english" in option.
I guess that the build force english at start and ignore the setting in diablio.ini ?

### To Reproduce

Go to the settings and change the language to anything than english.
Return to the main menu.
=> the diablo.ini contains the good value : 
```
[Language]
Code=fr
```
If i start a new game from the menu, the game is in english.
If i quit the application/game/main menu by closing the application, when i restart, in the language menu, english is selected.

**Comment by AJenbo** [comment]
Miyoo Mini does not have a 1.4.0 release, in fact it won't have any releases before 1.5.0. So this must be a self build version.

>  I guess that the build force english at start and ignore the setting in diablio.ini ?

Since it's self build I'm going to assume you simply is that you didn't build the translation files. Meaning that the game will fall back to English.

Please see the build instructions for how to build the translation files: https://github.com/diasurgical/devilutionX/blob/master/docs/building.md

**Comment by AJenbo** [comment]
I took at look at the content of devilutionx-onion-os.zip and it indeed is lacking the translation files. You can either ask him to add them. Or build them your self, or extract them from an official release, ad add them to the assets.

**Comment by dem1980** [comment]
Well done !
I took the content of the folder assets (*.gmo) from the official 1.4.1 build and i put it into Brocky's build and it works !
Thank you
