### ISSUE TITLE
Too many cows in town

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5170]
For some reason there are too many cows in town.
![cows](https://user-images.githubusercontent.com/45902449/182123846-2fa3086b-efa4-4491-9271-ae3dabd38592.png)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/9232874/single_0.hsv.zip)

**Comment by ephphatha** [comment]
Introduced by https://github.com/diasurgical/devilutionX/commit/c5ce29106ee903286e2f882a374013f2d6817671

Cows use negative indexes because they're multi-tile sprites, and prior to this commit the render code only tried to draw them when it reached the southernmost tile. It now gets called on all tiles and doesn't handle negative indexes properly.
