### ISSUE TITLE
Hidden Shrines refresh after going to town/different dlvl

### ISSUE THREAD

**Issue by Neratibt** [diasurgical/devilutionX#5230]
So I've been testing the new master and the bug is from there. I think it also works with all shrines that does not have the effect of the lion head coming from the shrine upon usage.

**Comment by qndel** [comment]
Follow the template

**Comment by AJenbo** [comment]
To elaborate I don't understand what the bug is supposed to be other then "Hidden Shrines refresh" the description appears to only be about where it happens, and I don't know what "refresh" is supposed to imply.

I'm not sure what this is comparing master to when saying "I've been testing the new master and the bug is from there", is it the PVP mode branch or something else?

>  it also works with all shrines that does not have the effect of the lion head coming from the shrine upon usage

This is applied randomly and only affects the animation, so unless this is about some animation issue when using shrines I don't see it being related.

**Comment by qndel** [comment]
This is implying we'll put exactly as much effort into fixing it as much has been put into the issue (none).
