### ISSUE TITLE
Broken level (Leorics tomb)

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5299]
### Operating System

Linux x64

### DevilutionX version

1.4.1 (latest release)

### Describe

Started a new game on nightmare difficulty.
Played to level 3 and saw something like this.
![leoric](https://user-images.githubusercontent.com/45902449/187065694-6388919c-e675-4a64-a787-c7c4e2b4f95e.png)

I can't judge if it's a vanilla bug, for example a broken seed or something similar.
A vanilla bug would of course be better, otherwise there might be an undesirable issue in our beautiful level generation code.

### To Reproduce

Rare issue. Unclear whether reproducible.

### Expected Behavior

No broken level

### Additional context

Savegame:
[leoric.zip](https://github.com/diasurgical/devilutionX/files/9439350/leoric.zip)

EDIT: When walking around the tomb there is a "mirroring effect".

**Comment by FitzRoyX** [comment]
This looks like it could be the same bug as what I reported recently with dlvl mutation in hellfire.

**Comment by Chance4us** [comment]
> This looks like it could be the same bug as what I reported recently with dlvl mutation in hellfire.

It looks like a very bad thing, is there any way to isolate the issue?

**Comment by AJenbo** [comment]
Issues introduced here: 6ec782fb7a9228a0fea726244d09a70270305682

**Comment by FitzRoyX** [comment]
Is it like the quest structure has no place to go because the 4-pillar theme is getting placed first?

**Comment by AJenbo** [comment]
Close, the issue was that I originally assumed that a level must have 2 chambers. We fixed that for the general level layout. The test case didn't have a quest piece and I missed fixing the same assumption later in the code where it picks between the available rooms.

In short because chamber 1 is missing, it assumes it should pick between 2 and 3.

![image](https://user-images.githubusercontent.com/204594/187565295-4d4b8343-7904-4ec9-9deb-063004099f59.png)
