### ISSUE TITLE
Update README for Linux x86

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#530]
The Linux build's How to install: section lists
"libsdl2 libsdl2-mixer libsdl2-ttf"
But the build is using SDL2

**Comment by AJenbo** [comment]
Is this the line you are referring to (Debian build dependencies)?
`sudo apt-get install cmake g++ libsdl2-mixer-dev libsdl2-ttf-dev libsodium-dev`

You said that it contains `libsdl2` but is using `SDL2`, I'm guessing you meant to say that it only refers to `libsdl2-mixer-dev libsdl2-ttf-dev` and not `libsdl2` (which is the case).

`libsdl2` is left out since it's a dependency of both `libsdl2-mixer` and `libsdl2-ttf`, and so will automatically be installed. The same is true for the debug run-time dependencies which are also not mentioned.

**Comment by predator8bit** [comment]
The released binary package is the one I'm referring to.

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/blob/master/Packaging/nix/README.txt#L9

Ok, well then i'm really not sure what you point is since libsdl2 == SDL2?

**Comment by predator8bit** [comment]
I'm sorry, I totally read libsdl12 and didn't even realize it.

**Comment by AJenbo** [comment]
No worries, we had a another bug report complaning that SD**1**2 didn't exist :)
