### ISSUE TITLE
Location of the golden elixir often ends at the hellgate circle

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5383]
### Operating System

Linux x64

### DevilutionX version

Custom build (commit 7ad5a4590508b8388312f0454516a7c294c91cec)

### Describe

The location of the golden elixir often ends at the hellgate circle.
I've noticed that very often before, but I can't tell if it's a vanilla issue.

### To Reproduce

Play and check very often.

### Expected Behavior

It would be desirable if the position would be more random.

### Additional context

Savergame:
[golden_elixir.zip](https://github.com/diasurgical/devilutionX/files/9690863/golden_elixir.zip)

Looks like following:
![golden_elixir](https://user-images.githubusercontent.com/45902449/193421493-c8e0eae2-215d-4fd3-8e67-fa3286b5fa95.png)

**Comment by StephenCWills** [comment]
Interesting, it seems to be somewhat intentional.

https://github.com/diasurgical/devilutionX/blob/4015dc186a27d27ebc8f385acc2424fed6b73802/Source/quests.cpp#L652

https://github.com/diasurgical/devilutionX/blob/4015dc186a27d27ebc8f385acc2424fed6b73802/Source/items.cpp#L3253-L3274

The selected position is, in fact, completely random. However, a `randarea` of 5 means that it's looking for a 5x5 area with no obstructions so it can place the elixir at the top of it.

![image](https://user-images.githubusercontent.com/9203145/193425522-f405a7cd-0164-4a2d-8470-307674340494.png)

Presumably, this is done to prevent the item spawning too close to a wall or fixture that would cover it up. You can see from the size of the area in the screenshot that the pentagram clears almost exactly that amount of space. Therefore, certain spaces around the pentagram will basically always meet this criteria.
