### ISSUE TITLE
Compilating to arm*, aarch64 and *musl in Linux

### ISSUE THREAD

**Issue by bugcrazy** [diasurgical/devilutionX#5402]
I was able to compile on Void Linux, using the FindSDL2.cmake file present in the devilution version 1.2.1 and disabling libzt with  "-DDISABLE_ZERO_TIER=ON", here link of PR on Void Linux: https://github.com/void-linux/void-packages/pull/34039/commits/72f2af7ce43ba5251fe4267dbd04c2ca57b26b4c

OpenSuse compiles with this patch in CMakeLists.txt: https://build.opensuse.org/package/view_file/games/devilutionx/aarch64-fix-detection.patch?expand=1

https://patch-diff.githubusercontent.com/raw/zerotier/libzt/pull/179.patch#/aarch64-fix-detection.patch

I hope this information will help to add support these architectures!

**Comment by StephenCWills** [comment]
For Void Linux, rather than porting an old `Find*.cmake` script that we explicitly removed from the project, it would be more helpful to know why the build system is unable to find SDL2.

For OpenSuse, I'm guessing that `CMAKE_SYSTEM_PROCESSOR` must be set to either `arm64` or `aarch64`, in which case the patch adds the `-march=armv8-a+crypto` compiler flag via CMake's `add_definitions()`. This is a very well known issue that has been addressed multiple times across many different issues here at DevilutionX, but it's really more of a libzt issue than a DevilutionX one so I recommend bringing it up with the maintainer of libzt. https://github.com/zerotier/libzt/pull/179

Lastly, I'm going to close this issue because there is no clear action to be taken on the part of the DevilutionX project maintainers. If you are having an issue with the Void Linux build that you would like us to address, please open a separate issue specifically for that with more details about the issue.

**Comment by bugcrazy** [comment]
The SDL2 error is this below, you can not find libsdl2main.a, so I use FindSDL2.cmake.  The architecture folder is not found when it is cross compile.

`devilutionX-1.4.1_1: running do_build ...
ninja: error: '/usr/lib64/libSDL2main.a', needed by 'devilutionx', missing and no known rule to make it`

`CMake Error in build/_deps/sdl_audiolib-src/CMakeLists.txt:
  Imported target "SDL2::SDL2" includes non-existent path

    "/usr/include/SDL2"

The DevilutionX version of Zerotier has differences from the original version.

Thanks, I'm going to talk to Zerotier patch creator.

**Comment by StephenCWills** [comment]
> The DevilutionX version of Zerotier has differences from the original version.

We did indeed make a few of the changes that were necessary to build for the platforms we support. In fact, you might be interested to know we introduced a fix for Android arm64-v8a to fix the very same OpenSuse/aarch64(?) issue you likely encountered (but didn't share). This fixed was submitted to libzt upstream and they merged it. https://github.com/zerotier/libzt/pull/164

There are two other things you might want to note about our Android arm64-v8a change as compared to the referenced patch. The first is that ours specifically targets an issue we were having with the build on that one platform and limits the scope of the change to only that platform, thereby ensuring that all other platforms remain unaffected. The second is that it also limits the scope of the compiler flag specifically to the target that needs it rather than adding it globally to all CMake targets through the use of `add_definitions()`. This type of change is much easier for a maintainer to accept when they likely don't have a test environment to verify the changes for all the affected platforms. That goes for libzt and also for us.

**Comment by bugcrazy** [comment]
> > The DevilutionX version of Zerotier has differences from the original version.
> 
> We did indeed make a few of the changes that were necessary to build for the platforms we support. In fact, you might be interested to know we introduced a fix for Android arm64-v8a to fix the very same OpenSuse/aarch64(?) issue you likely encountered (but didn't share). This fix was submitted to libzt upstream and they merged it. [zerotier/libzt#164](https://github.com/zerotier/libzt/pull/164)
> 
> There are two other things you might want to note about our Android arm64-v8a change as compared to the referenced patch. The first is that ours specifically targets an issue we were having with the build on that one platform and limits the scope of the change to only that platform, thereby ensuring that all other platforms remain unaffected. The second is that it also limits the scope of the compiler flag specifically to the target that needs it rather than adding it globally to all CMake targets through the use of `add_definitions()`. This type of change is much easier for a maintainer to accept when they likely don't have a test environment to verify the changes for all the affected platforms. That goes for libzt and also for us.

This is the point, portability for several architectures.

**Comment by StephenCWills** [comment]
> This is the point, portability for several architectures.

That is so far from the point, actually. libzt#179 says it fixes libzt#178 which is an issue that only affects 64-bit ARM architectures. However, as I previously mentioned, libzt#178 can be fixed merely by adding `-march=armv8-a+crypto` to the `zto_pic` and/or `zto_obj` targets. So can you explain to me what compatibility issues were on the `amd64` platform that require `-msse -msse2` to be added globally to `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS`? Honestly, if I were the maintainer of libzt, I would never merge that PR without more info.

I'm actually quite done talking about this. I've explained it so many times in so many different ways across so many different issues that I simply don't want to deal with it anymore, and nothing good appears to be coming out of this discussion so I'm locking the conversation.

**Comment by AJenbo** [comment]
> This is the point, portability for several architectures.

Your suggestions here are workarounds for misconfigurations of some distros. We already support ARM, ARM64 and AMD64 on various linux systems where things are setup correctly.
