### ISSUE TITLE
Noticeable change of pillars / gameplay

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5428]
### Operating System

Linux x64

### DevilutionX version

Custom build (016a06b99b6506b77c15f63b759959e6f271134d)

### Describe

After the fix of incorrect SOLData for L1 arched/pillar Pieces in commit 496689bb87a448c8b9b62f76f10861d459680f9b,
the gameplay has changed as following.

![pillars](https://user-images.githubusercontent.com/45902449/197357163-c19f54cf-0288-4abd-8055-0549af851340.gif)

As you can see, the hero is in a certain position.
The behavior before the above commit is that the hero sees all the skeletons and can hit and kill those in the last row.
In addition, projectiles can fly through the pillars.

The new solution is different from vanilla and cannot be called a bug.
But it represents a change that I didn't want to withhold from you.
It is now up to you whether the change will be preserved.

### To Reproduce

Load attached game and see the difference.
Also note that your projectiles can no longer fly though the pillars.

![pillars](https://user-images.githubusercontent.com/45902449/197357662-f04603e7-0a9d-48c0-a468-4a36da75b048.png)

Savegame:
[position.zip](https://github.com/diasurgical/devilutionX/files/9845086/position.zip)

### Expected Behavior

you decide :grin:

**Comment by obligaron** [comment]
The changed behavior was also [mentioned](https://github.com/diasurgical/devilutionX/pull/5264#issuecomment-1221613575) in #5264.
I was unsure if we should go this route. But also in vanilla some of this pillar pieces are blocking view and some not. 😕 
That's why we decided to be consequent (block vision and missiles) and with it fix some bugs (for example #1690).

How do you like these changes? Do they feel bad or uncommon or good?

**Comment by Chance4us** [comment]
The change is totally fine.
It's just different and we can keep it that way.
