### ISSUE TITLE
Chromebook not recognizing bluetooth xbox controller

### ISSUE THREAD

**Issue by jason-mehmel** [diasurgical/devilutionX#5815]
### Operating System

Other (please specify)

### DevilutionX version

1.4.1 (latest release)

### Describe

Running modern Chromebook, downloaded devilutionX through the Play store. Game runs, but the xbox controller functionality doesn't.

Controller functionality works on Pixel 4, also recently installed!

### To Reproduce

1. Go to Play Store,
2. Install devilutionX on Chromebook
3. Load Diablo files into the appropriate folder
4. Connect xbox controller via bluetooth
5. Load game
6. No response from devilutionX to the controller

### Expected Behavior

The same behavior as on android; either the controller working or the on screen controls.

### Additional context

I'm not sure about the xbox controller functionality with the chromebook in general. Researching that now!

**Comment by AJenbo** [comment]
Unfortunately I don't think there is much we can do here. You could try to report the issue with [libsdl](https://github.com/libsdl-org/SDL) since that is what handles the input.

But I would guess that the issue is that the Chromebook isn't forwarding the controller to the Android emulator. 

Another option would be to install the Linux version of DevilutionX since that would have native access to things (from my understanding)
