### ISSUE TITLE
Flamedart bug

### ISSUE THREAD

**Issue by ghost** [diasurgical/devilutionX#5839]
### Operating System

Other (please specify)

### DevilutionX version

1.4.1 (latest release)

### Describe

This is a bug in every version of Diablo 1 that i'm aware of.

[It is fairly well known.](https://diablo.fandom.com/wiki/Flame_Dart)
> Though this weapon lists the fire damage twice, only one 1-6 Fire Damage is checked per shot.

For some reason i cannot upload a character with flamedart?

![Flamedart bug](https://user-images.githubusercontent.com/53155671/221513886-a390ad96-0a75-485b-b8b5-a36646f9b20f.png)

[multi_3.zip](https://github.com/diasurgical/devilutionX/files/10838379/multi_3.zip)

### To Reproduce

Simply take a look at flamedarts description.

### Expected Behavior

Only list the fire damage once.

**Comment by AJenbo** [comment]
> For some reason i cannot upload a character with flamedart?

attatch it in a zip file

**Comment by StephenCWills** [comment]
Flamedart has both `IPL_FIRE_ARROWS` and `IPL_FIREDAM`, granting it both melee and ranged fire damage. The game is simply displaying the description for each item power, same as any other item. Apparently, the fact that this bow grants melee fire damage, is relevant for breaking barrels. See #2088

On Discord, @kphoenix137 suggested that we could simply modify `IPL_FIRE_ARROWS` so that it would also set the flag for `IPL_FIREDAM`. Then bows would consistently trigger fire damage even when breaking barrels, and we could remove `IPL_FIREDAM` from this bow. I personally think this would be a great solution.

**Comment by DakkJaniels** [comment]
But then all bows with fire damage would be OP at breaking barrels 🙂

**Comment by FitzRoyX** [comment]
Evidence that it's a mistake.
(a) It would be an easy mistake because two fire powers exist
(b) easy to miss during testing because you'd have to find the bow
(c) no other bow has it
(d) nobody would read that and understand the barrel mechanic, especially when you are still shooting arrows to break the barrel and not hitting it with the bow.
