### ISSUE TITLE
How to dupe in DevilutionX

### ISSUE THREAD

**Issue by D1-Constantine** [diasurgical/devilutionX#5847]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

So a guy shared me a way how to dupe in DevX and no , it's not via save files. It requires two people , player A and player B.

Player A and player B joins a game, then they drop the items they want to dupe on the ground. After that player A stops his internet connection. Since player A won't be kicked out of the room essentially both player A and B are in two different games , yet they are the same. After that all they just have to pick the items from the ground.

Strangely if you drop the duplicated items on the ground they won't register as dupes and you can pick them one by one, but you can't have both in your inventory at the same time. 

### To Reproduce

1) Run DevilutionX twice.
2) Join a multiplayer game with two different characters.
3) Drop items on the ground that you want to dupe.
4) Stop your internet connection.
5) Pick the items from the ground with both characters.
6) Profit.

### Expected Behavior

Duping 

### Additional context

I don't really know if this issue can be fixed or even if there is need to be fixed since you can easily dupe via save files, but still I wanted to share this way of duping so maybe counter measures can be made.

**Comment by kphoenix137** [comment]
> I doubt there is anything that can be done about this, plus, as you noted, you can just reload save files to easily dupe.

Rather than games splitting, wouldn't it be ideal that only one person will remain in the same game, and all the rest of the players would be dropped from the game? Vanilla would never allow the same game to continue running on more than one client IIRC

**Comment by DakkJaniels** [comment]
> Rather than games splitting, wouldn't it be ideal that only one person will remain in the same game, and all the rest of the players would be dropped from the game? Vanilla would never allow the same game to continue running on more than one client IIRC

How do you decide, in a peer to peer game, who is the person that dropped and who is the person that stayed?

**Comment by StephenCWills** [comment]
This is not an issue. We changed it intentionally. #4210

**Comment by AJenbo** [comment]
There are other ways of duping which are fare simpler. As a pear to beer game with local data running on unrestricted platforms there are no feasible ways to fully prevent data manipulation of this nature.

> Strangely if you drop the duplicated items on the ground they won't register as dupes

The original way of doing this was poorly implemented (since it would only detect items when on ground and on the same level), but also would at times cause false duplicates and delete items that where not even the same, let alone duplicates. So this check isn't being made any longer.

If we are to have anti cheat logic it should at least be robust.

> ### Expected Behavior
> 
> Duping

On a side note saying that this is the expected behavior means that you think the correct result is for duping to happen
