### ISSUE TITLE
Items that have been already initialized do not change their names when you change the language

### ISSUE THREAD

**Issue by lkk7** [diasurgical/devilutionX#5891]
### Operating System

Any

### DevilutionX version

1.4.1 (latest release)

### Describe

Items that have been already initialized do not change their names when you change the language.

Proposed fix:
1. Always initialize item names with their base name in English and keep it that way forever
2. Translate the string whenever it is meant to be shown.
3. (Worst step) Take care of edge cases – magic item generation, spellbooks, GetStaffPower, GetItemPower, and other places.

### To Reproduce

1. Start a game in a random language. Your items are initialized.
2. Restart Diablo and change the language back to English.
3. Load the game with the same character. Notice that the items are still in the initial language.

### Expected Behavior

The names should change smoothly between languages

### Additional context
Item initialized when playing in Greek retains the name after restarting the game in English, but correctly shows the further description:
<img width="749" alt="1" src="https://user-images.githubusercontent.com/14022447/225790369-48093b23-3422-4e4a-ac63-08b7cfcb9ef9.png">

**Comment by StephenCWills** [comment]
I think this is not exactly a duplicate, but it has already been discussed in #4382.

**Comment by AJenbo** [comment]
It's close enough that I would close this one since the solution is the same.

> Translate the string whenever it is meant to be shown.

how, there can be thousands of possible names

imo the only viable solution is to generate the name in another language. As with previous conversations on this topic we agree that the baked in name should be reverted to the English one, once we have a runtime solution for the displayed name.
