### ISSUE TITLE
MP: When fighting Leoric in his tomb monsters gets +100% hp

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5954]
A significant proportion of Leorics minons had gotten +100% hp after fighting i'm it's still a bit unclear how this happened. We had 1 player waiting out side the tomb and two player fighting in it.

**Comment by StephenCWills** [comment]
The sequence of events was as follows.

1. Players 1 and 2 entered the tomb and fought through the first couple rooms.
2. Both players went to town.
3. Third player joined.
4. Players entered the tomb through the Town Portal starting with player 3.
5. Player 3 left the tomb.
6. Players 1 and 2 cleared the tomb.

The monster health bar showed that many of the skeletons had more than 100% hp when we engaged them during step 6. I speculate that maybe their HP values got shuffled around due to monster sync packets, but that's kind of a wild guess.
