### ISSUE TITLE
MP: Valor won't open if player 2 reads the book

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#6023]
1: player 1 creates the game
2: player 2 joins
3: both players joins and leave on at a time (don't know if this has any effect)
4: player 2 reads to valor book
5: no blood stone drops, quest is stuck

**Comment by StephenCWills** [comment]
I had trouble reproducing this so I figured it probably had nothing to do with retracing the steps from our game. Instead, I suspect this is the result of a network race condition. Basically, this can happen in the fairly unlikely event where `OperateObject()` is invoked on player 1's client first. Since player 2 operated the book, `sendmsg` will evaluate to `false`, causing quest state to advance without spawning the Blood Stone. Once quest state has advanced, `Quests[Q_BLOOD]._qvar1` will evaluate to `1` making it impossible to force it to spawn the Blood Stone.

https://github.com/diasurgical/devilutionX/blob/6ba5998a978a0440037970ea8c18a6ad66f11f70/Source/objects.cpp#L2000-L2007

The exact race condition AJenbo and I encountered in our game would be difficult to reproduce, but the following steps will force a desync that causes the quest to get stuck.

1. On player 2's client, bind a key to the `Stop hero` action in keymapper settings
2. Get both players on dlvl 5
3. Place player 2 one tile away from the book
4. On player 2's client, click on the book, then press the `Stop hero` key from step 1 to cancel it
