### ISSUE TITLE
Feature request:  Toggle "Black Death" ability.

### ISSUE THREAD

**Issue by SabinStargem** [diasurgical/DevilutionX#6133]
The Black Death can permanently drain player stats, which I very much dislike.  Having the option to switch that off would be nice.

**Comment by SabinStargem** [comment]
> Mod territory

The problem with Black Death is that it reduces Max HP, not Vitality.  You can use an Elixir to increase Vitality, but there is no equivalent for Max HP.  I think this is an oversight made by Blizzard.

Further, there is the toggle for disabling stat drain shrines.  Which, by any reasonable definition, is a mod.  Why is it okay for Black Death's problem to be ignored, while malus shrines can be disabled?

**Comment by qndel** [comment]
Because shrine stuff only prevents you from clicking on them, doesn't change any game mechanics.

**Comment by AJenbo** [comment]
> The problem with Black Death is that it reduces Max HP, not Vitality. You can use an Elixir to increase Vitality, but there is no equivalent for Max HP. I think this is an oversight made by Blizzard.

They made multiple explicit fixes to that very logic so they where well aware of it and didn't remove it.

**Comment by galaxyhaxz** [comment]
While it is indeed the rogue like play-once-and-done aspect, nearly all stat reducing things are bugged (i.e. badly designed). Since the topic of shrines was brought up:
- there are 3 shrines which reduce max mana by 10% (not magic stat)
- there are 2 other shrines which can reduce magic stat by 1
- tear fountains can also reduce a stat by 1

Scenario: you hit a bunch of shrines to *permanently* reduce your max mana to 0. You then scout out shrines which reduce stats, and keep hitting them until it reduces the actual magic stat to 0. At this point, you will have a very low negative mana. 

One of two things can now happen:
- A) You can hit one more shrine and reduce magic stat to -1 (game has no check here). Since magic is unsigned, whenever you start a new game it will roll over to max (250 for sorc, etc.) but you will have something like -100 mana.
- B) You can hit a max mana reducing shrine and because it has checks, it will reset max mana from a negative value back to zero. You can then use magic elixirs to recover all the mana you "permanently" lost, except for the bonus from level ups.

All in all and IMO the black death was just as poorly designed as the other negative features. It only makes sense if you are to play through exactly ONE time, as an arcade game, and delete the save after.

**Comment by AJenbo** [comment]
Well poor game design is not a bug, it's bad design

**Comment by galaxyhaxz** [comment]
> Well poor game design is not a bug

For the record, you can apply the same technique above to recover permanently lost life from black deaths. You have to find shrines to reduce the vitality stat so you can use elixirs to boost it again. The only issue is that you can't let max life go below 1 in the same game, unless you cast energy shield to prevent death. Otherwise, a player can permanently be bugged in a death state from said shrines :P (yes, this is a bug and bad design)

**Comment by SabinStargem** [comment]
As I understand it, Blizzard altered Black Death in a Diablo 3 enactment of D1.  Black Death prevented the player from using healing sources while the debuff is present.   Aside from being more interesting than D1's effect during combat, it also implies that permanent stat loss isn't part of Diablo's identity.

The non-replaying of Diablo 1 may have been intentional at one point, but Diablo as a series has abandoned the once-and-done playstyle.  The question with DevilutionX is whether the project intends to keep Diablo 1 as an pure time capsule, or if the intent is to make Diablo 1 an ideal yet authentic version of itself.

That is why I requested for Black Death to have a mechanics toggle, so that old-school purists can have their version of Diablo, while more casual Diablo fans like myself can enjoy the game without jagged edges.  The option presented by Galaxyhaxz is a decent one.  I think there should be two options regarding stat drain:

A:  Temporary, where stat loss is localized for a current playthrough, and direct stat drain for HP/MP is applied to Vitality/Magic attributes instead.

B:  Vanilla behavior, where stat loss is permanent and can reduce max HP/MP.

This keeps the stat drain mechanics relevant, while keeping them more in line with future Diablo entries in spirit.

**Comment by AJenbo** [comment]
They also changed the entire team that worked on the game and everything else about it. If you want to chat and do theory crafting i suggest joining the chat instead of using GitHub issues.
