### ISSUE TITLE
Staffs remain unusable despite using stone shrine

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6141]
To reproduce, you first consume all the charges on your staff (e.g. staff of mana).
After that apply the stone shrine and see that the staff remains unusable.

**Comment by Korth999** [comment]
In the vanilla game, a staff depleted to zero charges loses its spell suffix. Just like an item depleted to zero durability is destroyed.

I thought this was intentional?

**Comment by StephenCWills** [comment]
Even if you deplete its _max_ charges to zero, the spell suffix does not get lost.

![image](https://github.com/diasurgical/devilutionX/assets/9203145/9bacf665-58ca-4d44-8df7-263176126c06)

But even if that's what you meant, it would be irrelevant to this issue because Stone shrine only replenishes charges, not max charges.

**Comment by qndel** [comment]
@Chance4us cannot reproduce on master. Provide save and commit

**Comment by Chance4us** [comment]
> Unless you mean that you have to reequip it to be able to use again?

Yes, I have to reequip the staff to make it usable again.
Otherwise, if I don't reequip the staff remains unusable.

**Comment by Chance4us** [comment]
I'll investigate/compare and let you know as soon as I can.

**Comment by AJenbo** [comment]
@qndel any idea if this was a vanilla issue?

**Comment by qndel** [comment]
@AJenbo It wasn't a vanilla issue
