### ISSUE TITLE
Gnat Sting and The Rift Bow don't do their special arrow mechanics when long pressing attack

### ISSUE THREAD

**Issue by wkdgmr** [diasurgical/devilutionX#6145]
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Issue is present in wkdmod with latest commits from Master and DevilutionX 1.4.1.

Referencing: Gnat String's "Multiple arrows per shot" only fires one arrow #1305 

I know this original issue was fixed, as both bows work when manually clicking/tapping the attack button... however if you stand ground and long press attack, or even long press attack at a targeted monsters, the multiple arrows of Gant Sting and Random Arrow Velocity of The Rift Bow mechanics don't work and the bows just fire normal arrows.

### To Reproduce

Load up a DevilutionX Debug build from 1.4.1 or current Master

dropu Gnat Sting
dropu The Rift Bow
goto 1
stand ground fire the weapon
target the monster fire the weapon

### Expected Behavior

the bows should always act as intended

**Comment by Korth999** [comment]
I'm running standard 1.4.1 release, no master or dev or debug build.

In this version, I use a Gnat Sting on my rogue and triple-shot works fine. I don't have a Rift Bow to test.

**Comment by StephenCWills** [comment]
Gnat Sting is working as intended. I am unable to reproduce the issue with Rift Bow.

https://github.com/diasurgical/devilutionX/assets/9203145/9e33b9a5-48c4-4aea-abdf-b7ccaadfe5f4

**Comment by Chonkblonk** [comment]
This is a bug? I thought this was intended behavior, and why I felt Gnat Sting wasn't a very good bow to use.
Still happens on my end, btw.

**Comment by Chonkblonk** [comment]
That Gnat Sting will not do its three-arrow Contra spread if you're holding down attack.
If I understood the OP right, this is supposed to be a bug, and it's supposed to be doing its triple shot every time, no matter what?

**Comment by StephenCWills** [comment]
Gnat Sting doesn't fire any extra arrows if you fire at full speed. It's been that way since vanilla, and it appears to have been intentional behavior based on how the code looks. DevilutionX hasn't changed that behavior.

Technically, vanilla didn't have hold-to-attack mechanics so some have suggested we could tweak the behavior to delay the hold-to-attack animation by one frame specifically for Gnat Sting, effectively enabling the user to reliably fire at maximum speed with the additional arrows. I personally don't think this is a good idea, and it was more or less rejected in #5598.

**Comment by DakkJaniels** [comment]
Was #5598 actually rejected, or did @kphoenix137 just close it during a mass closing spree of his open PRs? I think there were a few that were his that were closed by him on that date.
