### ISSUE TITLE
Quest Speech for Book of Blood stuck in loop - Multiplayer Loopback game

### ISSUE THREAD

**Issue by HellaTree** [diasurgical/devilutionX#6221]
### Operating System

Android

### DevilutionX version

1.5.0 (latest release)

### Describe

Upon reading the Book of Blood (multiplayer loopback game, Hell/Cats) I was unable to exit the quest dialogue - after playing through, the speech would repeat itself as if stuck on a loop. 

### To Reproduce

Go to dlvl5 while in a MP loopback game. 
Click on Book of Blood. 
Potential loop? 

### Expected Behavior

To finish the quest dialogue and exit the text pop-up. 

### Additional context

![Uploading Screenshot_20230614_202721_DevilutionX.jpg…]()

**Comment by AJenbo** [comment]
thanks for the bug report. it looks like you posted before the screen shot fully uploaded, could you please re upload it.

**Comment by StephenCWills** [comment]
Seems to happen consistently on gamepad. Some testing reveals that the game is spamming calls to `RepeatMouseAction()` while the quest dialog is playing. I guess the padmapper release action is getting skipped because of the key translation that occurs when quest text is active.

Padmapper release action:
https://github.com/diasurgical/devilutionX/blob/9381251b9d47a0500ade939a8bc4d881573688e5/Source/diablo.cpp#L1894-L1897

Key translation:
https://github.com/diasurgical/devilutionX/blob/9381251b9d47a0500ade939a8bc4d881573688e5/Source/controls/game_controls.cpp#L200-L201
