### ISSUE TITLE
New Gameplay Option: Pepin Auto-Heal

### ISSUE THREAD

**Issue by tunbridgep** [diasurgical/devilutionX#6225]
In the current version, visiting Pepin the Healer will automatically heal the character.

This is totally fine and how it was in the original.

However, this encourages a form of gameplay where the player is encouraged to run back up to town in order to receive free healing repeatedly, especially when fighting enemies near the start of the game.

I consider this degenerate gameplay, as it essentially allows the player to heal infinitely as long as they are willing to waste some time.

I would like an option in the gameplay settings, "Pepin Auto-Healing", similar to the Adria Auto-Mana option. When turned off, Pepin will only sell you potions, he will not heal you, meaning the only way to get healed is essentially by spending money.

I understand this is not likely to be a popular suggestion - most people might see it as odd that I am essentially asking for a feature to be removed rather than added. Especially since I could just not engage in the degenerate gameplay. However I do feel like it would help fix some of what I believe are gameplay issues in the original.

**Comment by DakkJaniels** [comment]
Adding yet another option for something one could just not engage with seems not worth the cost of expanding and complicating the codebase. Also this is how it worked in Diablo 2 (since you referenced how D2 worked in your other request), you couldn't turn off healing.

**Comment by AJenbo** [comment]
im more inclined to remove Adria Mana

**Comment by julealgon** [comment]
> However, this encourages a form of gameplay where the player is encouraged to run back up to town in order to receive free healing repeatedly, especially when fighting enemies near the start of the game.
> 
> I consider this degenerate gameplay, as it essentially allows the player to heal infinitely as long as they are willing to waste some time.

Totally agree that this is a poor gameplay mechanic, but I think you'll have a (very) hard time convincing people to add this option either because it makes things more complicated (@DakkJaniels 's argument which I agree with as well) or because it would enter into mod territory.

I'd propose a variation of that: perhaps make it so that Pepin charges for the service, proportional to the % of max life that needs to be healed? I'm sure there is a way to balance it out along with price for potions while still not completely removing the option.

The problem is that balancing this _properly_ could be a bit elaborate as well, since each class has a particular bonus or penalty to healing (e.g. the warrior is a lot more effective with small healing potions than the sorcerer).

**Comment by AJenbo** [comment]
Given that it would be an option i also feel it would be kinda pointless, people that tend to use it would just not disable it.

**Comment by julealgon** [comment]
> Given that it would be an option i also feel it would be kinda pointless, people that tend to use it would just not disable it.

I was coming from the perspective that if implemented that way, it would _not_ be an option but the default behavior. Otherwise I fully agree with you.
