### ISSUE TITLE
Gamepad: Unable to use some scrolls directly

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#6231]
### Operating System

Android

### DevilutionX version

1.5.0 (latest release)

### Describe

In some cases using a healing scroll will fail and instead the hero will start the frist frame of the animation, play the scroll sound and then return to idle with out having used the scroll.

Changing the active spell seams to alleviate this, but then the next scroll will fail as well.

### To Reproduce

1. load up your belt with a few heling scrolls
2. press the "heal action" button
3. be confused about what is going on

### Expected Behavior

cast the spell

### Additional context

This also happens when highlighting a scroll in the inventory and pressing use. This can also happen with identify scrolls.

Town portal scrolls do not appear to be affected by this issue.

Selecting the scroll as the active spell and casting it like other spells appears to work each time.

**Comment by StephenCWills** [comment]
I think it's because the cursor position is set to an invalid coordinate here.
https://github.com/diasurgical/devilutionX/blob/a88374cae8b547663a274582bb5c10b69a4fb6dc/Source/controls/plrctrls.cpp#L1775

The call to `UseInvItem()` uses the cursor position in the call to `NetSendCmdLocParam4()`.
https://github.com/diasurgical/devilutionX/blob/a88374cae8b547663a274582bb5c10b69a4fb6dc/Source/items.cpp#L4084-L4094

And this position is validated when the command is processed.
https://github.com/diasurgical/devilutionX/blob/a88374cae8b547663a274582bb5c10b69a4fb6dc/Source/msg.cpp#L1473-L1474

**Comment by StephenCWills** [comment]
I didn't bother testing, but it was almost certainly introduced by #5988. That PR introduces the call to `NetSendCmdLocParam4()` where previously it was writing directly to `player.destAction`.
