### ISSUE TITLE
Finding two identical items in the same session 

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6261]
I thought that we can no longer dupe.
But somehow received a duplicate of "ring of sorcery".
Not able to pick up both items, so it's a duped item.
![dupe](https://github.com/diasurgical/devilutionX/assets/45902449/4f9a5892-1ae5-418f-afcc-3705c0c46816)

[dupe.zip](https://github.com/diasurgical/devilutionX/files/11858016/dupe.zip)

**Comment by StephenCWills** [comment]
I was looking into this the other day because I'd received similar examples of duplicates from another player on Discord. It turns out the chances of this are a lot higher than you'd think.

Basically, you can find duplicates like this across different dlvls because the maximum RNG distance between any two dlvl seeds is 25 random numbers at the most. It takes around 2k-4k random numbers to generate all the objects and monsters on the level. Most of those random numbers are used when generating monsters, and it's all done right after seeding the RNG, so there's plenty of opportunity for overlap between the random number sequences used to generate different dlvls. If a monster's seed matches exactly with another monster that is located on another dlvl and the two monsters have the same mlvl, you will get an exact duplicate like the one in your save file.

**Comment by AJenbo** [comment]
I would say they are identical more then that they where duped, they are perfectly legit you just found the same item twice.
