### ISSUE TITLE
Ability to specify path of game files

### ISSUE THREAD

**Issue by msmigiel** [diasurgical/devilutionX#6476]
It would be great if there was a way to specify the location of the original game files. This woud benefit all supported platforms but would be especially helpful on Android as one could put the data files in a user configurable location (such as an external SD card to save internal storage space) instead of `Android/data/org.diasurgical.devilutionx/files`.

**Comment by DakkJaniels** [comment]
There is a way to do that, but maybe not on Android - can arguments be passed to the program in android when it runs?

**Comment by StephenCWills** [comment]
> There is a way to do that, but maybe not on Android - can arguments be passed to the program in android when it runs?

No, and there wouldn't really be any reason to do so either. I'm simplifying, but suffice it to say that our application doesn't have permission to read from or write to any other directory. If you want to put your data files on an external SD card, put it in the application's external files directory on that SD card. AFAIK, the path is the same, but on the SD card instead of the main storage device.

**Comment by AJenbo** [comment]
Recent sdk versions limit what paths native apps can access so this is out of our control.
But as mentioned it is possible to have the files on the SD card already.
