### ISSUE TITLE
[Feature Request]: Make belt items invisible to Adria when selling

### ISSUE THREAD

**Issue by Entkoffeinator** [diasurgical/devilutionX#6540]
### Feature Type

Quality of Life

### Describe

Remove/hide the potions/scrolls/etc equipped in your belt from the sell list.

**Comment by FitzRoyX** [comment]
This game has a crapton of scrolls, unlike d2, and they quickly become sell loot. You want to force moving them into the inventory before sale? Annoying. The real problem isn't the belt, it's that the sell windows are textual lists that can show 4 items at a time instead of a visual grid where you just click directly and immediately on what you want. You know, like the inventory.

**Comment by ChaosMarc** [comment]
A visual/textual indicator showing the item is in the belt instead of the inventory would help a lot I think. This wouldn't be the complete overhaul to d2 mechanics but would go in the right direction

**Comment by kphoenix137** [comment]
I think a GUI based shop would fix a lot of shop based woes

**Comment by julealgon** [comment]
Created a related, perhaps more general, proposal here:
- https://github.com/diasurgical/devilutionX/issues/6582
