### ISSUE TITLE
Toggle fullscreen by hitting alt+enter 

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#659]
Toggle fullscreen by hitting alt+enter does not work if the game is paused.

**Comment by remembertoremind** [comment]
Im currently using dwm. If I fullscreen devilutionx on one tag and change to another tag and back devilution will be tiled in a box but still be treated as fullscreen. Not sure if the bug is related to devilutionx or dwm.

**Comment by qndel** [comment]
what "tag"?

**Comment by AJenbo** [comment]
DWM: dynamic window manager - https://dwm.suckless.org/
It's a tiled window manager.

"Tag" is probably DWM way of referring to an application instance.

@remembertoremind, since your issue isn't related to the changes in this pull request commenting on it with your issue, is a bit of a hijack. The proper thing to do is open a new issue instead.

I would say that this issue is down to how your window manager responds to a request for an application to go fullscreen. So probably open an issue with them instead. The full-screen negotiation is happening between SDL2 and DWM, but I can't say if this is how DWM has chosen to do things by design.

**Comment by remembertoremind** [comment]
> since your issue isn't related to the changes in this pull request commenting on it with your issue, is a bit of a hijack. The proper thing to do is open a new issue instead.

Ah! Sorry. I had no intention of hijacking. I'll see if I can find more info and create another issue :)

**Comment by AJenbo** [comment]
I realize :) There isn't really anything we can do so you will need to create the issue with DWM, not sure where they have there bug tracker.
