### ISSUE TITLE
[Issue Report]: Graphical Glitch in Cave, See-Through Tile

### ISSUE THREAD

**Issue by sanscriptum** [diasurgical/devilutionX#6647]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

A graphical glitch as seen on the screenshot. If I'm not having a deja vu moment, I think it was a rare occurrence in vanilla as well.
![Screenshot from 2023-09-21 09-19-22](https://github.com/diasurgical/devilutionX/assets/3057589/e50336e5-c9b2-46de-9b3e-782471299429)
[save.zip](https://github.com/diasurgical/devilutionX/files/12681071/save.zip)

Coincidentally, this cave map was rather cursed, and I swear I had a charger actually go through the lava river on its diagonal corner in the upper left direction from the position on the screenshot.

### To Reproduce

Load the save and walk around a bit, it should be on the screen

**Comment by ephphatha** [comment]
This is a vanilla issue and was first reported in https://github.com/diasurgical/devilutionX/issues/111 (closing this one as a duplicate since 111 is still open)

I think the plan is to patch the missing tile(s) eventually, but no one has had a chance to implement that in the code that loads cels yet.
