### ISSUE TITLE
[Feature Request]: please add starcraft to this source port.

### ISSUE THREAD

**Issue by DOOMMARINE117** [diasurgical/devilutionX#6796]
### Feature Type

Other (please specify)

### Describe

Can you add starcraft brood war to this port if possible?

**Comment by StephenCWills** [comment]
No, that won't be happening.

**Comment by AJenbo** [comment]
@DOOMMARINE117 I don't think you understand how any of this work.

StarCraft and Disabl's only real common point is that they where released in the mid 90s. You might as well be asking for support for Quake 2.

If the reason you think it might make sens is because both use .mpq files then please know that they are very similar to zip files. It would again be analogous to thinking that you could add Quake 2 support because both where shipped on CDs.

Hope that helps explain why this suggestion is not something we can do in any meaningful sens.
