### ISSUE TITLE
[Feature Request]: Access dungeons from town

### ISSUE THREAD

**Issue by lonely188** [diasurgical/devilutionX#6910]
### Feature Type

Quality of Life

### Describe

When playing the base game of D1 (non Hellfire), as a single player game,  please make it so that the shortcuts from town, down to the dungeons (Catacombs,  Caves,  Hell)  are always unlocked after meeting clvl requirements.  It is this way in Hellfire Single player,  but not D1. As a QOL feature to D1, it would make playing repeated "New Games" with the same character much more enjoyable instead of having to run from level 1 all the way down to level 13 each new game on Nightmare or Hell when my character doesn't even gain XP anymore on the early dungeon levels. If not everyone wants this feature on,  make it part of the settings file to toggle on/off.

**Comment by julealgon** [comment]
From a game design/concept perspective, I strongly disagree. I'd instead propose the opposite: make it so that the shortcuts only open when the level is accessed from inside like in the original.

**Comment by Chonkblonk** [comment]
I fail to see the problem with this, it already works that way in multiplayer, may as well give the option for singleplayer.

**Comment by julealgon** [comment]
> I fail to see the problem with this, 

My own take on it is that I think this removes an important aspect of the gameplay, one that is actually somewhat logical/realistic: only having access to the shortcuts once you reach the levels. If it was up to me, I'd actually propose a change where you had to either find the actual shortcut stairs, or go through it, for the shortcut to be unlocked (instead of just _reaching_ the dlvl). That would work better to me as the player would be "discovering" the shortcut from the inside, which makes sense since the shortcuts are either locked or hidden initially.

I also think that basing it on clvl is too arbitrary. Why would a shortcut suddenly "open"/"be avaiable" once I reach a certain level? Yes I don't think every aspect of a game needs to be 100% realistic, but to me this is too far in the other direction.

And lastly, I think Nightmare and Hell balance should _never_ be used as justification for any changes in the game since they are completely and utterly broken by definition. Personally, I'd prefer they be removed entirely until someone can actually figure out a good way to put them back in. Yes, that's not a very popular opinion, I know.

> ...it already works that way in multiplayer, may as well give the option for singleplayer.

I don't particularly find this argument compelling. Multiplayer in Diablo was a hacked together afterthought (game was supposed to be single player for the vast majority of it's development, and it shows in the code...), and especially Nightmare and Hell difficulties are utterly imbalanced.

To me, any proposal that bases itself on multiplayer or existing difficulty levels balance is just weak by definition.

You also mention the behavior in Hellfire as another argument for making the change. The same logic applies there: just because something was done in Hellfire, doesn't mean it is good/correct/appropriate. Most of the time, it's the contrary: a lot of changes made in Hellfire are absolutely terrible from multiple angles.

Now... Ajenbo disagrees with me there so you actually have a good chance of this being added to the game. I don't have much of a say at all on what gets implemented, I just like discussing things about this game and questioning some of these requests from a game design and code simplicity perspective 😆

**Comment by lonely188** [comment]
I know I didn't say this in my original request,  but I would agree that at least on the players first play through, the dungeon shortcuts should be locked until you get to those levels first.  So maybe instead of basing it on character level,  each dungeon shortcut on each difficulty needs to be accessed for the first time and then remains unlocked from that point on in all future new games of that difficulty.  But that would require saving that info to the character save file right? Is that even possible?  Might be harder to implement?

**Comment by DakkJaniels** [comment]
I think we can, hypothetically, save whatever we want as a new file in the character file mpq. Since vanilla wouldn't know or care about this, that would probably be the best way to handle it anyway. I know there are some additional files in the mpq, but I don't recall offhand if there is one for character info.

**Comment by StephenCWills** [comment]
> I fail to see the problem with this, it already works that way in multiplayer, may as well give the option for singleplayer.

It would be reasonable to assume that Blizzard opened the shortcuts in MP because there is no Save/Load option. The same can't be said about Single Player so it's not a very good justification.

One thing that hasn't been mentioned is the fact that closing the shortcuts helps no one, and only serves to hassle the player. Therefore, it seems like pure QoL to just open them up, and Sierra devs obviously agreed. However, _because_ it is a hassle, it presents a trade-off to the player.

Let's say you're having some trouble getting through dlvl 13. Do you start a new game and wade through the early dungeon levels again to earn more exp and gain more loot in the hopes you can complete dlvl 13 this time, or do you tough it out and find a way to avoid the hassle of starting again?

Anyway, I don't think we really need to have the should we/shouldn't we discussion. We already have Hellfire, which opens up the shortcuts. For everything else, there's Lua.

**Comment by galaxyhaxz** [comment]
A lot of people are overlooking the balance aspect of this, as I've considered this myself as well: You can only buy things like elixirs/jewelry from vendors in single player, and it's based on what dungeon level you visited. If the shortcuts were open, you could easily reroll games and buy elixirs. OTOH in SP which didn't have difficulties by default, it makes no sense to send your level 30+ character back down the earlier levels on normal....

**Comment by lonely188** [comment]
> For everything else, there's Lua.

By Lua, you mean Lua scripts? Is this something already supported by devilutionx or coming in the future?  And are you saying this feature request could just be modded in with a Lua script? If so,  I would love to learn how.  

> We already have Hellfire, which opens up the shortcuts.

I like the base game better over what Hellfire all change to the game. A lot of Hellfire changes feel cheaty to me. So that's why I was asking for this QoL feature in D1, because my opinion was that this one change alone feels good and fair.  Again it wouldn't have to be exactly the same as it is in Hellfire. Instead it could be saved to a character,  and all shortcuts need to be unlocked for the first time,  but then remain unlocked in the future.

**Comment by julealgon** [comment]
> By Lua, you mean Lua scripts? Is this something already supported by devilutionx or coming in the future? And are you saying this feature request could just be modded in with a Lua script? If so, I would love to learn how.

Lua scripts, yeah. It is supported @lonely188 , but I think usage is still a bit limited. Other folks can elaborate.

**Comment by StephenCWills** [comment]
> By Lua, you mean Lua scripts? Is this something already supported by devilutionx or coming in the future? And are you saying this feature request could just be modded in with a Lua script? If so, I would love to learn how.

Yes, yes, and yes. But the caveat is that Lua is still in the early stages of development so you'd have to make changes on the C++ side to make it possible on the Lua side. After that, you'd just need to install a Lua script to have the shortcuts opened. This is something I expect will be made possible over the course of development for 1.6.0 since we are aiming to have Hellfire mechanics implemented as Lua scripts.

> I like the base game better over what Hellfire all change to the game. A lot of Hellfire changes feel cheaty to me.

Hmm. Off the top of my head, the shortcuts would rank as number 3 on my list of the cheatiest mechanics exclusive to Hellfire.

> A lot of people are overlooking the balance aspect of this, as I've considered this myself as well: You can only buy things like elixirs/jewelry from vendors in single player, and it's based on what dungeon level you visited. If the shortcuts were open, you could easily reroll games and buy elixirs. OTOH in SP which didn't have difficulties by default, it makes no sense to send your level 30+ character back down the earlier levels on normal....

On the topic of elixirs, I guess you could farm the Black Mushroom quest in Hellfire since the Caves shortcut is open. We had some discussions about that on Discord after we implemented SP quests in MP.

**Comment by AJenbo** [comment]
Lua it is then

**Comment by StephenCWills** [comment]
> If you want to grind for Elixirs in this situation, it's faster and easier to just run back and forth between Adria's shed and the Catacombs over and over. It costs some, but it's not that hard to make money.

TBH, that's what I've been telling everyone. It's more efficient to alternate between Warlord of Blood/Lazarus/XP farming and buying elixirs than it is to hunt solely for stats by doing dlvl 9 over and over again for the Spectral Elixir. The first thing I'll say is that not everyone is entirely convinced. Ignoring that, however, I must admit that it's not necessarily a useful observation. Like, comparing these two strategies made sense to me when arguing for the fact that introducing Black Mushroom to MP doesn't break the game's balance. In the context of this issue, it seems pointless to bring it up since opening the shortcuts makes both options significantly more viable.
