### ISSUE TITLE
[Issue Report]: Padmapping isn't working correct

### ISSUE THREAD

**Issue by 20Phoenix** [diasurgical/devilutionX#6930]
### Operating System

Xbox Series S

### DevilutionX version

1.5.1

### Describe

Changing buttons in diablo.ini under [Padmapping] doesn't change the menu behaviour.
I want to confirm with A in the menus and chancel with B.

### To Reproduce

After edited buttons PrimaryAction=A & CancelAction=B in diablo.ini, but A is still Cancel instead of Confirmation.

### Expected Behavior

Buttons should act as set.

**Comment by StephenCWills** [comment]
This is by design. The menu doesn't use padmapper bindings because you could easily brick the game by unbinding the confirm action.

**Comment by julealgon** [comment]
> This is by design. The menu doesn't use padmapper bindings because you could easily brick the game by unbinding the confirm action.

This is fairly poor justification @StephenCWills . Can't you just add some UI validation that guarantees the user has the required actions bound before exiting the button mapping area, and then make it apply globally?

**Comment by StephenCWills** [comment]
> This is fairly poor justification @StephenCWills . Can't you just add some UI validation that guarantees the user has the required actions bound before exiting the button mapping area, and then make it apply globally?

No, I can't. The settings menu reflects the actual state of the padmapper, not a transactional state that can be applied to the padmapper. When you change a binding in the settings menu, the binding gets applied directly to the state of the padmapper and therefore directly to the in-game mapping for the controller immediately.

Even if I was willing to rip out the guts of the settings menu to make this thing possible, that doesn't mean it's the best way to solve the core issue, which is simply a desire for the confirm and cancel buttons to be swappable. I have some other possible solutions in mind. Keeping an issue open that openly states the padmapper isn't working correctly on that basis would be silly.

**Comment by julealgon** [comment]
> > This is fairly poor justification @StephenCWills . Can't you just add some UI validation that guarantees the user has the required actions bound before exiting the button mapping area, and then make it apply globally?
> 
> No, I can't. The settings menu reflects the actual state of the padmapper, not a transactional state that can be applied to the padmapper. When you change a binding in the settings menu, the binding gets applied directly to the state of the padmapper and therefore directly to the in-game mapping for the controller immediately.

You are listing this as if it was immutable though. Making the button mapping dialog transactional instead of modifying the values on the fly for each edit would be 100% feasible. Then, validation can be implemented to ensure the setup is valid before persisting, and present an error message otherwise explaining why the setup cannot be used.

> Even if I was willing to rip out the guts of the settings menu to make this thing possible, that doesn't mean it's the best way to solve the core issue, which is simply a desire for the confirm and cancel buttons to be swappable.
> I have some other possible solutions in mind...

What do you think would be a better solution to the core issue? Do you think the desire itself isn't warranted? 

> Keeping an issue open that openly states the padmapper isn't working correctly on that basis would be silly.

I don't disagree, but I think renaming the issue to better reflect the request would be preferrable to just closing it. Yes, as you said, it's currently working by design, but this could still be converted from a bug into a feature.

**Comment by StephenCWills** [comment]
> You are listing this as if it was immutable though. Making the button mapping dialog transactional instead of modifying the values on the fly for each edit would be 100% feasible. Then, validation can be implemented to ensure the setup is valid before persisting, and present an error message otherwise explaining why the setup cannot be used.

It's an immutable fact that I won't be doing it. Since I refuse to do it, it isn't inaccurate to say that I can't. Although it would also be accurate to say that I do have the technical ability to do it, I don't think you really need me to tell you that.

> What do you think would be a better solution to the core issue? Do you think the desire itself isn't warranted?

I mean.. if you want to swap confirm/cancel in the menus, then the most obvious solution would be to provide a setting to swap confirm/cancel in the menus. I'm not sure if this is my favorite possible solution, but it does sound better than hijacking existing padmapper actions.

> I don't disagree, but I think renaming the issue to better reflect the request would be preferrable to just closing it. Yes, as you said, it's currently working by design, but this could still be converted from a bug into a feature.

Come on. It should be obvious that the title is not the only problem with this issue. The only sensible thing to do with this one is close it. I feel like you're not arguing because you actually think it's important to track this, but if I'm wrong then feel free to create a new issue yourself.

**Comment by julealgon** [comment]
> It's an immutable fact that I won't be doing it. Since I refuse to do it, it isn't inaccurate to say that I can't. Although it would also be accurate to say that I do have the technical ability to do it, I don't think you really need me to tell you that.

Fair enough, up to you. I just don't see this being very conducive to collaboration. You keep saying "you" personally is not going to/not willing to do it, but have you considered the possibility that somebody else looking into this would be willing to take a stab at it?

To be clear, I'm not saying I want to tackle this either, but that's not the point. My point is simply that, if an issue has merit, then it should remain open to give visibility to others and to promote more people contributing to the project.

My personal view is that you and Ajenbo are sometimes a bit _too_ quick on the trigger to close these and end up disregarding valid potential improvements.

> I mean.. if you want to swap confirm/cancel in the menus, then the most obvious solution would be to provide a setting to swap confirm/cancel in the menus. I'm not sure if this is my favorite possible solution, but it does sound better than hijacking existing padmapper actions.

Fair. I disagree, but I can see that as possible solution (I just think it's both unflexible and inconsistent). I do know some games that offer that option specifically, and I think it's a sub-optimal approach.

> Come on. It should be obvious that the title is not the only problem with this issue. The only sensible thing to do with this one is close it. 

I disagree. There is clearly some merit to it, it just need to be worded a bit different (mainly the title) and shifted from a bug to a feature request. You think otherwise, ok.

> I feel like you're not arguing because you actually think it's important to track this, but if I'm wrong then feel free to create a new issue yourself.

On a personal level, I don't care much for this functionality, but if I were to provide a button remapper (which DevilutionX does), _then_ I think it is an important and sensible request.

Would I consider it fairly low priority? Oh absolutely. 

But again, that's not really the point IMHO. The point is keeping track of valid improvements, regardless of how challenging they are to implement, or how critical they are, because this increases the likelyhood of other folks contributing to the project (or at least I believe so). And considering I'd like for DevilutionX to be as popular and successful as possible, of course I care about trying to expand the appeal of the source code in this sense.

Keep in mind that by abruptly closing issues with a single sentence drives a lot of people away from contributing _issues_ as well: the attritude is just not encouraging or friendly enough to motivate some people. If you are ok with this and would rather drive away those types of people anyway, then sure, I think the strategy is valid. Otherwise, my feedback (which you can totally ignore if you want) would be to give these issues _a better chance_, by working with the creators to salvage them into useful documentation/proposals. I think that would be substantially more productive.

**Comment by StephenCWills** [comment]
> Fair enough, up to you. I just don't see this being very conducive to collaboration. You keep saying "you" personally is not going to/not willing to do it, but have you considered the possibility that somebody else looking into this would be willing to take a stab at it?

Yes, of course I've considered it. But let's talk about you first. You've asked the following question.

> Can't **you** just add some UI validation...

You can claim that this was supposed to be the impersonal "you", but then what exactly was the answer you expected to receive? And can you really say I've done something wrong by answering for myself and not everyone else?

I am not using the impersonal "you" here, but my questions are rhetorical. This whole discussion is pointless, as is your implication that I didn't consider the possibility that somebody else would be willing to take a stab at this. If someone is willing to take a stab at this, I sincerely hope they don't read any of the discussion we've had here because none of it will be helpful. And between the two of us, I've tried to do more to avoid them reading this.. by closing the topic.

> To be clear, I'm not saying I want to tackle this either, but that's not the point. My point is simply that, if an issue has merit, then it should remain open to give visibility to others and to promote more people contributing to the project.

And what merit does this issue have? If you've identified something here with merit that needs to be captured by an issue, then I'm literally begging you to create a new issue using the feature request template that properly explains it.

> My personal view is that you and Ajenbo are sometimes a bit _too_ quick on the trigger to close these and end up disregarding valid potential improvements.

It's my personal view that you are too quick to link the act of closing issues with the act of disregarding potential valid improvements. The first is your opinion, presumably based on the second. But the second is just conjecture.

> Fair. I disagree, but I can see that as possible solution (I just think it's both unflexible and inconsistent). I do know some games that offer that option specifically, and I think it's a sub-optimal approach.

Right.. inflexible because what if someone wants menu cancel to be mapped to their guitar pedal? I would argue that a flexible solution to remapping menu controls would be a prime example of overengineering. Inconsistent because why shouldn't I be able to brick the menus if I'm able to brick the game? I would argue that being consistent in this regard runs the risk of homogenizing systems in the codebase in a way that would make it difficult to reflect the need for different usability requirements.

The menu is not really a large part of the core gameplay loop. The main thing you need to avoid is making them unintuitive. Hence why I've not made the claim that there's no need for swapping confirm/cancel. It's just that I'd be surprised if we really needed to do much more than that.

> I disagree. There is clearly some merit to it, it just need to be worded a bit different (mainly the title) and shifted from a bug to a feature request. You think otherwise, ok.

This issue needed to be about something that it is not. Saying that padmapper isn't working correctly and that it should be working a specific way is a far cry from swapping the confirm and cancel buttons in the menu. That the creator of this issue just happened to want to swap confirm and cancel in the menus circumstantially reinforces my point that implementing only that much is probably more-or-less sufficient to resolve some usability issues with the menus, but it's not what this issue is about.

To pivot this issue, I'd have had to edit everything about it. The caption of "Issue Report" is incorrect, the title itself is incorrect, the sections in the description are based on the bug report template and not the feature request template, the content of those sections are incorrect, and the tags would have to be modified. What would you even call that if it's not creating a whole new issue?

> On a personal level, I don't care much for this functionality, but if I were to provide a button remapper (which DevilutionX does), _then_ I think it is an important and sensible request.

Then you self-admittedly care about this functionality less than I do. Fixing this is on my to-do list. It's a bit insulting to me that you are arguing this hard when you don't even care.

> Would I consider it fairly low priority? Oh absolutely.

Another point we disagree on. I don't consider this a low priority. I intend to polish the gamepad controls for 1.6.0 because I consider it to be a pretty vital aspect of making the game accessible for visually impaired players. I've been actively involved in the development of the current controls, and I've done my own testing. I don't need an inaccurate issue on GitHub to help me track the usability concerns I can see with my own eyes by playing the game.

> But again, that's not really the point IMHO. The point is keeping track of valid improvements, regardless of how challenging they are to implement, or how critical they are, because this increases the likelyhood of other folks contributing to the project (or at least I believe so). And considering I'd like for DevilutionX to be as popular and successful as possible, of course I care about trying to expand the appeal of the source code in this sense.
> 
> Keep in mind that by abruptly closing issues with a single sentence drives a lot of people away from contributing _issues_ as well: the attritude is just not encouraging or friendly enough to motivate some people. If you are ok with this and would rather drive away those types of people anyway, then sure, I think the strategy is valid. Otherwise, my feedback (which you can totally ignore if you want) would be to give these issues _a better chance_, by working with the creators to salvage them into useful documentation/proposals. I think that would be substantially more productive.

I do somewhat agree with you here. Bug reports about the padmapper working incorrectly when it's actually working as designed is something that I would like to discourage. You could even say that I was discouraging this by design. Someone who actually cared about the issue of swapping confirm/cancel could then follow up with, say, "But how can I swap confirm/cancel in the menus?" And then you could come in and helpfully direct them to the "feature request" button. That would be a much cooler thing to do than to clutter up someone else's topic, waxing poetic about how you don't like how we manage issues when you don't even care about the topic at hand.

**Comment by AJenbo** [comment]
> My point is simply that, if an issue has merit, then it should remain open

I understand your perspective. However, we aim to streamline our process to focus on actionable items and prevent unnecessary clutter. Managing open issues can be challenging, especially when dealing with those that may not be immediately actionable or significant.

> My personal view is that you and Ajenbo are sometimes a bit too quick on the trigger to close these and end up disregarding valid potential improvements.

You have expressed this numerous times in various issues. It creates a lot of off-topic noise, something I think can be very discouraging to the original reporter since they likely get a bunch of notifications containing nothing but quarrel.

If you feel strongly about this matter, I encourage you to initiate a [discussion](https://github.com/diasurgical/devilutionX/discussions) about it where we can hash things out. Going off-topic in a closed issue is a sure fire way to start of on the wrong foot, and I ask that you refrain from it in the future if you do not have something directly related to the specific issue.

> The point is keeping track of valid improvements, regardless of how challenging they are to implement, or how critical they are, because this increases the likelyhood of other folks contributing to the project (or at least I believe so)

I get your sentiment. However, we should strike a balance to avoid overwhelming both contributors and maintainers. Having a lot of stale issues can also give the impression of project stagnation.

> Keep in mind that by abruptly closing issues with a single sentence drives a lot of people away from contributing issues as well: the attritude is just not encouraging or friendly enough to motivate some people.

There is some merit to this, and it is something that I try to keep in mind when choosing to close an issue. If it is a reasonable request and someone new to the project, I usually try to add a few encouraging words if I close the issue.

**Comment by glebm** [comment]
Making the buttons consistent between in-game and in-menu, e.g. to have A be the confirm button on Switch in both, is tracked in https://github.com/diasurgical/devilutionX/issues/5467.

**Comment by AJenbo** [comment]
I think this one is about Xbox though, I wonder if it's also not following the proper convention there and that is why @20Phoenix was trying to change them. A bit hard to know what combination we are looking at here.

**Comment by glebm** [comment]
Yeah, #5467 is not specific to the Switch. As @StephenCWills mentions in the other issues, (1) gamepad type may need to be made configurable, (2) we do not currently seem to handle gamepad type defaults correctly in the main menu (?).

**Comment by AJenbo** [comment]
We might even be doing it in reverse considering that both Switch and Xbox users are unhappy with it :sweat_smile:

**Comment by glebm** [comment]
Ah, that's an interesting observation, we probably are! 😅

**Comment by StephenCWills** [comment]
I couldn't find mention of this on GitHub with just a quick search so I'll make a note of it here. I remember now that the Xbox One/Xbox Series build had some custom startup code that attempted to swap the A/B and X/Y buttons using SDL controller mappings.

https://github.com/diasurgical/devilutionX/blob/9a148ab9909e51e4c33468ec232206e327e934d1/uwp-project/src/SDL_winrt_main_NonXAML.cpp#L65-L82

Now that we are able to detect controller type, this code should be unnecessary. But it's worse than that because I've found that it's subject to a race condition. Sometimes this code runs before the SDL event that adds the game controller. Discord user Tree reported it on Discord back in August 2022, and I think there was another report even before that so I think that confirms it happens on Xbox hardware. I have never run the build on anything but Windows, but I was also able to reproduce the issue there.

@20Phoenix didn't mention anything about the mapping being inconsistent so I'm wondering if it's still happening, or if it even happens on Xbox Series consoles. Regardless, it would be a good idea to remove this code.
