### ISSUE TITLE
[Issue Report]: Inventory problems

### ISSUE THREAD

**Issue by Sergei3000yt** [diasurgical/devilutionX#7026]
### Operating System

Android

### DevilutionX version

1.5.2

### Describe

I don’t know how it is on other platforms other than PC, but on Android the cursor is tied to the inventory and potion belt. This causes some problems. Firstly, with an open inventory it is impossible to replenish the character’s parameters at a new level. Well, that's okay, this can be solved by closing the inventory. A much more serious problem is that due to the cursor being tied to the inventory, the use of runes is impossible. The third problem is that some spells are very difficult to cast from scrolls from the inventory due to cursor binding.
At the moment in 1.6.0-dev these problems are still present.

P.s. Sorry if the problem is already known.

### To Reproduce

1. Open inventory
2.1. Try to increase your character's stats at a new level
2.2. Try using runes

### Expected Behavior

I wish the runes worked

**Comment by AJenbo** [comment]
When the inventory is open it switches to inventory navigation, that is intentional. If you don't want to interact with the inventory you should close the inventory.

Runes can only be used runes with a mouse for now, see https://github.com/diasurgical/devilutionX/issues/3359
It's not really connected to how inventory navigation works.
