### ISSUE TITLE
[Issue Report]: Inventory bug [1.6.0-dev]

### ISSUE THREAD

**Issue by Sergei3000yt** [diasurgical/devilutionX#7028]
### Operating System

Android

### DevilutionX version

1.6.0-dev-debug

### Describe

In version 1.6.0-dev-debug, the inventory began to work somewhat strangely. Very often, when picking up items, one of the inventory lines is not filled. The line slightly to the left of the middle (the line from top to bottom) is ignored by the inventory until you fill it in manually.

### To Reproduce

Pick everything up

**Comment by kphoenix137** [comment]
Unable to reproduce in commit: 99308085f0ed3eba3e8c5adf6fcebbd5907f4245
https://github.com/diasurgical/devilutionX/assets/68359262/ae7b0ef4-5f03-4e20-93e6-1d15635784ba

**Comment by AJenbo** [comment]
@Sergei3000yt Can you try to make a video, or be more specific. Maybe add a screen shot where  you mark what row (column) it is.
It sounds like you are talking about this column:
![image](https://github.com/diasurgical/devilutionX/assets/204594/6cf8dc9b-bd4e-4712-b954-19557571f157)

It would be good with specific steps to reproduce, maybe even a save game where the items to pick up are already on the ground.

Can you show how it places items differently in 1.5.2 (load the same save game and take a screen shot there)

**Comment by ephphatha** [comment]
Based on videos shared in discord this issue is discussing the behaviour for 2x2 items. From the original PR this is an intentional decision to try make the item placement more visually pleasing: https://github.com/diasurgical/devilutionX/pull/1876#discussion_r627746815

The issue appears to be if a player picks up a 1x2 item, a 1x3 item, then a bunch of 2x2 items they end up with a suboptimal inventory layout:
![2024-09-27T180857_devilutionx](https://github.com/user-attachments/assets/bc22715b-a147-4b03-a008-3c5a86b893e4)

If the special-case for 2x2 items was removed and instead item placement always used a stride of 1 players in this situation would be able to pick up one more 2x2 item.
