### ISSUE TITLE
[Feature Request]: Shrine effect suggestion

### ISSUE THREAD

**Issue by locksoft** [diasurgical/devilutionX#7033]
### Feature Type

Quality of Life

### Describe

Sorry if this suggestion is too wild (it is!), but I had to... :)

Most players are so good at this game they can recognize shrines by their names (when it's not a random one, of course). Not me, I've bad memory so I know only a few of them; I need to save the game before touching one, click it, see the result, possibly check online (https://diablo.fandom.com/wiki/Shrines_(Diablo_I)) when the result is not clear and decide if to keep it or reload the save and ignore it (I don't keep dangerous ones disabled).

I think it could be very nice to have an optional way to quickly identify the resulting effect hovering the mouse (or gamepad), maybe using the way unique items do, because some are a bit complicated:

![Shrines+](https://github.com/diasurgical/devilutionX/assets/9337221/0829c135-231d-423c-afe3-657bccaf08b9)

(I know, I know, it wasn't in the original game, but I had to give it a try. :)

P.S. Please, ignore the shrine description in the bottom bar, it's of course a Photoshop edit. :D

**Comment by AJenbo** [comment]
This would probably make a nice Lua mod. But I don't think it should go in the main code base. Looks nice though.

**Comment by FitzRoyX** [comment]
Yeah, if it's the type of shrine that makes subtle changes to stats, it's hard to even recognize what it did because that requires memorization of what your stats were before you clicked it. You either click every shrine without thinking and deal with the effects, or you figure out what the shrine does and avoid it using OP's savescum technique. If you're doing the latter, then shrine descriptions are better than playing the savescum minigame. I don't know why this feature's detractors don't understand that.

**Comment by julealgon** [comment]
@FitzRoyX 
> Yeah, if it's the type of shrine that makes subtle changes to stats, it's hard to even recognize what it did because that requires memorization of what your stats were before you clicked it. 
>
> ...
> I don't know why this feature's detractors don't understand that.

Focusing on this particular issue first: if your problem is that it is hard to tell what changed after clicking on a shrine (which I totally agree with), then the feature doesn't _need_ to be "describe shrine effects on hover", but instead "add a way to communicate shrine changes to the player".

In other words, instead of adding a pre-emptive description on the shrine, listings its effects, have it remain a mistery but make it obvious in the UI what changed _after_ clicking on it.

This could be done in a number of ways, including subtle ones like playing existing sounds.

I think this proposal would have more chance of making it than just exposing all the shrines effects upfront.

**Comment by locksoft** [comment]
My point is that, if you play casual, then the effect of a Shrine is not that important. In my first plays, if I couldn’t understand the effect, I carried on.
Once you start to play seriously, every bonus/malus is extremely important and you won’t undervalue it. So this forces you to pause the game and go and search that Shrine effect on some wiki. This spoils the atmosphere. Enabling the “safe” option won’t help much, because it excludes all the random shrines that could give benefits. So my idea it’s still a sort of help option, but really useful. Then, if you don’t want to use it, just leave it disabled.

**Comment by FitzRoyX** [comment]
> In other words, instead of adding a pre-emptive description on the shrine, listings its effects, have it remain a mistery but make it obvious in the UI what changed _after_ clicking on it.

Sounds complicated. How do you show that a shrine did nothing because Str was already at max? Or that a glimmering shrine would have identified your items but you had none? Or that you got a particular stat because of the time of day? You also can't lengthen the flavor text message duration because it's obstructive, or take over the description box.

Mouseover text is straightforward. You just have to accept that the "mystery" is a mirage. To me, it doesn't make sense to withhold information that can be so quickly deduced and undone with savescum.

**Comment by julealgon** [comment]
@FitzRoyX 
> Sounds complicated.

I never alluded to it being easy. Totally agree this is quite hard to do.

> How do you show that a shrine did nothing because Str was already at max? Or that a glimmering shrine would have identified your items but you had none? Or that you got a particular stat because of the time of day?

I don't have the answers for those questions at the moment. I would think about them more deeply if the idea itself was approved and I was involved in the design.
 
> Mouseover text is straightforward. 

True, but that doesn't mean it should be used here. Something being "easy to do" is not the defining factor for implementing it.

> You just have to accept that the "mystery" is a mirage. 

I don't. I'd rather expand upon it by removing the shrine names and have them all work like cauldrons, so that the player cannot guess the effects. I like the randomness factor that this introduces, personally.

> To me, it doesn't make sense to withhold information that can be so quickly deduced and undone with savescum.

Sounds like an easy fix: prevent save scumming. The _entire_ game is broken if you rely on save scumming for everything. It completely kills the original design (again, IMHO).

**Comment by DakkJaniels** [comment]
> I'd rather expand upon it by removing the shrine names and have them all work like cauldrons, so that the player cannot guess the effects. I like the randomness factor that this introduces, personally.

I like this, but also like the idea of names being randomized per session. So all Holy shrines would have the same effect in that game, but on a new game, it could (potentially) have a different effect.

**Comment by locksoft** [comment]
> I like this, but also like the idea of names being randomized per session. So all Holy shrines would have the same effect in that game, but on a new game, it could (potentially) have a different effect.

Ok, but that will change the nature of Diablo. The game wants you to know what a shrine does (besides the random ones on later levels).
The only problem is that a player cannot remember them all (especially with the Hellfire additional ones). I’d like a way to quickly know what they do without pausing the game and go to check online.
If then it’s implemented in the game itself or in an external mod (is that the mentioned “lua” above?) it’s the same.
Are there mods that do that? And are they compatible with this project?

**Comment by DakkJaniels** [comment]
Yeah sorry, I meant to add something about liking that for a mod, not for the DevilutionX.

**Comment by AJenbo** [comment]
Some one can make a mod using lua once 1.6.0 is released
