### ISSUE TITLE
[Issue Report]: Broken enemy movement

### ISSUE THREAD

**Issue by djvs** [diasurgical/devilutionX#7047]
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Enemy movement pretty broken, see video on discord:

https://github.com/diasurgical/devilutionX/assets/2954343/0e3cefc4-dba8-4323-a34a-77dc86478300

I'm running commit 3b4260dbbd633dc93139d5c6d992b0d37d6710d0 (from my other PR about window focus), was also an issue back at 8291d30dd14534ce7137098a4194195a1e8e93c4 (master).

### To Reproduce

It's when an enemy is coming up on you and/or evading.  

### Expected Behavior

Not sure exactly how the movement works normally, but it's definitely more fluid.

**Comment by StephenCWills** [comment]
Instead of linking to Discord, any chance you can attach the video to your post here on GitHub?

Also, it seems like it's pretty easy to reproduce, but it seems like the save you used in the video might help make testing faster since all you'd have to do is load game to reproduce. Would you also be able to provide that save as well?

**Comment by djvs** [comment]
https://github.com/diasurgical/devilutionX/assets/2954343/0e3cefc4-dba8-4323-a34a-77dc86478300

**Comment by djvs** [comment]
[save.zip](https://github.com/diasurgical/devilutionX/files/14874490/save.zip)

**Comment by kphoenix137** [comment]
Issue caused by incomplete implementation of corrected player tile occupation in https://github.com/diasurgical/devilutionX/pull/7043 which also extends to monsters.
