### ISSUE TITLE
[Issue Report]: Game loads endlessly

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#7463]
### Operating System

Linux x64

### DevilutionX version

Custom build (commit baaa906583800a4732f58134ed9f68e2f17a29fa)

### Describe

Game can not be loaded.

### To Reproduce

1. Load attached game
[endless.zip](https://github.com/user-attachments/files/17282606/endless.zip)
2. Go trough blue portal
3. Go through red portal
4. Save the game
5. Exit the game entirely
6. Load the game again
7. See that game can not be loaded

### Expected Behavior

No endless loading

### Additional context

Further events or possible causes have not yet been investigated

**Comment by kphoenix137** [comment]
Problem appears to be rooted in `PlaceUniqueMonst()`, where an infinite loop is entered:
https://github.com/diasurgical/devilutionX/blob/baaa906583800a4732f58134ed9f68e2f17a29fa/Source/monster.cpp#L348

`CanPlaceMonster()` returns `false` infinitely, deeming every iterated location as being Solid in `IsTileOccupied()` call via `IsTileSolid()`

**Comment by StephenCWills** [comment]
`LoadL1Dungeon()` calls `LoadDungeonBase()` before `Pass3()`.
https://github.com/diasurgical/devilutionX/blob/baaa906583800a4732f58134ed9f68e2f17a29fa/Source/levels/drlg_l1.cpp#L1328-L1335

`LoadDungeonBase()` calls `SetMapMonsters()` which begins by attempting to place Lazarus in the map. `PlaceUniqueMonst()` then runs that loop to find a random valid position to place him. However there are no valid positions because `Pass3()` hasn't been called yet, meaning `dPiece` is completely empty.
