### ISSUE TITLE
'quick' and 'haste' speed modifiers do not work as intended

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#839]
Because of the way the game handles frame skipping to increase attack speeds, some modifiers in the game end up having wrong effects on the final attack speeed.

For reference, here is the logic for each attack type that is affected by speed modifiers:
| Function | Logic |
| --- | --- |
| PM_DoAttack | https://github.com/diasurgical/devilutionX/blob/4a4486d6161028e69702bedec6cb071e6a5354c3/Source/player.cpp#L2617-L2629 |
| PM_DoRangedAttack | https://github.com/diasurgical/devilutionX/blob/4a4486d6161028e69702bedec6cb071e6a5354c3/Source/player.cpp#L2703-L2709 |

Notice how all frame skipping for both attacks always check frame 1 to decide how many frames to skip. However, these 2 methods are most of the time not fired for frame 1, and instead only begin to execute on frame 2 onwards. This has the effect that all frame skipping logic that is based on frame 1 is actually discarded. Effectively:

| Suffix | Modifier | Intended frame skips | Effective frame skips |
| --- | --- | --- | --- |
| "of readiness" | `quick attack` | 1 frame | 0 frames |
| "of swiftness" | `fast attack` | 2 frames | 1 frame |
| "of speed" | `faster attack` | 3 frames | 2 frames |
| "of haste" | `fastest attack` | 4 frames | 2 frames |

This behavior is caused by the way the game handles animation increments (see #838) as well as how attacks work when starting from a standstill. When performing player updates, animation transitions from several player modes cause the logic to repeat during the same frame depending on the return value of each processing function:
 https://github.com/diasurgical/devilutionX/blob/4a4486d6161028e69702bedec6cb071e6a5354c3/Source/player.cpp#L3416-L3454

Notice how each processing function can decide whether or not the loop should continue running, or if it should be aborted (variable `tplayer`). However, the `CheckNewPath` call does not provide this same functionality, as it does not affect `tplayer` which will always be `false` when it returns from the standing mode, as can be seen here:

https://github.com/diasurgical/devilutionX/blob/4a4486d6161028e69702bedec6cb071e6a5354c3/Source/player.cpp#L2075-L2078

`CheckNewPath` is where all requests to attack come from, meaning, whenever an attack animation is triggered from a standstill, the loop finishes and animation is incremented to frame 2 before `PM_DoAttack` has a chance to execute. Thus all logic that depends on frame 1 inside the attack functions will never execute.

There are a few ways to have frame 1 dependent logic to execute today, for example, attacking after walking. However, this is not how most normal attacks take place and thus why this problem is so impactful to weapon speed.

Here are a couple of saves to test the weapon speed behavior:
- Warrior (5 swords, one for each speed): [single_0.zip](https://github.com/diasurgical/devilutionX/files/5296086/single_0.zip)
- Rogue (3 bows, one for each speed): [single_1.zip](https://github.com/diasurgical/devilutionX/files/5296087/single_1.zip)

**Comment by PrisonOfMirrors** [comment]
Already a well known bug blizzard had a B's claim to fix it in 1.07 but didn't. The theory is that 4 frame increase would make melee attacks overpowered, so they didn't fix it.

**Comment by julealgon** [comment]
> The theory is that 4 frame increase would make melee attacks overpowered, so they didn't fix it.

@PrisonOfMirrors final effect compared to vanilla is actually 3 frames, not 4. You have to count the first frame which was being skipped before.

**Comment by PrisonOfMirrors** [comment]
I'm still all for fixing this bug, imo it's not op warrior is super underpowered compared to the sorceror anyway.

**Comment by FitzRoyX** [comment]
I've come to agree with fixing this, mostly because modding needs to make sense. You just can't have enchantment values doing nothing or having their own hidden logic. Any changes this may cause can be modded "back to how it was" by doing away with the fastest affix and lowering the base attack duration for all characters by 1.

**Comment by ikonomov** [comment]
With https://github.com/diasurgical/devilutionX/pull/5727 and a lengthy discussion on discord of this issue I think we can and probably should call it resolved.  After a thorough analysis Stephen discovered that all speed affixes can have an effect (in my opinion not insignificant) on the actual gameplay, if not the exact one that was originally intended.  We came to the conclusion that there is no way we can assume that the final behavior was not the intended one during the testing.  Two solutions were proposed, lowering the frames so that Haste skips 4 frames or doing the same but additionally removing the first frame skips in the code for all character attack animations by one.  Both would have a very significant effect on the gameplay which again we can't assume hasn't been part of the testing phase of the game development.

**Comment by kphoenix137** [comment]
@AJenbo was asking about this in Discord, so I'd like to add some more context for closing this issue for all to see. Several conversations have been had regarding this topic, with suggested possible solutions.  To paraphrase a very strong argument that was made, in my opinion, fixing this so that frame skips happen as [1, 2, 3, 4] rather than [0, 1, 2, 2] has 2 main problems:
* During development and playtesting, it's possible that Blizzard North was under the impression that it was working as intended, and they were sastified with the result. In the 1.07 patch notes, they wrote `Fixed bugs that prevented items with the suffixes Thieves, Speed/Haste, Balance/Stability/Harmony, and Piercing/Bashing/Puncturing from working properly.`. It's not entirely clear to me if this is referring to the problems with the intended frame skips not occurring, or if there was yet another bug with the original implementation. What is clear is that they returned to these affixes to "fix" them after the game's release, and either made a decision to not actually fix them to match the behavior we believe is correct, or they couldn't properly figure out how to do that. The problem here is that the intent is entirely unclear. The same could be said for many other things that have been fixed. For example: Damage VS Demons on bows. Which leads to the second point.
* Changing these frame skips would present a monumental rebalance to gameplay, which arguably would decrease the overall difficulty of the game, and potentially have absurd consequences when you consider Rogue with a bow, or Barbarian with an axe. This would effectively make the highest speed of Barbarian 4 frames, and Rogue 5 frames. (That's FIVE axe swings PER SECOND and FOUR arrows PER SECOND). As it stands, the fastest any character can attack per second is 3 times.

**Comment by julealgon** [comment]
@kphoenix137 while I wasn't part of the extended discussion on discord about this, I'd like to share a potential idea to solve this in a way that doesn't generate such a big imbalance while still allowing for each suffix to have a different effect.

You could increase the internal game update rate from 20fps to 40fps. With that adjustment, you could then have finer-grained frame increments for the speed affixes. For example, in 40fps update mode, 1, 2, 3, 4 would have to change to 2, 4, 6, 8 frames to be equivalent. Then, you could fine tune the new values to something like 1, 3, 5, 7, or 1, 3, 5, 6, or something similar, which would still generate a difference between each affix but not result in such crazy speeds in-game.

With a finer-grained frame interval, you could even create "non-discrete" increments and handle them using interpolation+randomness. For example, imagine that instead of:
- 1, 3, 5, 7 key-frame skips

You'd do:
- 1-2, 2-3, 3-4, 4-5

Meaning (in this case):
- half the time, first frame would be skipped. other half, first _and second_ frames would be skipped
- same for other intervals

This will lead into a variable attack speed that on average would be between 1,2,3,4 and 2,3,4,5 skip speeds, balancing it out over time.

Of course, increasing the game internal clock to 40fps changes a bunch of other things that would need to be doubled.

**Comment by AJenbo** [comment]
Rendering is already flexible, if it can it will render more frequent then logic and interpolate, if it can't keep up rendering will skip in favor of logic processing.

**Comment by glebm** [comment]
Processing is also rather cheap compared to rendering. Most of the CPU time is spent in rendering.

**Comment by julealgon** [comment]
> Rendering is already flexible, if it can it will render more frequent then logic and interpolate, if it can't keep up rendering will skip in favor of logic processing.

Ah nice.

> Processing is also rather cheap compared to rendering. Most of the CPU time is spent in rendering and audio.

![DumbAndDumberLloydGIF](https://github.com/diasurgical/devilutionX/assets/461579/5440b936-e4a8-4790-9806-e7d32ea5b502)

In all seriousness... I'd give it a shot. 20fps updates don't give you much of a window for fine-grained adjustments in the logic and attack-speed in particular would benefit from that IMHO.

**Comment by AJenbo** [comment]
I'm not the biggest fan of changing the internal tick rate, it could easily cause changes to gameplay, but getting time demos playing correctly would give some confidence.

**Comment by kphoenix137** [comment]
IIRC, Diablo 2 runs at a tick rate of 30, allowing for more unique levels of animation speeds. Although I'm not entirely sure it's worth putting in the work to increase the tick rate all for a couple of attack speed affixes.

**Comment by julealgon** [comment]
> IIRC, Diablo 2 runs at a tick rate of 30, allowing for more unique levels of animation speeds. .

Just keep in mind that jumping to a non-multiple of 20 will make things harder as it introduces potential rouding issues. This is why I proposed 40 initially since you can just double all frame counters with zero change in behavior.

> Although I'm not entirely sure it's worth putting in the work to increase the tick rate all for a couple of attack speed affixes

Fair, but remember this would also open the door for other animations, such as blocking and hit recovery to be more controllable as well. It would be especially useful for modding later where people would want to introduce more variations/affixes/etc.

**Comment by kphoenix137** [comment]
Sounds like a solid idea, would like to see it down the road. I think it's worth reopening as a long term goal. @AJenbo ?

**Comment by StephenCWills** [comment]
Keep in mind that damage-over-time effects will need to be halved if you double the game's tick rate. This could result in rounding errors.

**Comment by kphoenix137** [comment]
> 
Maybe it's possible to double the internal tick rate and then set everything you don't want to occur more than 20 times per second to process every other tick?

**Comment by StephenCWills** [comment]
Or we could modify Quick Attack to alternate between 0 and 1 skipped frames every other animation cycle, which would be equally complex and less broad/invasive.

I didn't mention this for a couple different reasons, but perhaps it's worth mentioning after all. Doubling timers could potentially cause integer overflow.

Personally, I'm not sold on increasing the tick rate of the game to 40 fps. However, I also wanted to say that rather than triggering DOTs every other frame, it would probably be a better strategy to increase the amount of precision for those computations to help mitigate the rounding errors.

**Comment by kphoenix137** [comment]
I think this would be a better approach:
`	int8_t skippedAnimationFrames = 0;

	if (HasAnyOf(player._pIFlags, ItemSpecialEffect::FastestAttack)) {
		skippedAnimationFrames = 2;
	} else if (HasAnyOf(player._pIFlags, ItemSpecialEffect::FasterAttack)) {
		skippedAnimationFrames = 1 + GenerateRnd(2);
	} else if (HasAnyOf(player._pIFlags, ItemSpecialEffect::FastAttack)) {
		skippedAnimationFrames = 1;
	} else if (HasAnyOf(player._pIFlags, ItemSpecialEffect::QuickAttack)) {
		skippedAnimationFrames = GenerateRnd(2);
	}`
	
I really dislike the idea of alternating every other swing because it creates this strange rhythm. Randomizing the chance of getting the extra skipped frame mixes it up a bit.

**Comment by julealgon** [comment]
I think that random approach would be an improvement even while keeping the current update rate (and indeed be less invasive of a change), but I still think you guys should seriously consider upgrading the internal tick rate from 20FPS in the future: 20FPS is just too low to work with for a lot of things.

**Comment by kphoenix137** [comment]
In all honesty, I think the correct thing to do would be to change the frame skips to what's intended, rather than mimicking the original broken behavior. Just need to convince the rest that it should be done.

**Comment by StephenCWills** [comment]
Seems backwards. Rather than coming to a conclusion on your own and then working to convince others, maybe try discussing with others first and then reach a conclusion. It's unclear how you jumped from 40 fps to RNG to what's intended, or what you even think the intended behavior should be.

**Comment by AJenbo** [comment]
> Accept balance impact.

I'm lacking a definition of what this means

**Comment by DakkJaniels** [comment]
Can't do number 5 without morphing.

**Comment by AJenbo** [comment]
Could just rename the ones that do the same number of frame skips to hide them...

**Comment by julealgon** [comment]
> > Accept balance impact.
> 
> I'm lacking a definition of what this means

I mean accepting that this option _will_ impact balance a bit but do not try to perform any rebalancing work. 1/2/3/4 and 1/2 will be more powerful than the current implementation if nothing else is changed.

> > Introduce artificial delay frames in attack animation then rebalance
> 
> It would effectively nerf all other weapons, you would need to rebalance the whole game at that point

Correct.

> > I'm assuming this is currently the selected option since this issue is closed 😅
> 
> When no good option exists, no change is the least controversial.

Fair enough.

**Comment by AJenbo** [comment]
on problem with the renaming is that they still have different prices for repair and item value.

**Comment by kphoenix137** [comment]
Per discussion in Discord last night, I decided to begin recording footage of single dungeon levels, testing between current frame skips (0/1/1/2) and proposed frame skips (1/2/3/4) to compare and contrast the differences. I thought of making creating test scenarios as well by setting up set levels with specific configurations of monsters to test both ways.

To expand on julealgon's No. 5, I think the appropriate temporary fix that should be altering the item description strings. This could either be permanent, or exist until a fix is accepted:

`Quick Attack` -> ` ` (Because it's 0 frame skips)
`Fast Attack` -> `Quick Attack` (Because it's 1 frame skip, and Quick Attack is the first tier of increased attack speed. Logically, 1 frame skip would be the first tier, because there's no frame skip between 0 and 1, and Quick Attack is the first and lowest available attack speed increase))
`Faster Attack` -> `Fast Attack` (Because it's 2 frame skips, the immediate next tier after Quick Attack)
`Fastest Attack` -> `Fast Attack` (Because it's 2 frame skips, same as above)

The first frame conditionally having different frame skips is more of a quirk of the item power, and I don't think that should influence the item string, since we only did it to preserve the original bug.

**Comment by StephenCWills** [comment]
> To expand on julealgon's No. 5, I think the appropriate temporary fix that should be altering the item description strings. This could either be permanent, or exist until a fix is accepted.

I'm rallying behind AJenbo here. It seems generally unwise strategically to implement a poorly considered halfway solution to "tide us over" until we have properly considered the implications of whatever we eventually settled on. People have dealt with this situation for 25 years, and the worst that happened is we all had big arguments over the definition of a bug, how hypocritical we are for fixing other bugs, and how absurd it is to want to stall until we get some real info. I can live with that for another 25 years, and at the risk of speaking for others, I'm going to assert that I'm sure everyone else can too.

If we are making any change that doesn't involve bugs we've introduced ourselves, it should be the accepted fix.

**Comment by kphoenix137** [comment]
> 

I don't disagree that solutions should not be implemented hastily (pun intended), and without serious consideration. This Issue report has existed for 16 days short of 3 years, and despite continual discussions, arguments, and debates, the issue remains untouched. Of course this is no guarantee that this issue will never be resolved, and there's no real way to predict something like that right now. I believe the item description strings and the functionality of attack speeds themselves are two intertwined, yet separate problems. The former is that the item strings are not accurate, and misleading to the player. The latter is the functionality of the frame skips/amount of frame skips themselves and whether or not they should be changed, and how. Fixing the accuracy of the item descriptions addresses one of the problems we have here and now, and one that is much easier to solve, and much less controversial as this has no effect on game mechanics. I don't think it's appropriate to put the cart in front of the horse, disregarding fixing item strings as a fix because of what _could_ be fixed at a future time that would invalidate my suggested fix. We don't know if it will be fixed at all. If the functionality of frame skips for attacks is modified at a later time, then item descriptions can be updated accordingly, with minimal effort.

**Comment by StephenCWills** [comment]
> This Issue report has existed for 16 days short of 3 years, and despite continual discussions, arguments, and debates, the issue remains untouched.

I believe I said I am okay with it going unaddressed for another 25 years. It expected it would be clear that acting like something needs to be done right this second before you've done the work to analyze the impact of the change is not a compelling argument. But maybe you weren't trying to convince me.

**Comment by kphoenix137** [comment]
> > This Issue report has existed for 16 days short of 3 years, and despite continual discussions, arguments, and debates, the issue remains untouched.
> 
> I believe I said I am okay with it going unaddressed for another 25 years. I expected it would be clear that acting like something needs to be done right this second before you've done the work to analyze the impact of the change is not a compelling argument. But maybe you weren't trying to convince me.

I didn't mean _literally_ right now. I'm sorry if I'm giving the impression that this is of utmost critical urgency. It's not. Isn't this the process? We are discussing it as we should.

**Comment by kphoenix137** [comment]
> I'm not sure what else you could mean by advocating for a temporary solution.

I think the difference between permanent and temporary at this point is just semantics. I'm proposing this as a permanent solution, and there's nothing to suggest that it wouldn't be permanent beyond speculation.

**Comment by AJenbo** [comment]
i think renaming it is worse then properly documenting there effects.

**Comment by kphoenix137** [comment]
I wasn't suggesting renaming the affixes

**Comment by kphoenix137** [comment]
![image](https://github.com/diasurgical/devilutionX/assets/68359262/d5a78114-e973-4a91-8f4d-94775b443d74)
![image](https://github.com/diasurgical/devilutionX/assets/68359262/80f86796-3dab-43f1-a015-c9dea2ef654e)
![image](https://github.com/diasurgical/devilutionX/assets/68359262/c854549e-d5ad-4ef0-b74d-f2e037ca5dbc)
![image](https://github.com/diasurgical/devilutionX/assets/68359262/a3d9f430-c6e0-4154-8ac9-87a192d07b51)

**Comment by kphoenix137** [comment]
![Screenshot_20230917_211711_Discord.png](https://github.com/diasurgical/devilutionX/assets/68359262/bd2d44c4-aebb-40ee-845e-ab563ed59135)

This would also not be the first time that an item description has been revised to make it more accurate to what the affix actually does.

**Comment by obligaron** [comment]
Just a small comment to increasing the game ticks from 20 to 40 (or other values):
This can be challenging for singleplayer games if we want to keep compatible with vanilla.

Assumption:
- We increase the game ticks from 20 to 40 (or another value)
- We want to stay compatible with vanilla singpleayer
- That means when loading we increase every number by 2 and if we save we divide by 2
- This would result changing "odd" ticks to the next "even" tick

This can result in some problems, where we truncate a odd value
- Should we round up or down? How does this affect the game play?
- When a user interaction starts at an "odd" tick (for example start attack)
- When a action finishes at an "odd" tick (for example a sword attack is finished sooner, see discussion about quick attack)
- Monsters get activated at an "odd" tick
- ...

That's why I'm a little bit skeptical about changing tick rate AND stay compatible with singleplayer vanilla saves.

**Comment by ikonomov** [comment]
Ideally we want all actions to take the same time, so this change should affect only those two affixes.  Currently the Quick suffix is actually quite useful, not just theoretically, but in practice.  Being able to land the first hit with slower attack speed when engaging with monsters that have fast attack speed can make all the difference.  The same can be said for Haste compared to Speed affixes for weapons that a character has a natural slow attack speed with, for example most melee weapons for a Sorcerer or when using an axe with a Rogue.  Although the variation in damage output from these affixes will be a welcome change it is absolutely not needed in order to justify having 4 different speed affixes.
