### ISSUE TITLE
ARM support 

### ISSUE THREAD

**Issue by Askmewho** [diasurgical/devilutionX#87]
[ 50%] Building CXX object CMakeFiles/devilution.dir/Source/mpqapi.cpp.o
/home/pi/Desktop/devilutionX/Source/mpqapi.cpp: En la función ‘void dvl::mpqapi_xor_buf(char*)’:
/home/pi/Desktop/devilutionX/Source/mpqapi.cpp:98:8: error: ‘_rotl’ no se declaró en este ámbito
   v1 = _rotl(v1, 1);
        ^~~~~
CMakeFiles/devilution.dir/build.make:530: fallo en las instrucciones para el objetivo 'CMakeFiles/devilution.dir/Source/mpqapi.cpp.o'
make[2]: *** [CMakeFiles/devilution.dir/Source/mpqapi.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
CMakeFiles/Makefile2:72: fallo en las instrucciones para el objetivo 'CMakeFiles/devilution.dir/all'
make[1]: *** [CMakeFiles/devilution.dir/all] Error 2
Makefile:83: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

**Comment by AJenbo** [comment]
What platform are you trying to compile for? Could you get the error message in English?

**Comment by Askmewho** [comment]
Its armhf. Ok, I will.

**Comment by AJenbo** [comment]
Arm is currently untested/unsupported, but we would love patches that enables it. The first minor issue that you have bumped in to is that arm doesn't have __rotl so you would need to implement it in C.

**Comment by Askmewho** [comment]
Ok. I will try! Thanks

**Comment by ApertureSecurity** [comment]
@Askmewho  

I have already done this work. I am thinking that this week I will open a REPO for the ARM distro.

**Comment by Askmewho** [comment]
@ApertureSecurity let me know when you thats available

**Comment by AJenbo** [comment]
I have added an implemtantion of _rotl and _rotr and the code is moving along nicely:
![screen00-ConvertImage](https://user-images.githubusercontent.com/204594/57028120-2a95b980-6c36-11e9-96fa-c63e0e24d7a9.png)
I did have to disable a few things to get it running, but you'r able to walk but only down/right (probably because of char unsiged on ARM).

**Comment by Askmewho** [comment]
good! let me know if you resolve the issue! I will test it (and make a short review) on rpi and other boards. Ive tried this game with notaz binaries on arm (he decompiled the game and recompiled to arm) on wine (arm) and... it works really good but has some minor glitches as expected and its difficult to setup for others (custom kernel... and wine) . Notaz D2 works great, but of course, its not open. thanks @AJenbo

**Comment by AJenbo** [comment]
I managed to work around the performance issue today by blitting directly to the window surface instead of using the texture render, the downside is that you get no scaling this way. I don't expect to be working much on the ARM port until x86_64 has been fully solved. Probably they share some issues any way. So hopfully some one else is willing to dive into this..

**Comment by AJenbo** [comment]
ARM (only 32bit was tested) builds are now fully working. Performance was tested on a Raspberry Pi 3+, with the right settings the game runs true to the original, but it is not able to handle much more then that. https://github.com/diasurgical/devilutionX/pull/103

`upscale` has been added to the ini file, settings this to `0` disables use of OpenGL and can help a lot with performance. In my experience doing so when running the Pi without OpenGL support (default for current Raspbian) gives the best performance, though it looks like it might be able to handle upscaling given the right settings.
