### ISSUE TITLE
Happyfun 1.5x zoom toggle.

### ISSUE THREAD

**Issue by clort81** [diasurgical/devilutionX#884]
Zoom toggle 2x scale was too zoomed in for me so i made a little hack to get 1.5x zoom.

[scrollrt.cpp.txt](https://github.com/diasurgical/devilutionX/files/5376187/scrollrt.cpp.txt)

![bettersize](https://user-images.githubusercontent.com/51511737/95953938-e5018800-0dfa-11eb-86dc-ec07832d5bd1.jpg)

**Comment by AJenbo** [comment]
Please link to your git repo or patch file instead of a full cpp renamed as txt

**Comment by clort81** [comment]
web says i use 'diff -u' to make a patch.  github only accepts '.txt'
[scrollrt.cpp.patch.txt](https://github.com/diasurgical/devilutionX/files/5376920/scrollrt.cpp.patch.txt)
summary picture:
![smallbig](https://user-images.githubusercontent.com/51511737/95967173-3d8d5100-0e0c-11eb-9438-6606a2df6007.jpg)

**Comment by AJenbo** [comment]
Hmm, at least the patch is short and in any case easier to read than posting the entire file. But I would really recommend that you fork the project and push your changes so that we can collaborate via GitHub rather than sending patches. Then you also wouldn't have to put comments on all the lines you change like it was 1995 :)

This looks wrong and is probably the reason you have the holes in the right side of the render
```patch
-		if (columns & 1) {
+		if (int(columns/1.5) & 1) { // clort was 2, cast to int for modulo
```

From what I can tell you didn't actually make it scale by 1.5 you just made it align as if it was a 1.5 scaling. The actual scaling happens on line 900-927 in the `Zoom()` function.

A colose up of you screen shot also shows that all pixels are 2x2 if it was 1.5 scaling some should be 1x1 and some 2x2.

You can get rid of the main panel with this set of changes:
```
@@ -1232,9 +1232,6 @@ void DrawView(int StartX, int StartY)
 	DrawPlrMsg();
 	gmenu_draw();
 	doom_draw();
-	DrawInfoBox();
-	DrawLifeFlask();
-	DrawManaFlask();
 }
 
 extern SDL_Surface *pal_surface;
@@ -1426,27 +1423,6 @@ static void DrawMain(int dwHgt, BOOL draw_desc, BOOL draw_hp, BOOL draw_mana, BO
 		DoBlitScreen(0, 0, SCREEN_WIDTH, ysize);
 	}
 	if (ysize < SCREEN_HEIGHT) {
-		if (draw_sbar) {
-			DoBlitScreen(PANEL_LEFT + 204, PANEL_TOP + 5, 232, 28);
-		}
-		if (draw_desc) {
-			DoBlitScreen(PANEL_LEFT + 176, PANEL_TOP + 46, 288, 60);
-		}
-		if (draw_mana) {
-			DoBlitScreen(PANEL_LEFT + 460, PANEL_TOP, 88, 72);
-			DoBlitScreen(PANEL_LEFT + 564, PANEL_TOP + 64, 56, 56);
-		}
-		if (draw_hp) {
-			DoBlitScreen(PANEL_LEFT + 96, PANEL_TOP, 88, 72);
-		}
-		if (draw_btn) {
-			DoBlitScreen(PANEL_LEFT + 8, PANEL_TOP + 5, 72, 119);
-			DoBlitScreen(PANEL_LEFT + 556, PANEL_TOP + 5, 72, 48);
-			if (gbMaxPlayers > 1) {
-				DoBlitScreen(PANEL_LEFT + 84, PANEL_TOP + 91, 36, 32);
-				DoBlitScreen(PANEL_LEFT + 524, PANEL_TOP + 91, 36, 32);
-			}
-		}
 		if (sgdwCursWdtOld != 0) {
 			DoBlitScreen(sgdwCursXOld, sgdwCursYOld, sgdwCursWdtOld, sgdwCursHgtOld);
 		}
@@ -1517,23 +1493,7 @@ void DrawAndBlit()
 
 	lock_buf(0);
 	DrawView(ViewX, ViewY);
-	if (ctrlPan) {
-		DrawCtrlPan();
-	}
-	if (drawhpflag) {
-		UpdateLifeFlask();
-	}
-	if (drawmanaflag) {
-		UpdateManaFlask();
-	}
-	if (drawbtnflag) {
-		DrawCtrlBtns();
-	}
-	if (drawsbarflag) {
-		DrawInvBelt();
-	}
 	if (talkflag) {
-		DrawTalkPan();
 		hgt = SCREEN_HEIGHT;
 	}
 	scrollrt_draw_cursor_item();
```

**Comment by mgpat-gm** [comment]
Something similar happens when I zoom in with the "z" button in ubuntu at 2560x1440. A section of the map appears. I'll update once I can make a video.

**Comment by AJenbo** [comment]
> Something similar happens when I zoom in with the "z" button in 1.1.0 on ubuntu at 2560x1440. A section of the map appears. I'll update once I can make a video.
is it only when walking in some directions?

**Comment by mgpat-gm** [comment]
@AJenbo It is any direction. It appears to be projected outside right of the boundaries of the normal map and only when my character is on the right side of the map. Maybe it is generated the whole time, but my resolution prevents me from viewing it. As you can see, the error portion is zoomed in even further.

123 | 456
---------- | ----------
![1](https://user-images.githubusercontent.com/60494513/96065526-62aead80-0e66-11eb-8f39-da256b4fe899.png) | ![4](https://user-images.githubusercontent.com/60494513/96065542-63dfda80-0e66-11eb-84b5-1455c058cf79.png)
![2](https://user-images.githubusercontent.com/60494513/96065532-63474400-0e66-11eb-8b1f-4d60b8adf3e9.png) | ![5](https://user-images.githubusercontent.com/60494513/96065548-63dfda80-0e66-11eb-97d2-aed7732c7461.png)
![3](https://user-images.githubusercontent.com/60494513/96065535-63474400-0e66-11eb-8e6f-0cf3d728cf1f.png) | ![6](https://user-images.githubusercontent.com/60494513/96065554-64787100-0e66-11eb-9a70-5120fb55e0ef.png)

**Comment by AJenbo** [comment]
Ah, this is a different cause than the sawtooth. The reason it is 4x is that the zoom function reads and writes to the same surface, so if an area isn't overwritten with new content in the next frame it will 2x the previous frame in that area.

The reason for the gap is that the edge of the map is covered by dirt tiles which only have content higher up. But since the tiles do have content they aren't being filled with black, resulting in you being able to see the previous frame through the non existing floor.

It's a bit of a special case, but shoudn't be to hard to fix.

**Comment by AJenbo** [comment]
A better solution for this would be to allow for a software render and have SDL upscale things in software.:
`Uint32 rendererFlags = SDL_RENDERER_ACCELERATED;`
