### ISSUE TITLE
Low performance when using higher than 1080p resolutions

### ISSUE THREAD

**Issue by Lrflx** [diasurgical/devilutionX#913]
Now I understand that it's kinda pointless and almost impossible to play older isometric games like this in 4K, everything is too small and all that, but in 1440 it actually looks and plays very nicely. Problem is, when using this resolution fps constantly drops lower than 60. I know that original game couldn't go higher than 30, but here all these frame fluctuations create noticeable stutters.

**Comment by AJenbo** [comment]
Are you using the official release or some other build?

**Comment by Lrflx** [comment]
Latest version from here, 1.1.0
Windows 10 x64, Xeon E5-1650, gtx 1080 ti, 16gb ram

**Comment by qndel** [comment]
the original ran only at 20 fps and I got a pretty similar setup to you and it runs at stable 60 fps on 4k 🤷

**Comment by AJenbo** [comment]
@Lrflx can you give us some metrics for your system load when running the game. What is the actual desktop resolution? What happens if you disable upscaling in the ini?

**Comment by Lrflx** [comment]
Ok, frame times look like this most of the time https://ibb.co/567ZShW
Cpu load is about 30%. I tried with desktop at 4k and 1440 both, also windowed, all show similar results. When using 1080 and lower I don't have any problems at all, only at higher res. Upscaling doesn't seem to influence anything performance wise.
It's possible problem is on my side ofc, just have no idea where to look. Belzebub works fine btw, but I don't like its additions

**Comment by AJenbo** [comment]
Could you give us actual resolutions instead of marketing terms, my monitor is 3440x1440, is that what you are referring to by 1440?

Almost all rendering in DevilutionX happens on the CPU in 8bit and is then converted to 32bit before it is set to the GPU for upscaling and presentation. I could easily see there being bandwidth issues when trying to do this at 3840x2160. Also, keep in mind that the game is single threaded which also causes some limitations in this regard.

Belzebub is a completely different engine written from scratch, afaik it renders the game on the GPU, so the system requirements are very different (requiring a capable GPU, but not requiring as much of the CPU). Eventually, we hope to provide a GPU based renderer for capable systems.

**Comment by Lrflx** [comment]
Ok, thank you for answering! My actual resolution is 3840x2160, but I play in older games like this in 2560x1440 usually.
It's kinda what I expected about game being bottlenecked on cpu side. Adding gpu support would be really nice, ofc it's not something that could be implemented easily I understand, still will be looking forward to try it in future.
