### ISSUE TITLE
Would fallout 1 ever be possible to port to the Vita? Are there any guides on how to begin this process myself?

### ISSUE THREAD

**Issue by barrywilcox** [diasurgical/devilutionX#979]
Hello apologies for posting this here but I'm not quite sure where else to ask this question.

It needs a specific expertise to be answered by someone with knowledge in porting old PC titles.

I am dreaming of the day when the highly enthralling fallout 1 PC game may be ported to the Vita.
I am of the mindset that the Vita is the best console made of all time and to have this amazing game here along side Diablo 1 and Diablo 2 would be quite amazing.

Having some of the amazing developments of Blizzard and Interplay on the same device,  simply amazing.

My question is,  

-  1  would this even be a possibility to have happen? 
-  2 how much world would it require,  is it within the realm of someone like myself with a limited coding background
-  3 if possible is there a way to donate money towards this project. I would be willing to donate money for this project to be attempted if it's beyond my skill levels. 

Thank you to anyone who is reading this, Thank you for making the Diablo port and your wonderful Vita work, I am very appreciative and if you do not want this post here please  just  tell me and I will delete this.

**Comment by galaxyhaxz** [comment]
Of course it's possible! Anything is possible as long as you have a big enough life savings meant for college and feel generous enough to donate it along with 2 years of your life!

First and foremost you have to reverse engineer the game. This can take awhile depending on how complex or large it is, and how bad the code is optimized. For devilution I used IDA pro and paired it with existing documentation to give the binary a complete layout. Then decompiled the code. It took about 4 months total.

Documenting the binary will require you to understand and figure out the structs and magic numbers. The bss must be completely layed out or you will wind up with many overflows.

At work ATM so that's all I can type. I too think the Vita and PSP are awesome consoles. Vita would work well since it has dual analogs. Wish you luck!

**Comment by MaxDesiatov** [comment]
https://github.com/pingw33n/vault13 and https://github.com/darkf/darkfo are the most advanced reverse engineering efforts for both Fallout 1 and Fallout 2 (as both run on basically the same engine)

**Comment by galaxyhaxz** [comment]
Those look to be a good place to start, but the Vita only has a C/C++ compiler and those are In rust/python respectively, so one would have to address that first and foremost.

**Comment by MaxDesiatov** [comment]
I'm a Rust/Swift person, if anyone were to ask me I'd rather invest my time in porting Rust to Vita than rewriting the engine in C/C++ 🙈

**Comment by galaxyhaxz** [comment]
I haven't used Rust myself but heard good things about it. Currently I'm working with Go :)

**Comment by AJenbo** [comment]
> Hello apologies for posting this here but I'm not quite sure where else to ask this question.

to answer your first question: the chat (see project readme) would be the appropriate place for a free form conversation about the general subject.

**Comment by galaxyhaxz** [comment]
They were asking about donations to porting fallout. In that case I'm sure you could pay someone to port if for you, but expect to have a fun time searching for someone that will

**Comment by qndel** [comment]
well, the search time is inversely proportional to the amount of money offered :D

**Comment by galaxyhaxz** [comment]
I demand a ransom for...... one millions dollars! :imp:

**Comment by AJenbo** [comment]
@barrywilcox in case you haven't noticed we now have Vita support.
